### PR TITLE
[WIPTEST] Implement Collections for RBAC Role

### PR DESCRIPTION
**Pull request by LandoCalrizzian**
{{pytest: -v -k 'test_role_name_required_error_validation or test_rolename_duplicate_validation or test_delete_default_roles or test_edit_default_roles or test_permission_edit or test_permissions or test_rolename_required_error_validation or test_rolename_duplicate_validation or test_form_button_validation or test_group_ownership_on_user_only_role or test_group_ownership_on_user_or_group_role or test_tagvis_tag_datacenter_combination'}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3071549dd8ec7b06d7d1831bd6d525eb3a8eba55:

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 35:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by LandoCalrizzian** [comment]
Closing this PR and combining it with #5734

**Pull request closed without merging**
