### PR TITLE
[1LP][RFR] Changes to ap_cli naming & current_appliance usage removal

### PR DESCRIPTION
**Pull request by lcouzens**

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
@lcouzens You gotta sign it to get PRT result.

**Comment by lcouzens** [comment]
@jkrocil I thought I did, sorted now :)

**Pull request merged**
