### PR TITLE
[1LP][RFR] fix collectonly for dummy-appliance

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
test_visual_infra.py was using appliance provided data in test parameterization that equaled a already known
constant, so i just shifted to to use that

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 46f529580f892eb7bc8406216f80d8a8ef3987ec:

`cfme/tests/configure/test_visual_infra.py`:
- :bangbang: Line 33:1: **E305** *expected 2 blank lines after class or function definition, found 1*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6029ee45acc2efa3ca4b87a9ae670ee3a92db16d:

`cfme/tests/configure/test_visual_infra.py`:
- :bangbang: Line 34:1: **E305** *expected 2 blank lines after class or function definition, found 1*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by anurag03** [comment]
I used dynamic parametrization because the content of the drop down kept on changing from "5" to "5 Items". I wasn't aware of the ill effects of doing that. @RonnyPfannschmidt, thanks for highlighting this issue and fixing it :)

**Comment by mfalesni** [comment]
@izapolsk I see there are some JSPaginationPane errors in the 5.9 build, can you take a peek?

**Comment by izapolsk** [comment]
@mfalesni , sure, looking.

**Pull request merged**
