### PR TITLE
changing existing appliance nav calls to use Server

### PR DESCRIPTION
**Pull request by izapolsk**
Purpose or Intent
=================
- Since Loggedin is moved to Server, all existing nav calls have to be updated. 
 I made appropriate replacement.
- removed old destination.

P.S. I left Dashboard and Configuration in the same place since those are not completely moved to another place.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e49f877e6ba29facd9f52ff8627818fd9388e0b4:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c387f4187727a2b0eda1c48e3d0c97587a6bf1bd:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4796764a1237ffe1d9779e00fcdfcf63e65e31eb:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by izapolsk** [comment]
current PR is logical continuation of PR #3587

**Pull request merged**
