### PR TITLE
Test rel tables funct updated

### PR DESCRIPTION
**Pull request by jdemon519**
Modified the functionality in test_pods_rel and test_images_rel.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 5532bdc38b340ee251209fe74eae08bcff9f4caf:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7b298d1dc70408c5c821cc4698eed2feba8167f5:

`cfme/tests/containers/test_pods_prop_data_integrity.py`:
- :bangbang: Line 23:101: **E501** *line too long (107 > 100 characters)*
- :bangbang: Line 24:101: **E501** *line too long (118 > 100 characters)*
- :bangbang: Line 33:101: **E501** *line too long (117 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 910fad71d5a5477f1a12d435cc4ae7feb08b6566:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@jdemon519 you need to squash all the commits

**Comment by jdemon519** [comment]
mfalesni I guess it didn't work, I'll try again

**Comment by dajoRH** [comment]
Lint report for commit ecd0dc8b138fd91d43c3cb2ebfd6f6d24b4d308e:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@jdemon519 still many commits ...

**Comment by psav** [comment]
#3328 is a newer version of this? please close one off so we don't double review.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request closed without merging**
