### PR TITLE
[WIP] ManageIQ Ansible tests refactoring

### PR DESCRIPTION
**Pull request by pavelzag**
{{pytest: cfme/tests/containers/test_manageiq_ansible_users.py -v --use-provider cm-env2 }}

Purpose or Intent
=================

ManageIQ Ansible Modules are moving to Ansible upstream. Doing some clean up before the move
http://docs.ansible.com/ansible/devel/manageiq_user_module.html

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9258f8d91c13a5a868dc21806e677e391d7d9072:

Lint OK! :cake: :punch: :cookie: .

* 9258f8d91c13a5a868dc21806e677e391d7d9072
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f0d556914a56f5e899bd165409dfe963eea4b4f2:

`utils/ansible.py`:
- :bangbang: Line 165:101: **E501** *line too long (104 > 100 characters)*
- :bangbang: Line 168:101: **E501** *line too long (130 > 100 characters)*
- :bangbang: Line 169:101: **E501** *line too long (128 > 100 characters)*
- :bangbang: Line 170:101: **E501** *line too long (120 > 100 characters)*
- :bangbang: Line 171:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 174:101: **E501** *line too long (125 > 100 characters)*
- :bangbang: Line 175:101: **E501** *line too long (117 > 100 characters)*
- :bangbang: Line 178:101: **E501** *line too long (120 > 100 characters)*
- :bangbang: Line 179:101: **E501** *line too long (130 > 100 characters)*
- :bangbang: Line 180:101: **E501** *line too long (130 > 100 characters)*
- :bangbang: Line 181:101: **E501** *line too long (112 > 100 characters)*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Please re-open PR if necessary

**Pull request closed without merging**
