### PR TITLE
[1LP][RFR] fixed error: str object has no attribute pick; added import wait_for

### PR DESCRIPTION
**Pull request by lina-nikiforova**
{{ pytest: -v cfme/tests/control/test_basic.py -k 'test_modify_condition_expression or test_assign_condition_to_control_policy or test_condition_crud' --long-running }}

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
unfortunately prt doesnt support putting in pytest commands like that

**Comment by RonnyPfannschmidt** [comment]
i believe te shortest variant in that case is listing the file, and using `-k 'test_modify_condition_expression or ....'`

**Comment by lina-nikiforova** [comment]
Hi, I believe it works https://github.com/ManageIQ/integration_tests/pull/7702
and I saw correct output in CI tests there

**Comment by RonnyPfannschmidt** [comment]
@lina-nikiforova i just cross-checked, only one of the commands was executed
so the result is incorrect

**Comment by lina-nikiforova** [comment]
@RonnyPfannschmidt indeed... changed the comment as you suggested

**Pull request merged**
