### PR TITLE
Add compatibility with ManageIQ.qe stuff + fix test_requirements

### PR DESCRIPTION
**Pull request by jkrocil**
Purpose or Intent
=================
Also, added `provider_discovery` to requirements to fix a collection issue and sorted the damn requirements

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 91ac097978d76aa748846b4224edb7fed1e88453:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 96bd5a97161cbef61914f7159a8c3dc6f38b1f38:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
Tested locally against 5.6.2.0 and 5.7.0.4.

**Comment by jkrocil** [comment]
Upstream fails in PRT because it's an old upstream without ManageIQ.qe.... Templates created after Oct 6th should work.

**Pull request merged**
