### PR TITLE
Fix menu check

### PR DESCRIPTION
**Pull request by mkoura**
{{pytest: cfme/tests/configure/test_visual_cloud.py -v -k test_start_page}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b9b5ab2ea127a44a0f972baba383a5c598a1b6ea:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mkoura** [comment]
There seems to be timing issue that wait_for_ajax can't currently handle. The `get_current_menu_state` method attempts to read values of level1 and level2 menus before the menu is expanded.

**Comment by psav** [comment]
If I remember correctly, it doens't need to expand them to read their CSS classes

**Comment by psav** [comment]
I'm happy to merge this as it resolves the menu nav import error that we were seeing before

**Comment by dajoRH** [comment]
Lint report for commit 2b9f25b72d602e8e97dc8314ec61d8ad03eef629:

`cfme/web_ui/menu.py`:
- :bangbang: Line 137:25: **E126** *continuation line over-indented for hanging indent*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a84a69377425c9069a3a0dc5f4e9d4afdec830c6:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mkoura** [comment]
@psav it's now getting the 'textContent' attribute - this also works for hidden elements. The `element.text` works only for visible elements (and `sel.text()` is using `move_to_element()` which also requires element to be visible).

**Comment by mfalesni** [comment]
@mkoura I have known about this issue for a long time since I was playing with the Automate class schemas and I could not read hidden texts - the field labels. I was thinking of emulating the text getter with javascript if it reads an empty text from the element. I would do some trickery to read it, but I don't know how correct would that approach be... :) There would have to be something htat takes innerHTML and somehow strips the eventual html tags to get the same result like the .text param.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0ad1a76d226bf226a0cb9d19ffe437211b1bd936:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 288cd8c6a9539a254fb8214353748de86f3b4d37:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
