### PR TITLE
[WIPTEST]Csv v2v

### PR DESCRIPTION
**Pull request by sshveta**
^ Make sure to prefix the Title with [WIP]/[WIPTEST]

Purpose or Intent
=================

__Fixing__ X because it is currently doing Y which is incorrect. It should be doing Z.

or

__Extending__ X because I need it to do Y so that I can update / add more test cases; PR #123 depends on it.

or

__Adding tests__ for feature X to cover cases Y and Z. They were implemented in product version 1.2.3.

or

__Updating tests__ for feature X because the behavior changed in product version 1.2.3.

--
These should serve mainly as a guideline. The more related information you provide, the better. :wink:

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3130322793dd0ee5bec03490d7c05724e445d4a4:

`cfme/tests/v2v/test_csv_import.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic.exceptions.WidgetOperationFailed' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.fixtures.v2v_fixtures.mapping_data_vm_obj_mini' imported but unused*
- :bangbang: Line 49:20: **E124** *closing bracket does not match visual indentation*
- :bangbang: Line 126:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 242:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0973c5cef844ff38b3aaf355b1f0cae804febf14:

`cfme/tests/v2v/test_csv_import.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic.exceptions.WidgetOperationFailed' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.fixtures.v2v_fixtures.mapping_data_vm_obj_mini' imported but unused*
- :bangbang: Line 179:34: **E127** *continuation line over-indented for visual indent*
- :bangbang: Line 196:34: **E127** *continuation line over-indented for visual indent*
- :bangbang: Line 213:34: **E127** *continuation line over-indented for visual indent*
- :bangbang: Line 247:34: **E127** *continuation line over-indented for visual indent*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bcc1108b2c561cc021d150df76a7b94e03a38900:

`cfme/tests/v2v/test_csv_import.py`:
- :red_circle: Line 6:1: **F401** *'widgetastic.exceptions.WidgetOperationFailed' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.fixtures.v2v_fixtures.mapping_data_vm_obj_mini' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by sshveta** [comment]
Opening https://github.com/ManageIQ/integration_tests/pull/8761/ instead

**Pull request closed without merging**
