### PR TITLE
[WIP] Fix api port test

### PR DESCRIPTION
**Pull request by jadhaj**
Removed webui replaced with widgetastic

{{ miq-runtest cfme/tests/openstack/infrastructure/test_provider.py::test_api_port --use-provider uc_ci }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 54184fbb9d2d60ca0c476d32befbe34bcf0c41bd:

`cfme/tests/openstack/infrastructure/test_provider.py`:
- :bangbang: Line 16:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 16:1: **E112** *expected an indented block*
- :bangbang: Line 16:2: **E999** *IndentationError: expected an indented block*
- :bangbang: Line 16:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 16:7: **E225** *missing whitespace around operator*
- :bangbang: Line 17:5: **E113** *unexpected indentation*
- :bangbang: Line 20:3: **E225** *missing whitespace around operator*
- :bangbang: Line 20:5: **E225** *missing whitespace around operator*
- :bangbang: Line 20:7: **E225** *missing whitespace around operator*
- :bangbang: Line 23:7: **E225** *missing whitespace around operator*

Hmmm
:scream: You might like to check the lint of your code :point_up: 

* 878400063448c35876dca3c5e708b604fb7c0981
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 6e8a3c547f19830a96cc1f3087b8b683be2860a2
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 54184fbb9d2d60ca0c476d32befbe34bcf0c41bd
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root

**The PR might not be acceptable in this state** :rage4:.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef299671417680a95ebb593903d1bfc880b6dfb1:

Lint OK! :cake: :punch: :cookie: .

* 878400063448c35876dca3c5e708b604fb7c0981
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 6e8a3c547f19830a96cc1f3087b8b683be2860a2
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 54184fbb9d2d60ca0c476d32befbe34bcf0c41bd
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* ef299671417680a95ebb593903d1bfc880b6dfb1
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root

**The PR might not be acceptable in this state** :rage4:.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3e81bf49e5ba1ad0b767f257237413dd8ad58a40:

Lint OK! :cake: :punch: :cookie: .

* 878400063448c35876dca3c5e708b604fb7c0981
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 6e8a3c547f19830a96cc1f3087b8b683be2860a2
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 54184fbb9d2d60ca0c476d32befbe34bcf0c41bd
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* ef299671417680a95ebb593903d1bfc880b6dfb1
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root

**The PR might not be acceptable in this state** :rage4:.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c5fc51903f9d6b4a1abc56a54951c5542df01e77:

Lint OK! :cake: :punch: :cookie: .

* 878400063448c35876dca3c5e708b604fb7c0981
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 6e8a3c547f19830a96cc1f3087b8b683be2860a2
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root
* 54184fbb9d2d60ca0c476d32befbe34bcf0c41bd
  * Commit author is root (did you create your git identity?)
  * Commit author email starts with root

**The PR might not be acceptable in this state** :rage4:.

*CFME QE Bot*

**Comment by jadhaj** [comment]
Reopened

**Pull request closed without merging**
