### PR TITLE
[RFR][NOMERGE] switch the hardcoding of marionette to True in order to test

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
against the new firefox images

### CODE REVIEW

**Comment by mshriver** [comment]
I pushed a commit to include @izapolsk PR for wt.core for FF60+ support.

**Comment by mshriver** [comment]
rebased to get the pyvmomi requirement fix in

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 613235f0f87aab9226f6024d42f5612f640c65d7:

`cfme/utils/browser.py`:
- :bangbang: Line 210:5: **E303** *too many blank lines (2)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d6ae1efeab2ac5ccb226eb5c7192833669c266f1:

`cfme/utils/browser.py`:
- :bangbang: Line 210:5: **E303** *too many blank lines (2)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
Not expecting PRT results here, we're running a Jenkins build for this branch to test wharf2 with newer firefox.

**Pull request merged**
