### PR TITLE
[RFR] Keep alive thread :(

### PR DESCRIPTION
**Pull request by psav**
Necessary, for making tests pass + keeping keepalive ;)

### CODE REVIEW

**Comment by psav** [comment]
I'm seeing this
2017-02-16 11:22:39,301 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:23:09,325 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:23:39,370 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:24:09,399 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:24:39,424 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:28:41,808 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:29:11,848 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:32:46,843 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:33:16,889 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:33:46,910 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:34:16,952 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:34:47,001 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:35:17,044 [D] renewing connection (utils/browser.py:246)
2017-02-16 11:35:47,070 [D] renewing connection (utils/browser.py:246)
But the thread was never killed as far as I can see so not sure what happened and why there was a 4 min gap and a 3 min gap

**Comment by RonnyPfannschmidt** [comment]
wow, having to write such workarounds is  a pile of sadness with crocodile tears

**Comment by dajoRH** [comment]
Lint report for commit 6d9396b810bbd8d2b2a6576c7e57805847c96386:

`utils/browser.py`:
- :red_circle: Line 120:5: **N802** *function name should be lowercase*
- :red_circle: Line 120:5: **N803** *argument name should be lowercase*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mfalesni** [comment]
We'll see, worst case we revert.

**Pull request merged**
