### PR TITLE
Made the provider types entirely modular

### PR DESCRIPTION
**Pull request by psav**
Purpose or Intent
=================

* Before provider types (the real types, infra, cloud etc....) were
  baked into the system, hardwired so to speak. Now they are free!
* New provider types can be added with ease, by adding one file, and at
  the moment editing another. Perhaps this will change soon too.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d36ac411e48cd1394b23c19c533781bf214607a6:

`cfme/common/provider.py`:
- :red_circle: Line 10:1: **F401** *'defaultdict' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 00cee1332b2db05008051cc76ad2589e55fd389f:

`cfme/common/provider.py`:
- :red_circle: Line 10:1: **F401** *'defaultdict' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 81904a7d3c6417a7560f459b7c56451bef797112:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 27103a59349acd22ad92c0fd68267fe49bedc50f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 02ae0446e7bda030b33fff06f5d98dbea6bea655:

`cfme/tests/infrastructure/test_providers.py`:
- :red_circle: Line 14:1: **F401** *'providers' imported but unused*

`utils/providers.py`:
- :red_circle: Line 10:1: **F401** *'partial' imported but unused*
- :red_circle: Line 14:1: **F401** *'toolbar' imported but unused*
- :red_circle: Line 21:1: **F401** *'version' imported but unused*
- :red_circle: Line 23:1: **F401** *'wait_for' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit da7b47a9765eb130558f619ef662899bab8e3895:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9633d7097f19be372cd9fcd8ddc7fcb322d11de7:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
PRT seems happy

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f7db8a7aa2f953a6dc1fb7fd18c58fcbdf019ac2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 77db53faf5875faf6c33d67d1d16d45972922f97:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f44233de5e6b47351585fa80c8f3837b01e16c50:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
