### PR TITLE
[1LP][RFR] Add UI tests for Identify buttons in the physical server page

### PR DESCRIPTION
**Pull request by igorrran**
This PR is able to :

* Add new tests to cover all options in the Identify button are working on physical server details page.

Depends On: https://github.com/ManageIQ/integration_tests/pull/6898

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d39282662660a4be4d08afc823549950fc32bc8d:

`cfme/tests/physical_infrastructure/ui/test_physical_server_identify_action.py`:
- :bangbang: Line 10:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 22:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 33:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 427bda64bbbbab0c4f519394de536f5fc5d378e0:

`cfme/physical/physical_server.py`:
- :heavy_exclamation_mark: Line 309:75: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by igorrran** [comment]
The failures in the ci checks are not related to this pull request.

**Comment by rlbabyuk** [comment]
@igorrran please sign your commit

**Pull request merged**
