### PR TITLE
[RFR][NOTEST] Logging refactor for CI scripts

### LINKED ISSUE #4472: Combine stdout and file logging for scripts
Logging the exceptions to utils.logger has so far been a poor practice, because without going to the log there's no indication in stdout or the generated ec2_cleanup.log file that an exception occurred.

~~Remove utils.logger use and print exception information to stdout.~~

A much better approach, originally suggested by @izapolsk in #4956, is to configure `utils.log.logger` to write to stdout as well as the existing logger configuration.

### PR DESCRIPTION
**Pull request by mshriver**
Use logger to print all messages to stdout and to the log.

Within the scope of the `scripts` directory, and especially with those scripts run by CI infrastructure, we want to simultaneously write all info/debug/warning/error/exception messages both to stdout and to the logger provided by `utils.log.logger`.

These scripts can't/won't be tested by PRT for now, so I'm testing all of them locally before committing changes.

Adding basic logging import and console args where appropriate for the scripts that are scoped for this PR. 

Ignore the damn lint tool.

FIXES #4472

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fa0b99bcf91a6988b6ade1cff00a3e385619bbe0:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 45cd030b2a5159bd0d6f86417f3027744a4e9604:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ca2c65190985b7989a4ef083afb0a9c96da4a7f9:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 464:57: **S001** *found %s formatter*
- :grey_exclamation: Line 466:35: **S001** *found %s formatter*
- :grey_exclamation: Line 520:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 164:68: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d0691b4bd40ef6cb1f89ca60eca5835d58f95cf9:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 464:57: **S001** *found %s formatter*
- :grey_exclamation: Line 466:35: **S001** *found %s formatter*
- :grey_exclamation: Line 520:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 164:68: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 427755c0ffb35236a575ee4759c4b1661327e192:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 464:57: **S001** *found %s formatter*
- :grey_exclamation: Line 466:35: **S001** *found %s formatter*
- :grey_exclamation: Line 520:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 164:68: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21fcbe43c687c4f4fb71057c260b052e8153141e:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 464:57: **S001** *found %s formatter*
- :grey_exclamation: Line 466:35: **S001** *found %s formatter*
- :grey_exclamation: Line 520:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 164:68: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ee4ad58cba5f2d3cad407f97f12e6c13b5905353:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 71:68: **S001** *found %s formatter*
- :grey_exclamation: Line 187:22: **S001** *found %s formatter*
- :grey_exclamation: Line 225:68: **S001** *found %s formatter*
- :grey_exclamation: Line 230:30: **S001** *found %s formatter*
- :grey_exclamation: Line 238:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 464:57: **S001** *found %s formatter*
- :grey_exclamation: Line 466:35: **S001** *found %s formatter*
- :grey_exclamation: Line 520:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 164:68: **S001** *found %s formatter*

`scripts/template_upload_vsphere.py`:
- :grey_exclamation: Line 118:35: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cf4bf5b6f23b64fb81d625d4f7f1dc3e98c18da1:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 70:68: **S001** *found %s formatter*
- :grey_exclamation: Line 186:22: **S001** *found %s formatter*
- :grey_exclamation: Line 224:68: **S001** *found %s formatter*
- :grey_exclamation: Line 229:30: **S001** *found %s formatter*
- :grey_exclamation: Line 237:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 463:57: **S001** *found %s formatter*
- :grey_exclamation: Line 465:35: **S001** *found %s formatter*
- :grey_exclamation: Line 519:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 163:68: **S001** *found %s formatter*

`scripts/template_upload_vsphere.py`:
- :grey_exclamation: Line 116:35: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5f10ae45f030188a04009504dce91c8687dbda0e:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 70:68: **S001** *found %s formatter*
- :grey_exclamation: Line 186:22: **S001** *found %s formatter*
- :grey_exclamation: Line 224:68: **S001** *found %s formatter*
- :grey_exclamation: Line 229:30: **S001** *found %s formatter*
- :grey_exclamation: Line 237:79: **S001** *found %s formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 463:57: **S001** *found %s formatter*
- :grey_exclamation: Line 465:35: **S001** *found %s formatter*
- :grey_exclamation: Line 519:68: **S001** *found %s formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 163:68: **S001** *found %s formatter*

`scripts/template_upload_vsphere.py`:
- :grey_exclamation: Line 116:35: **S001** *found %s formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1eba02144b994cbb7aea0a5e17311e4c82a0c33a:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 70:68: **S001** *found %r formatter*
- :grey_exclamation: Line 186:22: **S001** *found %r formatter*
- :grey_exclamation: Line 224:68: **S001** *found %r formatter*
- :grey_exclamation: Line 229:30: **S001** *found %r formatter*
- :grey_exclamation: Line 237:79: **S001** *found %r formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 463:57: **S001** *found %r formatter*
- :grey_exclamation: Line 465:35: **S001** *found %r formatter*
- :grey_exclamation: Line 519:68: **S001** *found %r formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 163:68: **S001** *found %r formatter*

`scripts/template_upload_vsphere.py`:
- :grey_exclamation: Line 116:35: **S001** *found %r formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit efe7c51adf34b456ba5dfce8493b1df77b5cd8ab:

`scripts/template_upload_ec2.py`:
- :grey_exclamation: Line 70:68: **S001** *found %r formatter*
- :grey_exclamation: Line 186:22: **S001** *found %r formatter*
- :grey_exclamation: Line 224:68: **S001** *found %r formatter*
- :grey_exclamation: Line 229:30: **S001** *found %r formatter*
- :grey_exclamation: Line 237:79: **S001** *found %r formatter*

`scripts/template_upload_rhevm.py`:
- :grey_exclamation: Line 463:57: **S001** *found %r formatter*
- :grey_exclamation: Line 465:35: **S001** *found %r formatter*
- :grey_exclamation: Line 519:68: **S001** *found %r formatter*

`scripts/template_upload_rhos.py`:
- :grey_exclamation: Line 163:68: **S001** *found %r formatter*

`scripts/template_upload_vsphere.py`:
- :grey_exclamation: Line 116:35: **S001** *found %r formatter*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
Note: I will merge this at the end of the sprint without review, as it does not impact the framework but does impact the CI infrastructure logging.

**Pull request merged**
