### PR TITLE
Remove SOAP and its tests

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 005477106dbe1bec288e28a2ff01bcfb5cd5e811:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
I pushed a related commit to your branch @mfalesni

**Comment by dajoRH** [comment]
Lint report for commit dbd92f7b4d62676a0695a3242b563a785a92ea75:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 55bf0a1323e8abebde99e410bb825c3fdece65ea:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
