### PR TITLE
marking power tests

### PR DESCRIPTION
**Pull request by lkhomenk**
Purpose or Intent
=================
Marking Power tests

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 833d32252f28fa515bb76576db15c19e83e83099:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 815b5c545e973f98a6eee585dafde2ffcd04ea4c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by lkhomenk** [comment]
@psav I've update. but this PR depends a bit on #3521 as this module contains common and REST tests. same as Provisioning

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit db06ec05a6f0c8e8da8f5ad4958e8c7ce5ea7ff9:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6bbbdf9b7c3ae4fd462f5561d2f942b852a8e50c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
