### PR TITLE
[WIPTEST]Test vm online (draft)

### PR DESCRIPTION
**Pull request by jistefan**
Purpose or Intent
=================
__Adding tests__ for feature Reporting to cover testing of Canned Reports. Previous approach with prov mgmt was flawed (provider data is moving sand) so we decided to use DB data instead. This is first from collection of canned reports tests.

{{pytest: -k 'test_datastores_summary' -s -v}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4a8f426ad0c7acd41e7785de322ff73907f5a3b4:

`cfme/tests/intelligence/reports/test_canned_corresponds.py`:
- :bangbang: Line 98:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 120:5: **E265** *block comment should start with '# '*
- :grey_exclamation: Line 132:21: **T001** *print statement found.*
- :grey_exclamation: Line 135:9: **T001** *print statement found.*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by jistefan** [comment]
@mfalesni Please check test logic

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1a1550ee49339083c5e201864f9f6f5f416c00c5:

`cfme/tests/intelligence/reports/test_canned_corresponds.py`:
- :grey_exclamation: Line 157:9: **T001** *print statement found.*
- :red_circle: Line 167:5: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1f96abba4f1ba3bdf394421e9da03433540214c0:

`cfme/tests/intelligence/reports/test_canned_corresponds.py`:
- :grey_exclamation: Line 160:9: **T001** *print statement found.*

`utils/testgen.py`:
- :red_circle: Line 99:1: **F401** *'utils.providers.get_class_from_type' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request closed without merging**
