### PR TITLE
Update cfme.web_ui.PagedTable, add find_row_by_cell_on_all_pages

### PR DESCRIPTION
**Pull request by mshriver**
Add a new function to PagedTable to find a row by a cell, instead of a single column/value match.

### CODE REVIEW

**Comment by psav** [comment]
What happens if there are two? Will we just find the first?

**Comment by mshriver** [comment]
@psav Correct, this behaves the same as Table.find_row_by_cells() and returns the first match. I can add a docstring explaining that behavior?

Table.find_rows_by_cells() returns all matching rows.

**Comment by dajoRH** [comment]
Lint report for commit 943737b21d0b2e5955323de21ab836f4789c2773:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ebf7d63d3c9e7cd7e661c6e1e3ee2c6c711ea414:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
