### PR TITLE
[WIP] automate: test_tagvis_config_manager_provider

### PR DESCRIPTION
**Pull request by psimovec**
{{ pytest: cfme/tests/cloud_infra_common/test_tag_objects.py -v }}
{{ pytest: cfme/tests/infrastructure/test_config_management.py::test_tagvis_config_manager -v  }}

Aside from automating the test, I have extracted TaggableFromEditTags. I did not need the get_tags method in the end for automating the test, but it doesn't work for 5.11 [for configured_system where it was]. I made it clear that it's not implemented for 5.11 in this PR. (I wasn't able to implement it in a reasonable amount of time)

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 02383d27716dea298f3311c811d3d18f313bc9a4:

`cfme/ansible_tower/explorer.py`:
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.BreadCrumb' imported but unused*
- :red_circle: Line 21:1: **F401** *'cfme.utils.providers.get_crud_by_name' imported but unused*
- :bangbang: Line 213:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 339:96: **W292** *no newline at end of file*

`cfme/tests/cloud_infra_common/test_tag_objects.py`:
- :red_circle: Line 7:1: **F401** *'cfme.infrastructure.config_management.Satellite' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.infrastructure.config_management.get_config_manager_from_config' imported but unused*
- :bangbang: Line 17:1: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 242:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 242:1: **F811** *redefinition of unused 'test_tagvis_cloud_object' from line 151*
- :bangbang: Line 265:101: **E501** *line too long (106 > 100 characters)*

`widgetastic_manageiq/__init__.py`:
- :heavy_exclamation_mark: Line 3591:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit a753b6a410cb598942c275380844da623ff23db0

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit a753b6a410cb598942c275380844da623ff23db0:

`cfme/ansible_tower/explorer.py`:
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.BreadCrumb' imported but unused*
- :red_circle: Line 21:1: **F401** *'cfme.utils.providers.get_crud_by_name' imported but unused*
- :bangbang: Line 213:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 339:96: **W292** *no newline at end of file*

`cfme/tests/cloud_infra_common/test_tag_objects.py`:
- :red_circle: Line 7:1: **F401** *'cfme.infrastructure.config_management.Satellite' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.infrastructure.config_management.get_config_manager_from_config' imported but unused*
- :bangbang: Line 17:1: **E122** *continuation line missing indentation or outdented*
- :red_circle: Line 243:1: **F811** *redefinition of unused 'test_tagvis_cloud_object' from line 151*

`widgetastic_manageiq/__init__.py`:
- :heavy_exclamation_mark: Line 3591:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 6ac2b540fc782a8a33cfde5abf32d70ec17d70d3

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit 6ac2b540fc782a8a33cfde5abf32d70ec17d70d3:

`cfme/ansible_tower/explorer.py`:
- :red_circle: Line 8:1: **F401** *'widgetastic_patternfly.BreadCrumb' imported but unused*
- :red_circle: Line 21:1: **F401** *'cfme.utils.providers.get_crud_by_name' imported but unused*
- :bangbang: Line 213:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 339:96: **W292** *no newline at end of file*

`widgetastic_manageiq/__init__.py`:
- :heavy_exclamation_mark: Line 3591:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit bc91be5c8fa94972865ef583247a8cd5f0763321

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit 109c0e2fd01a37150c14e42b19e22757f45df7ab:

`widgetastic_manageiq/__init__.py`:
- :heavy_exclamation_mark: Line 3591:1: **W293** *blank line contains whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 109c0e2fd01a37150c14e42b19e22757f45df7ab

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit af81b3d3d19c4d75f976b99577029b0cc679e807

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit fb9fd82c417627ce72f052095bdcaa4737826a89

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit fb9fd82c417627ce72f052095bdcaa4737826a89:

`widgetastic_manageiq/__init__.py`:
- :heavy_exclamation_mark: Line 3591:1: **W293** *blank line contains whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 3a61a894d32ebbde4079cf2d46de9fd2c02f7a51

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit d169645132ce5ddf0c402f0691aba6a6d3724789

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 27ec320a414706937a1574e2bb2192cc05fc7f88

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit f917c863cd8a4224db0dc2b5a652ecd84c702552

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit ac187126751be52bfb1a8c32f37cd53b037e4e7b

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 58ffd3347782a6d7556c240ac0124fddd0eaa8a7

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit d9b5468fdf0b300041272355d2ae80f1a1e1cb99

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 5e73df6dc768c9ef7695177b3eaca1cb77446450

The *local* fixture **`tower`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_tag_objects.py**
    - *test_tagvis_config_manager_provider*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by john-dupuy** [comment]
FYI whichever of #9317 and this PR are merged first will cause the other to rebase

**Comment by psimovec** [comment]
> FYI whichever of #9317 and this PR are merged first will cause the other to rebase

Very nice PR @john-dupuy! Changing status of my PR to WIPTEST and I'll rebase after #9317 is merged

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request closed without merging**
