### PR TITLE
[1LP][RFR] Fix PolicyCollection.PRETTY and PoliciesAllView.is_displayed

### PR DESCRIPTION
**Pull request by mshriver**
is_displayed raises exception because PolicyCollection has no `PRETTY` attribute.

Added `PRETTY=None` and updated `is_displayed` because the collection page doesn't have a unique title.

{{ pytest: cfme/tests/control/test_actions.py -k test_action_start_virtual_machine_after_stopping --long-running }}

### CODE REVIEW

**Comment by izapolsk** [comment]
Could not do Waiting for view [NewPolicyView] to display at /cfme_tests_te/cfme/utils/appliance/implementations/ui.py:558 in time

@mshriver ^^

**Comment by mshriver** [comment]
Different view class, but I'll fix that here too @izapolsk

**Comment by mshriver** [comment]
This is part of resolving #7960

**Comment by dajoRH** [comment]
Lint report for commit d27d88ffcd0655a9f81ef1fe5868798b85711114:

`cfme/tests/control/test_actions.py`:
- :bangbang: Line 193:5: **E124** *closing bracket does not match visual indentation*
- :bangbang: Line 576:5: **E125** *continuation line with same indent as next logical line*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
PRT failures look unrelated at this point, think I want to call it on scope for this PR.

**Pull request merged**
