### PR TITLE
[1LP][RFR] Fix fixture call pattern in test_snapshots_rest

### PR DESCRIPTION
**Pull request by mshriver**
This pattern was directly calling the fixture function, which is not allowed by pytest.

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit e0c878d58cae9e0af9822222c123a4522e5fb05a

The *local* fixture **`vm_snapshot`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_snapshots_rest.py**
    - *test_create_snapshot*
    - *test_delete_snapshot_from_detail*
    - *test_delete_snapshot_from_collection*
    - *test_delete_snapshot_race*
    - *test_revert_snapshot*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit e0c878d58cae9e0af9822222c123a4522e5fb05a:

`cfme/tests/cloud_infra_common/test_snapshots_rest.py`:
- :bangbang: Line 84:9: **E123** *closing bracket does not match indentation of opening bracket's line*
- :bangbang: Line 91:9: **E123** *closing bracket does not match indentation of opening bracket's line*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit f2a50eeddbc4fd92b16e32f85f8d3414aa564a01

The *local* fixture **`vm_snapshot`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_snapshots_rest.py**
    - *test_create_snapshot*
    - *test_delete_snapshot_from_detail*
    - *test_delete_snapshot_from_collection*
    - *test_delete_snapshot_race*
    - *test_revert_snapshot*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by john-dupuy** [comment]
Seeing some fixture scope mismatch and 
```
>           vm_snapshot(request, appliance, collection, vm)
E           TypeError: 'tuple' object is not callable

cfme/tests/cloud_infra_common/test_snapshots_rest.py:184: TypeError
TypeError
b"'tuple' object is not callable"```
on PRT

**Comment by mshriver** [comment]
Thanks @john-dupuy, resolved those. Needed a module scope on a provider marker for one test function, and to call the newly named method in the other, instead of trying to call the fixture.

**Comment by dajoRH** [comment]
I detected some fixture changes in commit fcf2911d61c741c6f0fbb6d94d78a9afa73daaba

The *local* fixture **`vm_snapshot`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_snapshots_rest.py**
    - *test_create_snapshot*
    - *test_delete_snapshot_from_detail*
    - *test_delete_snapshot_from_collection*
    - *test_delete_snapshot_race*
    - *test_revert_snapshot*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Pull request merged**
