### PR TITLE
Automate: Adding stub tests

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4803463843275f993eb5d788f5ef021b2b070452:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Happy to merge, but @RonnyPfannschmidt looping you in because we maybe want another marker for "manual" tests that we want to document in the source, but never run

**Comment by RonnyPfannschmidt** [comment]
@psav @mfalesni lets just add a reason to the skip mark and call it done for now

**Comment by dajoRH** [comment]
Lint report for commit bfd9f99785f6f7f18af1e6472de256bf25c0f427:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
I think I will add these tests as a part of the automate explorer conversion, so do not merge this, I will close it once taht gets it.

**Pull request closed without merging**
