### PR TITLE
[RFR] Fixing the buttons adding in 5.9

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: -v cfme/tests/automate/test_buttons.py -k 'test_button_crud or test_button_group_crud'}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 84afc4766df2631858fea42241b30cdde3897371:

`cfme/automate/buttons.py`:
- :red_circle: Line 252:11: **N801** *class names should use CapWords convention*
- :red_circle: Line 265:11: **N801** *class names should use CapWords convention*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mfalesni** [comment]
This will not pass on current upstream because it is older than the 5.9 change to the flash message. Damn it!

**Comment by mfalesni** [comment]
But it runs fine locally on 5.9 ...

**Comment by mfalesni** [comment]
Initiated a retest because we just received a newer upstream which should have the UI the same as the downstream 5.9.

**Pull request merged**
