### PR TITLE
[RFR] Remove Polarion IDs from CMQE Tests

### PR DESCRIPTION
**Pull request by jawatts**
Combining cmqe and cfme polarion projects, the CMP IDs are no longer needed.

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 676fca0443090619bac6e96609a7383d7c962b30:

`cfme/tests/containers/test_labels.py`:
- :red_circle: Line 8:1: **F401** *'manageiq_client.api.APIException' imported but unused*

`cfme/tests/containers/test_properties.py`:
- :bangbang: Line 38:16: **E231** *missing whitespace after ','*
- :bangbang: Line 42:14: **E231** *missing whitespace after ','*
- :bangbang: Line 67:13: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 71:13: **E126** *continuation line over-indented for hanging indent*

`cfme/tests/containers/test_tags.py`:
- :bangbang: Line 12:25: **E231** *missing whitespace after ','*
- :bangbang: Line 12:46: **E231** *missing whitespace after ','*
- :heavy_exclamation_mark: Line 74:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jawatts** [comment]
@jadhaj I agree this is good practice, but all the changes were related to the removing of the polarion ID. Also, reviewers will generally squash commits before the merge unless it can be argued to keep more than one commit.

**Comment by dajoRH** [comment]
Lint report for commit 7171c7c31403ecd6b6a551cdbb8c4dac048132ac:

`cfme/tests/containers/test_labels.py`:
- :bangbang: Line 24:1: **E303** *too many blank lines (4)*

`cfme/tests/containers/test_ssa_set_cve_image_inspector_per_provider.py`:
- :bangbang: Line 148:2: **E999** *SyntaxError: invalid syntax*
- :bangbang: Line 148:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 148:7: **E225** *missing whitespace around operator*
- :bangbang: Line 151:3: **E225** *missing whitespace around operator*
- :bangbang: Line 151:5: **E225** *missing whitespace around operator*
- :bangbang: Line 151:7: **E225** *missing whitespace around operator*
- :bangbang: Line 152:1: **E302** *expected 2 blank lines, found 0*
- :bangbang: Line 153:7: **E225** *missing whitespace around operator*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
