### PR TITLE
[WIP][NOTEST] Sprout+Appliance - Support for containerized appliances

### PR DESCRIPTION
**Pull request by mfalesni**
Requirements for the containerized appliances:
1) Name of the container does not matter as long as it corresponds to the DB record
2) The VM must have the same credentials as on ordinary appliance
3) the VM must have a `cfme-start` command which starts up the cfme container, redirects ports 80, 443 and 5432 and ensures that the VM's `/share` is mounted as `/share` in the container.
4) the VM's cfme-start script must read /etc/cfme_pull_url and use its CFME_URL variable to start the container.

Supersedes #3084

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1be8e96bb0ebd14aabd52c2f9d7e70aa2b60e027:

`sprout/appliances/migrations/0032_template_container.py`:
- :bangbang: Line 18:101: **E501** *line too long (186 > 100 characters)*

`sprout/appliances/migrations/0033_appliancepool_is_container.py`:
- :bangbang: Line 18:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f7f013b1ec5df35830d3a5038e86596b36c1e2fe:

`sprout/appliances/migrations/0032_template_container.py`:
- :bangbang: Line 18:101: **E501** *line too long (186 > 100 characters)*

`sprout/appliances/migrations/0033_appliancepool_is_container.py`:
- :bangbang: Line 18:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 183f22ac963000a51854cc23339de28057c9b77b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
#3084 needs to go in first, then I will clean up this PR and prepare for merge.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0739cb6327ee423c9379c6602f60cde1d52138d3:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 461bdb308bbfe6398c353624b994b33ba05a7c18:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4eea34221815c3dacb6b9a5f2161dc216f846c0e:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef488ef73c39fdb03ec82a02161d2d7c00511699:

`sprout/appliances/migrations/0035_auto_20160922_1635.py`:
- :bangbang: Line 18:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 23:101: **E501** *line too long (126 > 100 characters)*
- :bangbang: Line 28:101: **E501** *line too long (140 > 100 characters)*
- :bangbang: Line 33:101: **E501** *line too long (186 > 100 characters)*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8f3ae67ffebb119f244e64e429caf17561756e70:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 20d063bad2d4140d3005cb3e95c05b181051f394:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
