### PR TITLE
moved redundant SSA from tests

### PR DESCRIPTION
**Pull request by rrasouli**
Purpose or Intent:

The SSA is irrelevant by the added tests, motivation to save test time and overkilling tests

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2b7a93cd246f24fe22273e39ee4428e92bd216cf:

`cfme/tests/openstack/test_host_devices.py`:
- :red_circle: Line 4:1: **F401** *'toolbar' imported but unused*

`cfme/tests/openstack/test_host_hostname.py`:
- :red_circle: Line 2:1: **F401** *'toolbar' imported but unused*

`cfme/tests/openstack/test_host_memory.py`:
- :red_circle: Line 4:1: **F401** *'toolbar' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 94607088cbe8c411a05561e41917d3d4114304b9:

`cfme/tests/openstack/test_host_devices.py`:
- :red_circle: Line 4:1: **F401** *'toolbar' imported but unused*

`cfme/tests/openstack/test_host_hostname.py`:
- :red_circle: Line 2:1: **F401** *'toolbar' imported but unused*

`cfme/tests/openstack/test_host_memory.py`:
- :red_circle: Line 4:1: **F401** *'toolbar' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 547b5b80befedb142baefac7e7b828e2643ecd56:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by rrasouli** [comment]
@dajoRH please merge

**Comment by dajoRH** [comment]
Response to comment #260594957:

It seems like all the basic requirements were met, I have therefore merged your PR.

**Pull request merged**
