### PR TITLE
[1LP][RFR]Adding auto_placement tests

### PR DESCRIPTION
**Pull request by lkhomenk**
__Extending__ test_provision_from_template to cover auto_placement option
{{pytest: -k test_provision_from_template  --use-provider gce_central --use-provider azure --use-provider vsphere6-nested --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ecc8ee428e722c752aa679a396dc43fab508309e:

`cfme/tests/infrastructure/test_provisioning.py`:
- :red_circle: Line 65:9: **F841** *local variable 'host' is assigned to but never used*
- :red_circle: Line 66:9: **F841** *local variable 'datastore' is assigned to but never used*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by lkhomenk** [comment]
i'll replace assertion message - we need to check request status if we cant find we in cfme

**Comment by lkhomenk** [comment]
a bit depends on  #4457 as we need to know why provisioning was failing

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 31398177a896fbd493235b53407d67e21ce5f04d:

`cfme/tests/infrastructure/test_provisioning.py`:
- :red_circle: Line 67:60: **F821** *undefined name 'auto'*
- :red_circle: Line 68:70: **F821** *undefined name 'auto'*
- :red_circle: Line 69:40: **F821** *undefined name 'auto'*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9953f705e7c9b6201463d96a208b13e775eaaeba:

`cfme/provisioning.py`:
- :bangbang: Line 333:5: **E303** *too many blank lines (2)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by lkhomenk** [comment]
it's really hard to get clean test run on this
5.6 - cloud 100% / infra 50% - there's an open BZ for that - 1435814 
5.7 - ec2 fails due to refresh rate was exceeded - we can't fetch images list
5.8 same as 5.7
adding some wait-checks for ec2 will generate another bunch of refresh operations

**Comment by lkhomenk** [comment]
latest test run is a good one

**Pull request merged**
