### PR TITLE
[1LP][RFR] Remove the Middleware Provider.

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9f0a5709ebed91d1ba89642aa397a210b5d9696f:

`cfme/common/provider_views.py`:
- :heavy_exclamation_mark: Line 531:2: **W291** *trailing whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by izapolsk** [comment]
@hhovsepy, please explain what is it for ?

**Comment by quarckster** [comment]
@izapolsk I guess this required because Hawkular will be not included in CFME 5.9

**Comment by hhovsepy** [comment]
@izapolsk @quarckster right, this is because Middleware Manager integration is cancelled as of 5.9 relase.

**Comment by quarckster** [comment]
@hhovsepy  Honestly, I don't like the idea to just comment out everything. I would propose two options:
1. Leave everything as is and just disable tests related to Middleware.
2. Delete completely entire Middleware related code and keep it in your personal branch locally.
When Middleware will be integrated again you can enable the tests or push back your branch.

**Comment by izapolsk** [comment]
I also thought of that. I think we have only choice - remove unnecessary code. We can always restore code later if it becomes necessary.

**Comment by hhovsepy** [comment]
@quarckster  The reason why I did not leave middleware code, is because when it remains, then it should be maintained with the framework changes.
We discussed with @jkrocil that better to disable the code instead of deleting it at all is that there is a chance that hawkular will come within the Openshift Provider, so it will be easier to return it back by FIXME Middleware keyword.

But if it is critical to remove the unused code, I could delete it.

**Comment by jkrocil** [comment]
@hhovsepy Since everyone would prefer to see it removed, ignore my initial suggestion to just comment it out, please, and let's just delete it. It's true that we can always recover it if necessary sometimes in the near future.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request merged**
