### PR TITLE
Nuke 5.4

### PR DESCRIPTION
**Pull request by lehinevych**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2edc715f1955a38e47ac8a0b490ea338719de032:

`cfme/tests/cloud/test_cloud_timelines.py`:
- :red_circle: Line 11:1: **F401** *'current_version' imported but unused*

`cfme/tests/cloud/test_delete_cloud_object.py`:
- :red_circle: Line 8:1: **F401** *'current_version' imported but unused*

`cfme/tests/cloud_infra_common/test_tag_objects.py`:
- :red_circle: Line 10:1: **F401** *'current_version' imported but unused*

`cfme/tests/configure/test_visual_cloud.py`:
- :red_circle: Line 12:1: **F401** *'current_version' imported but unused*

`cfme/tests/control/test_actions.py`:
- :red_circle: Line 33:1: **F401** *'MiqVM' imported but unused*

`cfme/tests/infrastructure/test_vm_power_control.py`:
- :red_circle: Line 13:1: **F401** *'current_version' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a226f83a37fed0f4a8ed48f866182843665becdb:

`cfme/tests/intelligence/reports/test_report_corresponds.py`:
- :red_circle: Line 9:1: **F401** *'since_date_or_version' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b45572839629a00affdcd4ba8a37c9fae49ef096:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bd4fa16afd83c03e8aca3e52ae4aa68b13bc7a57:

`cfme/tests/cloud/test_instance_power_control.py`:
- :red_circle: Line 7:1: **F401** *'version' imported but unused*

`cfme/tests/configure/test_tag_category.py`:
- :red_circle: Line 8:1: **F401** *'version' imported but unused*

`cfme/tests/infrastructure/test_advanced_search_host.py`:
- :red_circle: Line 12:1: **F401** *'current_version' imported but unused*

`cfme/tests/infrastructure/test_providers.py`:
- :red_circle: Line 11:1: **F401** *'version' imported but unused*

`cfme/tests/infrastructure/test_vm_retirement_rest.py`:
- :red_circle: Line 6:1: **F401** *'current_version' imported but unused*

`cfme/tests/intelligence/reports/test_crud.py`:
- :red_circle: Line 13:1: **F401** *'version' imported but unused*

`cfme/tests/services/test_rest_services.py`:
- :red_circle: Line 12:1: **F401** *'version' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5fbfd51f0284165f43269c8279b5567b15ac3a5a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2c1c26d7b0ec1b9920de08e42245fb41ab090991:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0a09782450cc3e3b8eca254a1b636d7e186e17bc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
@jkrocil Didn't we decide we can't nuke 5.4 because of upgrade requirements now?

**Pull request closed without merging**
