### PR TITLE
Optimized middleware tests by replacing method calls from 'UI' version to 'DB' version

### PR DESCRIPTION
**Pull request by hhovsepy**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 10080b4d994e28b7a73ac6daae5d20477101665f:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
This is failing a few tests in PRT, happy to merge if you want to?

**Comment by dajoRH** [comment]
Lint report for commit 36963e63c285356a9e7bee7616b3d6995f9374dd:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
Absolutely

**Comment by RonnyPfannschmidt** [comment]
as it looks we still should merge it as its a improvement

**Comment by hhovsepy** [comment]
adding more changes here to fix failing tests

**Comment by RonnyPfannschmidt** [comment]
i see, then perhaps add a [wip] marker?

**Comment by dajoRH** [comment]
Lint report for commit 8285a6997909fc70e7a5d830761b16c2b23bbc16:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by hhovsepy** [comment]
@RonnyPfannschmidt now it can be merged

**Comment by RonnyPfannschmidt** [comment]
@hhovsepy that's even better, thanks :+1:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by hhovsepy** [comment]
will rebase it once https://github.com/ManageIQ/integration_tests/pull/3819 is merged

**Comment by dajoRH** [comment]
Lint report for commit eac4d52fbbc410d8a6a8f6750e986295bc24fb66:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
