### PR TITLE
Fix for external DB, existing appliance

### PR DESCRIPTION
**Pull request by psav**
This fix allows an existing appliance with an external database to be
used automatically within the framework, is_db_ready and db_online do
not work, BUT they currently do not work with the enable_external_db
method anyway.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fa68dbe7c044c0f3ad93e2173c8d6a8a703ba880:
:godmode: All seems good! :cake: :punch: :cookie: 
*CFME QE Bot*

**Comment by psav** [comment]
@anewmanRH I'd like you to please take a look at validating that this is still good please

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7cfb51f176fc6b0bea7e231fb725ed425a847b9d:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a625f5c6c35c627fa9f998c40f75387bcf1df3f1:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request closed without merging**
