### PR TITLE
[WIP] Added new appliance_console tests

### PR DESCRIPTION
**Pull request by lcouzens**
Added a few new tests to increase automated appliance_console coverage.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3a8795e87870fd504c7fa5225b4d76fa3d72657a:

`cfme/tests/cli/test_appliance_console.py`:
- :red_circle: Line 397:5: **F841** *local variable 'f1' is assigned to but never used*
- :red_circle: Line 398:5: **F841** *local variable 'f2' is assigned to but never used*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by lcouzens** [comment]
Requires pr572 on gitlab to be merged.

**Comment by dajoRH** [comment]
Lint report for commit 5ab7821d8084b45f4f737a9dc792133ee0e659d6:

`cfme/tests/cli/test_appliance_console.py`:
- :red_circle: Line 2:1: **F401** *'re' imported but unused*
- :red_circle: Line 5:1: **F401** *'cfme.utils.blockers.BZ' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by lcouzens** [comment]
Tests added in another PR, closing this as dup

**Pull request closed without merging**
