### PR TITLE
[WIP] Change the tests to wait for the power state  of the a server be changed

### PR DESCRIPTION
**Pull request by CharlleDaniel**
This PR is able to:
* Refactor the physical servers UI tests to wait for the power state be changed.
* Add two new tests cases  to test the `Restart to System Setup` and `Restart Management (BMC)` inside the power button on the physical server page.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8fa3f708bf900e6842006ad4333bebe24cdec96b:

`cfme/tests/physical_infrastructure/ui/test_physical_server_details_buttons.py`:
- :bangbang: Line 23:101: **E501** *line too long (107 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by CharlleDaniel** [comment]
@mshriver Could you review this PR as well? :+1:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
@CharlleDaniel my apologies that this PR was not reviewed in a timely manner.  Are you still interested in rebasing and pushing this PR to completion?  Understood if you are not, but we welcome your contributions anytime!

@miha-plesko If @CharlleDaniel is not interested in this PR, are you able to take ownership of these enhancements?

Thanks guys!

**Comment by miha-plesko** [comment]
@matejart we would need something similar, right?

**Pull request closed without merging**
