### PR TITLE
[1LP][RFR][CAREFUL] bump pytest to 3.4.1

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
experimenting with bumping to the most recent pytest to find detail issues

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
pytest-dev/pylib#180 will fix the issue we see on prt

**Comment by mshriver** [comment]
Adding WIPTEST to remove from filters since it has [NOMERGE] set

**Comment by RonnyPfannschmidt** [comment]
new pylib was released, rerunning

**Comment by RonnyPfannschmidt** [comment]
errors seem unrelated, pushing rfr and triggering a retest

**Pull request merged**
