### PR TITLE
[1LP][RFR] fix unpacking of element_data

### PR DESCRIPTION
**Pull request by mkoura**
UPDATE:
I changed the PR to include just the framework fix to make the change obvious and speed up the review/merge process.

The issue is that the ``element_data`` can be list or tuple, in which case the current code fails.

### CODE REVIEW

**Comment by izapolsk** [comment]
all tests failed. I've restarted PRT tests

**Comment by izapolsk** [comment]
@mkoura , tests failed again. Please either fix them or confirm that those are expected and why.

**Comment by mkoura** [comment]
@izapolsk the PR4281 changed `service_dialog.create()` call and broke many tests, including mine. While I was at fixing my tests, I fixed all the remaining calls in other tests, too.
I wasn't trying to fix other problems in these tests.

**Comment by mkoura** [comment]
This PR fixes ``service_dialog.create()`` calls (`create` no longer accepts `element_data`) and `element_data` unpacking - now it's broken when `element_data` is not single item.
There were other issues caused by https://github.com/ManageIQ/integration_tests/pull/4281 like changes to ``ServiceCatalogs`` instantiation that I'm addressing in https://github.com/ManageIQ/integration_tests/pull/4497
PRT results are not really relevant here, tests are broken for various other reasons and this PR is only solving issues with ``dialog.create()`` calls.

**Pull request merged**
