### PR TITLE
fixed wait_for_no_providers_by_type

### PR DESCRIPTION
**Pull request by nachandr**
Purpose or Intent
=================
Fixing wait_for_no_providers_by_type() in utils/providers.py because test_utilization.py is failing.

{{pytest: -v -k 'test_metrics_collection' --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 5bdc071b33f598c2e23b32994836861051691051:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by psav** [comment]
What is passing that parameter in?
```
#  git grep wait_for_no_providers_by_type
utils/providers.py:def wait_for_no_providers_by_type(prov_class):
utils/providers.py:            wait_for_no_providers_by_type(prov_class)
utils/providers.py:    do_for_provider_types(wait_for_no_providers_by_type)
```

nothing else uses this........

**Comment by dajoRH** [comment]
Lint report for commit 6c4fa1756e71f6a15a4473f3ccc04825a1092013:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by nachandr** [comment]
@psav, I'm trying to fix this error that I'm seeing while running test_utilization.py

provider = <cfme.infrastructure.provider.virtualcenter.VMwareProvider name='vSphere 5.5', key='vsphere55', zone='default'>

    @pytest.yield_fixture
    def handle_provider(provider):
        try:
            providers.clear_providers()
            providers.setup_provider(provider.key)
        except FlashMessageException as e:
            e.skip_and_log("Provider failed to set up")
        else:
            yield
        finally:
>           providers.clear_providers()

cfme/tests/test_utilization.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
utils/providers.py:403: in clear_providers
    do_for_provider_types(wait_for_no_providers_by_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

op = <function wait_for_no_providers_by_type at 0x7f9f651cc050>

    def do_for_provider_types(op):
>       op('cloud', validate=False)
E       TypeError: wait_for_no_providers_by_type() got an unexpected keyword argument 'validate'

utils/providers.py:396: TypeError

**Comment by dajoRH** [comment]
Lint report for commit d1ba4f081e6bcc4476c0dff85ac989b112a6a3b9:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
