### PR TITLE
[1LP][RFR][NOTEST] Pre commit config

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this adds a base config that we will gradually enable/move to capture more

todo:

- [x] add travis job to lint * cache pre-commit
- [x] prepare transition to partial appliation of pre-commit
- [x] rebase off that branch

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b738cd5741813945516b1188a631fd676fcfd365:

`cfme/utils/update.py`:
- :bangbang: Line 12:17: **E127** *continuation line over-indented for visual indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by psav** [comment]
Please exclude everything inside the ```data``` directory

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
after reading context from @mshriver on RC

#7347 should happen before

**Comment by dajoRH** [comment]
Lint report for commit 1e5e83df4089b4a5f4b0f96b13e1931574b0ae68:

`cfme/utils/update.py`:
- :bangbang: Line 12:17: **E127** *continuation line over-indented for visual indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
working on re-basing, due to new changes more fixes/excludes are needed for initial introduction

**Pull request merged**
