### PR TITLE
[WIP] Assigned to juwatts: custom button container tests

### PR DESCRIPTION
**Pull request by digitronik**
Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

Purpose or Intent
=================
- These test need container provider... most of time skipped on PRT as we are testing container related tests in different job. better to assigned container owner.
- As cfme moving from containers :D... those test on on priority as well.

### CODE REVIEW

**Comment by jawatts** [comment]
@digitronik Containers tests are run in the same jenkins jobs as everything else.

**Comment by digitronik** [comment]
@jawatts its difficult for me to when tests skip due to provider. better these tests assigned to you... till we support OSP and  we not not focusing on container testing. I talk with Sudhir about this.

**Comment by jawatts** [comment]
@digitronik OCP is still supported in 5.11, so I am not sure when you say "till we support Openshift". The provider skips are due to https://bugzilla.redhat.com/show_bug.cgi?id=1713504

**Comment by digitronik** [comment]
> @digitronik OCP is still supported in 5.11, so I am not sure when you say "till we support Openshift". The provider skips are due to https://bugzilla.redhat.com/show_bug.cgi?id=1713504

https://bugzilla.redhat.com/show_bug.cgi?id=1668023#c9

Please refer this comment from Loic...

**Comment by digitronik** [comment]
As part of clean up closing this ^^

**Pull request closed without merging**
