### PR TITLE
[1LP][RFR] Add hawkular creds validation to containers

### PR DESCRIPTION
**Pull request by jkrocil**
@pavelzag Let me know if this works for you.

### CODE REVIEW

**Comment by jkrocil** [comment]
We need properly implemented endpoints so that we don't have to do stuff like this. This is a hacky way of doing things and I don't like it.

**Comment by pavelzag** [comment]
@jkrocil Checking, thanks!

**Comment by pavelzag** [comment]
@jkrocil Looks fully functional!

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by pavelzag** [comment]
@mfalesni. Thanks Milan, do you mind merging it? I want to finish working against it next Sunday

**Pull request merged**
