### PR TITLE
[WIP] - Translator testing

### PR DESCRIPTION
**Pull request by psav**
Adding this to the https://github.com/ManageIQ/manageiq/blob/master/app/helpers/application_helper/toolbar/ems_clouds_center.rb file

```ruby     
          'pficon pficon-add-circle-o fa-lg',
          #. QE: new_cloud_provider_toolbar
          t = N_('Add a New #{ui_lookup(:table=>"ems_cloud")}'),
          t,
```     
     
Means we can then access it like this

```    
In [1]: from utils.providers import get_crud
No handlers could be found for logger "psphere.config"

In [2]: aa = get_crud('rhos7-ga')

In [3]: aa.toolbar_add_button()
Out[3]: u'Add a New Cloud Provider'

In [4]: 
```

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1dbbfa20358d94624278477e078edcb5021eb2d7:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav Whoohoo, nice.

**Comment by mfalesni** [comment]
@psav But, .po files are generated out from zanata :disappointed:

**Comment by mzazrivec** [comment]
The workflow with the .po / .pot files is:

1. an automated process collects strings from our application and creates `manageiq.pot`, which
contains all the collected strings (as things are, these are in english)
2. we take `manageiq.pot` and push it to zanata for translation
3. once the translation is complete, we pull the translated catalogs from zanata and put them
into our git (those are the `manageiq.po` files)

So you cannot just add your custom identifiers to `manageiq.po` and hope that they will
stay (they won't stay).

What you can do is add those QE identifiers directly to ManageIQ sources and these annotations
would be extracted during part one of the process (from above) and put into `manageiq.pot`.
Similar to the "TRANSLATORS" comments you can also see in the catalogs.

The problem here though would be that this would not work in 100% of the situations, for example
we're not able to extract these annotations from views (haml files).

**Comment by psav** [comment]
I see :unamused:

**Comment by dajoRH** [comment]
Lint report for commit dd6ca6b8432b6c38a45ecb3979950fdfb94d667d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
This has been updated to attack the problem at the source - with a few comments in there, we can make this work.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
Moved as a "thought" branch to mojo

**Pull request closed without merging**
