### PR TITLE
[NOTEST] This will add new IFrameText widget.

### PR DESCRIPTION
**Pull request by sbulage**

### CODE REVIEW

**Comment by sbulage** [comment]
As this PR 7289 raised closing it.

**Comment by sbulage** [comment]
For ease of review, re-opening it.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
@sbulage I think iframe support (across all widgets, not just a specific TextWidget) is something that needs to be implemented/supported in wt.core, not here in integration_tests.

I'm going to close this PR, as it needs rebased and should likely not be implemented with a narrow scope. You are more than welcome to re-open, and we can address your automation needs!

Thanks

**Pull request closed without merging**
