### PR TITLE
[WIP] Fix problems in the authentication

### PR DESCRIPTION
**Pull request by mfalesni**
This PR does not completely resolve the authentication errors, but it removes all the nonsense errors caused by bad code.

* Fix the navigation of Group to GroupCollection
* Remove all the separate steps for each auth type `#badidea`
* Remove separate views for all auth types and use conditional switchable view
* That done `^`, you can now rely on `changed` value, fixing the `Database` auth revert

@mshriver ^

### CODE REVIEW

**Comment by mshriver** [comment]
I didn't address GroupCollection in #6217, and I'll be going on vacation for the shutdown starting shortly.

So its up to you how to proceed with these changes. #6217 I'm confident in the view and navigation changes that I've made, but they haven't been fully tested, and the test fixtures calling them will need some slight updates.  For now the auth tests are blocked by BZ anyway, so the fixtures aren't really getting any use anyway.

**Comment by mshriver** [comment]
After some discussion with @mfalesni I believe we'll be closing this PR after merging #6217, assuming I pull the GroupCollection fixes from here into there.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Covered by #6217

**Pull request closed without merging**
