### PR TITLE
Navmazing conversion for Access Control

### PR DESCRIPTION
**Pull request by psav**
Purpose or Intent
=================

Navmazing conversion for access control
{{pytest: cfme/tests/configure/test_access_control.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 34863c43ed034768bb6eee19fd75dd61a0309267:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 776461a792709b8132da07b7e2fa323bbb4eb2c6:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ce36dde45c4e39207037b1eaa7e5095aa233aed5:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d34d3fb3e2f010b17afab095496f84d48013fc4d:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 198988e79c618f695d351219297e23a48c8123a7:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
Fire in the hole!

**Pull request merged**
