### PR TITLE
Added support of Middleware Server Group and Middleware Domain.

### PR DESCRIPTION
**Pull request by hhovsepy**
Adjusted Middleware Server code and tests to support Domain mode Servers. Added test cases.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3ea0d27f387f404b0094537386f52cb031eea455:

`cfme/middleware/server.py`:
- :red_circle: Line 177:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ec771d33a8ea3cd8d0b323d6614dbe34ab38e45a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c3c26ea020e1e140abdf73f0792f807a3b6f3b4:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
Rebased and did small fix to pass tests.

**Comment by dajoRH** [comment]
Lint report for commit d5fc8e4de2304ea31c98c3fbddcb5dc07be44ed1:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
