### PR TITLE
[WIPTEST]  Fix test_tower_workflow_item

### PR DESCRIPTION
**Pull request by jaryn**
{{ py.test: cfme/tests/services/test_ansible_workflow_servicecatalogs.py cfme/tests/services/test_config_provider_servicecatalogs.py::test_order_tower_catalog_item -v --use-provider complete }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit d0363b8cd4ee8ce92be88b95706f200366974cc7

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *local* fixture **`nosleep`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**

The *local* fixture **`vm_mock`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

The *local* fixture **`vm_mock2`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 3803fd266b5035de5c1b12583cca6bbfd551ca02

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *local* fixture **`nosleep`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**

The *local* fixture **`vm_mock`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

The *local* fixture **`vm_mock2`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 9bf51ddbe5b46f7d339e6723cdd2d818829ceb97

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *local* fixture **`nosleep`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**

The *local* fixture **`vm_mock`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

The *local* fixture **`vm_mock2`** is used in the following files:
- **cfme/utils/tests/test_connect_ssh.py**
    - *test_connect_ssh*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by jaryn** [comment]
The tests were failing perhaps as an effect of https://bugzilla.redhat.com/show_bug.cgi?id=1824846

They are no longer failing so I think this PR is obsolete.

**Pull request closed without merging**
