### PR TITLE
[1LP][RFR] Physical server tests

### PR DESCRIPTION
**Pull request by skovic**
This PR implements the physical server integration tests.

Depends on view changes made in ManageIQ/integration_tests/pull/5968

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 61a5dceb0393e6ba825b4338ba6d41a37a0e4fd7:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 579:90: **E231** *missing whitespace after ','*
- :bangbang: Line 579:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 12:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 13:1: **F401** *'cfme.physical.physical_server.PhysicalServer' imported but unused*
- :red_circle: Line 14:1: **F401** *'cfme.physical.provider.lenovo.LenovoProvider' imported but unused*
- :red_circle: Line 46:34: **F812** *list comprehension redefines 'physical_server' from line 39*
- :red_circle: Line 75:29: **F821** *undefined name 'host'*
- :heavy_exclamation_mark: Line 93:1: **W391** *blank line at end of file*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 

* 2c0ace705ced8769fb2c331615b5176ddd51feb6
  * Merge commit detected!!! :bangbang:
* 649c9ce618224b1058b1afde2e3022d97a2d8574
  * Merge commit detected!!! :bangbang:
* ab7ff95b59eabc1970033ed3d638f4f516f7d5cb
  * Merge commit detected!!! :bangbang:
* 70b40819ee08bd0503df08f788190b54b8d85f07
  * Merge commit detected!!! :bangbang:
* 05f14c325a12bad7ddf8ad79f9f6b0917599d83f
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dafab4a68c9f99838ad783d1b4b8892fff040425:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 579:90: **E231** *missing whitespace after ','*
- :bangbang: Line 579:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 

* 2c0ace705ced8769fb2c331615b5176ddd51feb6
  * Merge commit detected!!! :bangbang:
* 649c9ce618224b1058b1afde2e3022d97a2d8574
  * Merge commit detected!!! :bangbang:
* ab7ff95b59eabc1970033ed3d638f4f516f7d5cb
  * Merge commit detected!!! :bangbang:
* 70b40819ee08bd0503df08f788190b54b8d85f07
  * Merge commit detected!!! :bangbang:
* 05f14c325a12bad7ddf8ad79f9f6b0917599d83f
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fe9bc27b93a63fd66e0c05646e3dec40fc3253a9:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 579:90: **E231** *missing whitespace after ','*
- :bangbang: Line 579:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 

* 2c0ace705ced8769fb2c331615b5176ddd51feb6
  * Merge commit detected!!! :bangbang:
* 649c9ce618224b1058b1afde2e3022d97a2d8574
  * Merge commit detected!!! :bangbang:
* ab7ff95b59eabc1970033ed3d638f4f516f7d5cb
  * Merge commit detected!!! :bangbang:
* 70b40819ee08bd0503df08f788190b54b8d85f07
  * Merge commit detected!!! :bangbang:
* 05f14c325a12bad7ddf8ad79f9f6b0917599d83f
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 528917bc4a99add755d2418c491e2487d4c87ff2:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 579:90: **E231** *missing whitespace after ','*
- :bangbang: Line 579:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 

* 2c0ace705ced8769fb2c331615b5176ddd51feb6
  * Merge commit detected!!! :bangbang:
* 649c9ce618224b1058b1afde2e3022d97a2d8574
  * Merge commit detected!!! :bangbang:
* ab7ff95b59eabc1970033ed3d638f4f516f7d5cb
  * Merge commit detected!!! :bangbang:
* 70b40819ee08bd0503df08f788190b54b8d85f07
  * Merge commit detected!!! :bangbang:
* 05f14c325a12bad7ddf8ad79f9f6b0917599d83f
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0ee7df92117f999d8449ede3dbffeba9550d85aa:

Lint OK! :cake: :punch: :cookie: .

* 2c0ace705ced8769fb2c331615b5176ddd51feb6
  * Merge commit detected!!! :bangbang:
* 649c9ce618224b1058b1afde2e3022d97a2d8574
  * Merge commit detected!!! :bangbang:
* ab7ff95b59eabc1970033ed3d638f4f516f7d5cb
  * Merge commit detected!!! :bangbang:
* 70b40819ee08bd0503df08f788190b54b8d85f07
  * Merge commit detected!!! :bangbang:
* 05f14c325a12bad7ddf8ad79f9f6b0917599d83f
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by skovic** [comment]
@psav @mshriver When you get a chance, could you take a look at this PR? It has just one test file. Thanks

**Pull request merged**
