### PR TITLE
[WIP][NOTEST]too complex documentation string

### PR DESCRIPTION
**Pull request by jistefan**
Simple change from 'they're' to 'they are' to prevent glitching of syntax highlight.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit bd178927db9e3df641c1d0e9d369c58bb823a9e7:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 147:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bbd8666281d408408c2a9085df00fc40f744f17c:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 151:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3fff8c1099e561471514a858ace422a1c15720b2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
LGTM :+1:

**Comment by jkrocil** [comment]
Can you squash it to a single commit please so I can merge it? @jistefan

**Comment by dajoRH** [comment]
Lint report for commit d7f5f5b98fc6ca99325ceceab935116a4007336e:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 147:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Pull request closed without merging**
