### PR TITLE
[WIP] - SSUI beginnings

### PR DESCRIPTION
**Pull request by sshveta**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 446ae8467a0d1ea440c627dae305a39efbbca566:

`cfme/login.py`:
- :bangbang: Line 139:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/ssui/test_ssui_links.py`:
- :bangbang: Line 34:1: **E303** *too many blank lines (3)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21a7101cd1daf12e1a4fc19436282dee91a8db80:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9ab8ea234e19deef8441f5f914d233ce5931ba06:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
This still requires my branch additions right?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 449743c8a97e764895555b39646807a2f1af85d8:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by sshveta** [comment]
Closing this PR for now.

**Pull request closed without merging**
