### PR TITLE
[1LP][RFR] move rest of fixtures into cfme

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this pr is one of the last preparations for enabling packaging of the framework as python package

it moves the last remaining global python folder into the cfme package

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
travis just pointed to an issue

**Comment by RonnyPfannschmidt** [comment]
waiting for travis now, @psav please take a look on prt - the failures there look unrelated but i'd like a second oppinion

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
just rebased

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request merged**
