### PR TITLE
[1LP][RFR] Update SSHClient.status, evmserverd output processing

### PR DESCRIPTION
**Pull request by mshriver**
index was too high, server list was empty

Tested locally in 5.9.9 and 5.10.2

{{ pytest: --long-running cfme/tests/cli/test_evmserverd.py }}

### CODE REVIEW

**Comment by digitronik** [comment]
5.10 failures may be due sprout pool problem... moving to 1LP.

**Comment by izapolsk** [comment]
@mshriver, PRT against 5.10 failed. gonna fix or merge as is ?

**Comment by mshriver** [comment]
@izapolsk  was testing something else, but yeah want to debug through this as well.

**Comment by mshriver** [comment]
@izapolsk @digitronik Take a second look please, I added some more changes to deal with 5.10 and clean up some things.

**Pull request merged**
