### PR TITLE
[WIP]v2v Refactoring

### PR DESCRIPTION
**Pull request by sshveta**
{{ pytest: --use-provider rhv42 --use-provider vsphere67-nested --provider-limit 2 -vvvv --long-running cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations.py }}

    Refactored v2v code
    Split code of migrations.py between migration_plans.py and infrastructure_mappings.py
    Moving/modifying tests from test_v2v_migrations.py to test_v2v_migrations_new.pyone by one .
    Will rename it to test_v2v_migrations.py once all tests work.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f9da9fe0da45dfafc8003f92b8236d1748c7aa14:

`cfme/fixtures/v2v.py`:
- :bangbang: Line 331:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 392:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 433:101: **E501** *line too long (104 > 100 characters)*

`cfme/v2v/migration_plans.py`:
- :bangbang: Line 412:101: **E501** *line too long (104 > 100 characters)*
- :bangbang: Line 419:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 449:101: **E501** *line too long (124 > 100 characters)*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7ee790ae57ee1f0f36f84a9cc4cc714e0b2dab8d:

`cfme/fixtures/v2v.py`:
- :bangbang: Line 333:22: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 337:17: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 395:22: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 399:17: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 437:22: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 438:17: **E122** *continuation line missing indentation or outdented*

`cfme/v2v/migration_plans.py`:
- :bangbang: Line 1:1: **E902** *TokenError: EOF in multi-line statement*
- :bangbang: Line 415:29: **E124** *closing bracket does not match visual indentation*
- :bangbang: Line 454:7: **E999** *SyntaxError: invalid syntax*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6c30339917f3c1eab7e53ad92e9228f4cea8d96f:

`cfme/fixtures/v2v.py`:
- :bangbang: Line 331:30: **E231** *missing whitespace after ':'*
- :bangbang: Line 436:22: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 437:17: **E122** *continuation line missing indentation or outdented*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d48307436fb9c228c528a05ad6cc7c3d132ebacf:

`cfme/fixtures/v2v.py`:
- :bangbang: Line 438:42: **E124** *closing bracket does not match visual indentation*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 989703c20ab5c83153fb5f730ea580289782a15c:

`cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations_single_vcenter.py`:
- :bangbang: Line 30:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 186:1: **E302** *expected 2 blank lines, found 1*
- :heavy_exclamation_mark: Line 314:61: **W292** *no newline at end of file*

`cfme/v2v/migration_plans.py`:
- :bangbang: Line 427:17: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 431:17: **E123** *closing bracket does not match indentation of opening bracket's line*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7ef58afc44d3b7c2df74d8aa29a14e55b54974c1:

`cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations_single_vcenter.py`:
- :red_circle: Line 11:1: **F401** *'cfme.utils.appliance.implementations.ui.navigator' imported but unused*
- :red_circle: Line 14:1: **F401** *'cfme.utils.wait.wait_for' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit a2c2f6ed09fc3590eaa0a84e1166f19822385f47

<details>
<summary>
<b>Show fixtures</b>
</summary>


The *global* fixture **`v2v_downstream_enable`** is used in the following files:

The *global* fixture **`v2v_providers`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*
- **cfme/tests/v2v/test_csv_import.py**
    - *infra_map*
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_cancel_migrations.py**
    - *test_dual_vm_migration_cancel_migration*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_single_datastore_single_vm_migration*
    - *test_single_network_single_vm_migration*
    - *test_dual_datastore_dual_vm_migration*
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
    - *test_migrations_different_os_templates*
    - *test_single_vm_migration_with_ssh*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_single_vm_migration_power_state_tags_retirement*
    - *test_multi_host_multi_vm_migration*
    - *test_migration_special_char_name*
    - *test_migration_long_name*
    - *test_migration_with_edited_mapping*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_infra_mapping_ui_assertions*
    - *test_v2v_ui_set1*
    - *test_v2v_ui_no_providers*
    - *test_v2v_mapping_with_special_chars*
    - *test_v2v_ui_set2*
    - *test_v2v_ui_migration_plan_sorting*
    - *test_migration_rbac*
    - *test_edit_mapping_fields*
    - *test_conversion_host_tags*
- **cfme/tests/v2v/test_v2v_schedule_migrations.py**
    - *test_single_vm_scheduled_migration*

The *global* fixture **`host_creds`** is used in the following files:
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_cancel_migrations.py**
    - *test_dual_vm_migration_cancel_migration*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_single_datastore_single_vm_migration*
    - *test_single_network_single_vm_migration*
    - *test_dual_datastore_dual_vm_migration*
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
    - *test_migrations_different_os_templates*
    - *test_single_vm_migration_with_ssh*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_multi_host_multi_vm_migration*
    - *test_migration_special_char_name*
    - *test_migration_long_name*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_v2v_ui_migration_plan_sorting*
- **cfme/tests/v2v/test_v2v_schedule_migrations.py**
    - *test_single_vm_scheduled_migration*

The *global* fixture **`conversion_tags`** is used in the following files:
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_migration_special_char_name*
    - *test_migration_long_name*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_v2v_ui_migration_plan_sorting*

The *global* fixture **`form_data_multiple_vm_obj_single_datastore`** is used in the following files:

The *global* fixture **`form_data_single_datastore`** is used in the following files:
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_infra_mapping_ui_assertions*
    - *test_v2v_ui_set1*
    - *test_v2v_mapping_with_special_chars*
    - *test_v2v_ui_set2*

The *global* fixture **`form_data_single_network`** is used in the following files:

The *global* fixture **`edited_form_data`** is used in the following files:
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_migration_with_edited_mapping*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_edit_mapping_fields*

The *global* fixture **`form_data_dual_vm_obj_dual_datastore`** is used in the following files:

The *global* fixture **`form_data_vm_obj_dual_nics`** is used in the following files:
- **cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations.py**
    - *test_dual_nics_migration*

The *global* fixture **`form_data_vm_obj_single_datastore`** is used in the following files:
- **cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations.py**
    - *test_dual_disk_vm_migration*

The *global* fixture **`form_data_vm_obj_single_network`** is used in the following files:

</details>

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit a2c2f6ed09fc3590eaa0a84e1166f19822385f47

<details>
<summary>
<b>Show fixtures</b>
</summary>


The *global* fixture **`v2v_downstream_enable`** is used in the following files:

The *global* fixture **`v2v_providers`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*
- **cfme/tests/v2v/test_csv_import.py**
    - *infra_map*
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_cancel_migrations.py**
    - *test_dual_vm_migration_cancel_migration*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_single_datastore_single_vm_migration*
    - *test_single_network_single_vm_migration*
    - *test_dual_datastore_dual_vm_migration*
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
    - *test_migrations_different_os_templates*
    - *test_single_vm_migration_with_ssh*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_single_vm_migration_power_state_tags_retirement*
    - *test_multi_host_multi_vm_migration*
    - *test_migration_special_char_name*
    - *test_migration_long_name*
    - *test_migration_with_edited_mapping*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_infra_mapping_ui_assertions*
    - *test_v2v_ui_set1*
    - *test_v2v_ui_no_providers*
    - *test_v2v_mapping_with_special_chars*
    - *test_v2v_ui_set2*
    - *test_v2v_ui_migration_plan_sorting*
    - *test_migration_rbac*
    - *test_edit_mapping_fields*
    - *test_conversion_host_tags*
- **cfme/tests/v2v/test_v2v_schedule_migrations.py**
    - *test_single_vm_scheduled_migration*

The *global* fixture **`host_creds`** is used in the following files:
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_cancel_migrations.py**
    - *test_dual_vm_migration_cancel_migration*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_single_datastore_single_vm_migration*
    - *test_single_network_single_vm_migration*
    - *test_dual_datastore_dual_vm_migration*
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
    - *test_migrations_different_os_templates*
    - *test_single_vm_migration_with_ssh*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_multi_host_multi_vm_migration*
    - *test_migration_special_char_name*
    - *test_migration_long_name*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_v2v_ui_migration_plan_sorting*
- **cfme/tests/v2v/test_v2v_schedule_migrations.py**
    - *test_single_vm_scheduled_migration*

The *global* fixture **`conversion_tags`** is used in the following files:
- **cfme/tests/v2v/test_post_migrations.py**
    - *test_migration_policy_tag*
- **cfme/tests/v2v/test_v2v_ansible.py**
    - *test_migration_playbooks*
- **cfme/tests/v2v/test_v2v_migrations.py**
    - *test_dual_nics_migration*
    - *test_dual_disk_vm_migration*
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_migration_special_char_name*
    - *test_migration_long_name*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_v2v_ui_migration_plan_sorting*

The *global* fixture **`form_data_multiple_vm_obj_single_datastore`** is used in the following files:

The *global* fixture **`form_data_single_datastore`** is used in the following files:
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_infra_mapping_ui_assertions*
    - *test_v2v_ui_set1*
    - *test_v2v_mapping_with_special_chars*
    - *test_v2v_ui_set2*

The *global* fixture **`form_data_single_network`** is used in the following files:

The *global* fixture **`edited_form_data`** is used in the following files:
- **cfme/tests/v2v/test_v2v_migrations_single_vcenter.py**
    - *test_migration_with_edited_mapping*
- **cfme/tests/v2v/test_v2v_migrations_ui.py**
    - *test_edit_mapping_fields*

The *global* fixture **`form_data_dual_vm_obj_dual_datastore`** is used in the following files:

The *global* fixture **`form_data_vm_obj_dual_nics`** is used in the following files:
- **cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations.py**
    - *test_dual_nics_migration*

The *global* fixture **`form_data_vm_obj_single_datastore`** is used in the following files:
- **cfme/tests/v2v/vmware_to_rhv/test_v2v_migrations.py**
    - *test_dual_disk_vm_migration*

The *global* fixture **`form_data_vm_obj_single_network`** is used in the following files:

</details>

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by mshriver** [comment]
@sshveta is this still an active branch? If not, can we close this? is it replaced by any other PRs?

**Comment by sshveta** [comment]
> @sshveta is this still an active branch? If not, can we close this? is it replaced by any other PRs?

Yes Mike . This was replaced by smaller PR's and merged . Closing this one

**Pull request closed without merging**
