### PR TITLE
[WIP] Add remaining manual tests for Compare Host/Node view to test_infra_manual.py x

### PR DESCRIPTION
**Pull request by prichard77**
## Purpose or Intent
- __Adding manual tests__ for FA infra_hosts to cover remaining cases for the hosts comparison view.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b35e271dda5395bda346da729c78585e4e196124:

`cfme/tests/infrastructure/test_infra_manual.py`:
- :bangbang: Line 324:1: **E302** *expected 2 blank lines, found 1*
- :heavy_exclamation_mark: Line 381:1: **W293** *blank line contains whitespace*
- :grey_exclamation: Line 414:13: **P667** *Invalid value "icon 1. Hosts view is displayed with hosts filtered via the Default filter (denoted by "(Default)" next to the filter name in the dropdown). 2. The selected hosts should be displayed with a blue border and checked checkbox. 3. The "Compare Host / Node" view should be displayed (in expanded view by default). - icons are displayed for all and only selected hosts with hostname displayed - one of the quadicons has the host denoted as "(base)" in the hostname - host properties row is displayed (default) - "% Matched" text or graphs are displayed - remove icons exist for all non-base hosts. 4. All hosts are still displayed but now in compressed mode: - column headings(hosts) are displayed vertically - a smaller, simpler, icon is displayed (represents 3rd quadrant) for the hosts. - on parent rows, "% Matched" is displayed as "%". - on child(leaf) rows, color coded values are replaced with checkmarks for matching, and x's for non-matching values" of the "expectedResults" field*
- :grey_exclamation: Line 451:13: **P667** *Invalid value "icon 1. Hosts view is displayed. 2. The selected hosts should be displayed with a blue border and checked checkbox. 3. The "Compare Host / Node" view should be displayed. 4. A compare report should be downloaded (Chrome will show it in left bottom corner of window. - report is in text format. - report has date appended to name. - data in the report matches the GUI. 5. A compare report should be downloaded (Chrome will show it in left bottom corner of window. - report is in CSV format. - report has date appended to name. - data in the report matches the GUI. 6. A print page is displayed containing the compare report." of the "expectedResults" field*
- :bangbang: Line 473:101: **E501** *line too long (110 > 100 characters)*
- :bangbang: Line 483:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 502:101: **E501** *line too long (102 > 100 characters)*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e77d83a29e78d5b638e1bfcf8c53c3d334f38850:

`cfme/tests/infrastructure/test_infra_manual.py`:
- :grey_exclamation: Line 382:9: **P667** *Invalid value "icon 1. Hosts view is displayed. 2. The selected hosts should be displayed with a blue border and checked checkbox. 3. The "Compare Host / Node" view should be displayed (in expanded view by default). - icons are displayed for all and only selected hosts with hostname displayed - one of the quadicons has the host denoted as "(base)" in the hostname - host properties row is displayed (default) - "% Matched" text or graphs are displayed - remove icons exist for all non-base hosts. 4. Network Adapter row will be displayed in the Compare Host/Node panel. 5. Individual child rows will be displayed with "% Matched" in base host and graphs displayed for the rest of the hosts. 6. The "% Matched" and graphs displayed on child rows will be replaced with "+" or "-" depending if the item exists in the non-base hosts." of the "expectedResults" field*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by prichard77** [comment]
I created another pull request for this content. Closing this one.

**Pull request closed without merging**
