### PR TITLE
[WIP] Log monitor

### PR DESCRIPTION
**Pull request by jaryn**
- {{pytest: cfme/tests/cli/test_appliance_console_db_restore.py -k "test_appliance_console_restore_pg_basebackup_replicated  or test_appliance_console_restore_db_replicated or test_appliance_console_restore_db_ha" -v}}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 83d74e44ac8dc02bf5d2d48c17df5b3184fedec0

<details>
<summary>
<b>Show fixtures</b>
</summary>


The *global* fixture **`check_evm_log_no_errors`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *get_ha_appliances_with_providers*

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *global* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_appliance_with_ansible`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_ha_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`prepare_proxy_specific`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_override*

The *local* fixture **`prepare_proxy_default`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_valid*

</details>

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 784e97b4202581bd4a257c04c9a4cbf7b9869e3a

<details>
<summary>
<b>Show fixtures</b>
</summary>


The *global* fixture **`check_evm_log_no_errors`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *get_ha_appliances_with_providers*

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *global* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_appliance_with_ansible`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_ha_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`prepare_proxy_specific`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_override*

The *local* fixture **`prepare_proxy_default`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_valid*

</details>

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 4ea2b38b7963330a9fa3cab440ef970b62f91766

<details>
<summary>
<b>Show fixtures</b>
</summary>


The *global* fixture **`check_evm_log_no_errors`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *get_ha_appliances_with_providers*

The *global* fixture **`utility_vm_nfs_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_samba_ip`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *global* fixture **`utility_vm_proxy_data`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *prepare_proxy_specific*
    - *prepare_proxy_default*

The *global* fixture **`utility_vm_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

The *global* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_appliance_with_ansible`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_ha_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`prepare_proxy_specific`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_override*

The *local* fixture **`prepare_proxy_default`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *test_proxy_valid*

</details>

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit f8e015d01386ac674380c98b9c84ba5f51752d2d

The *global* fixture **`check_evm_log_no_errors`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *get_ha_appliances_with_providers*

The *local* fixture **`get_appliance_with_ansible`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

The *local* fixture **`get_ha_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by jaryn** [comment]
https://github.com/ManageIQ/integration_tests/pull/9790

**Pull request closed without merging**
