### PR TITLE
[WIP] Changed ownership and geneaology assignee

### PR DESCRIPTION
**Pull request by spusateri**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 993528db2a8a4e946ef48e8d585598cc1f8441eb:

`cfme/tests/cloud_infra_common/test_genealogy.py`:
- :bangbang: Line 118:5: **E265** *block comment should start with '# '*
- :bangbang: Line 121:5: **E303** *too many blank lines (2)*
- :bangbang: Line 121:5: **E265** *block comment should start with '# '*
- :heavy_exclamation_mark: Line 164:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 922b1188bf5d3a81c0fb13c18b960c8f742e9642:

`cfme/tests/cloud_infra_common/test_genealogy.py`:
- :bangbang: Line 25:2: **E999** *SyntaxError: invalid syntax*
- :bangbang: Line 25:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 25:7: **E225** *missing whitespace around operator*
- :bangbang: Line 26:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 26:7: **E225** *missing whitespace around operator*
- :bangbang: Line 27:3: **E225** *missing whitespace around operator*
- :bangbang: Line 27:5: **E225** *missing whitespace around operator*
- :bangbang: Line 27:7: **E225** *missing whitespace around operator*
- :bangbang: Line 29:3: **E225** *missing whitespace around operator*
- :bangbang: Line 29:5: **E225** *missing whitespace around operator*
- :bangbang: Line 29:7: **E225** *missing whitespace around operator*
- :bangbang: Line 31:7: **E225** *missing whitespace around operator*
- :bangbang: Line 39:7: **E225** *missing whitespace around operator*
- :bangbang: Line 93:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 93:7: **E225** *missing whitespace around operator*
- :bangbang: Line 95:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 95:1: **E112** *expected an indented block*
- :bangbang: Line 95:3: **E225** *missing whitespace around operator*
- :bangbang: Line 95:5: **E225** *missing whitespace around operator*
- :bangbang: Line 95:7: **E225** *missing whitespace around operator*
- :bangbang: Line 97:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 97:7: **E225** *missing whitespace around operator*
- :bangbang: Line 99:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 99:1: **E112** *expected an indented block*
- :bangbang: Line 99:7: **E225** *missing whitespace around operator*
- :bangbang: Line 100:3: **E225** *missing whitespace around operator*
- :bangbang: Line 100:5: **E225** *missing whitespace around operator*
- :bangbang: Line 100:7: **E225** *missing whitespace around operator*
- :bangbang: Line 102:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 102:1: **E112** *expected an indented block*
- :bangbang: Line 102:7: **E225** *missing whitespace around operator*
- :bangbang: Line 127:5: **E303** *too many blank lines (2)*
- :bangbang: Line 132:5: **E303** *too many blank lines (3)*
- :bangbang: Line 143:5: **E265** *block comment should start with '# '*
- :bangbang: Line 146:5: **E303** *too many blank lines (2)*
- :bangbang: Line 146:5: **E265** *block comment should start with '# '*
- :heavy_exclamation_mark: Line 188:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
Please re-open from a new branch, bad rebase pulled 500+ commits into this.

**Pull request closed without merging**
