### PR TITLE
Fix default views

### PR DESCRIPTION
**Pull request by akarol**
{{pytest: -v -k 'test_compressed_view'}}
# Purpose or Intent

Fixing views as it was failing

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6dd43d43b2b914d212410fa232137be790f6c779:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e7f79809129fb9ef18f55edab7075200516ec46d:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by akarol** [comment]
@jkrocil will look into it.

**Comment by dajoRH** [comment]
Lint report for commit 68049ac9c16871b89464ec1ad687c06192fd2c6f:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mshriver** [comment]
Commit needs signing. @akarol Please comment on upstream PRT failure and I'll review. Thanks!

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by akarol** [comment]
Closing this as many fixes related to view has been fixed and merged in PR#3782

**Pull request closed without merging**
