### PR TITLE
Menu.py add overview

### PR DESCRIPTION
**Pull request by pavelzag**
Fix to add Overview menu in the menu.py

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit efce461df11e60a1b0b22446a29c3704f53302fc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Will need this squashed, but otherwise this is fine

**Comment by dajoRH** [comment]
Lint report for commit d4a4c5feeab9d619c6628bea84b41bc6e70308b4:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 75ff4d9791c7a0538be27cdf87f27859f88b01bf:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
