### PR TITLE
[WIP] Adding new vm reconfigure tests to add/remove hot disk

### PR DESCRIPTION
**Pull request by niyazRedhat**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 044a23f0c9eb28477a0f7e3af391f5a471fe1447:

`cfme/tests/infrastructure/test_vm_reconfigure.py`:
- :heavy_exclamation_mark: Line 166:1: **W293** *blank line contains whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef13f611f5729785f6e9a72124b33c92c4100551:

`cfme/tests/infrastructure/test_vm_reconfigure.py`:
- :heavy_exclamation_mark: Line 166:1: **W293** *blank line contains whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by niyazRedhat** [comment]
Closing this one. Due to one bz. I will raise new pr later once bz will get fixed.

**Pull request closed without merging**
