### PR TITLE
[1LP][RFR] apply the python modernize import fixer for six

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2d4622fcd73c0299f15e880b899555fec59824b5:

`cfme/utils/dockerbot/dockerbot.py`:
- :bangbang: Line 462:101: **E501** *line too long (112 > 100 characters)*

`cfme/utils/tests/test_ipappliance.py`:
- :red_circle: Line 2:1: **F401** *'six.moves.urllib.parse.urlparse' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by psav** [comment]
This is good, we are waiting until start of next sprint to merge

**Comment by izapolsk** [comment]
@RonnyPfannschmidt, please rebase

**Comment by psav** [comment]
@mfalesni please approve the changes to sprout

**Pull request merged**
