### PR TITLE
[WIP] [NOTEST] Sprout - Add HWProfile class

### PR DESCRIPTION
**Pull request by mfalesni**
Will enable us to assign different flavours / hw configurations for the providers.

Requires https://github.com/RedHatQE/mgmtsystem/pull/38 to go in first.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 077f2fd13b9ab299dadd92c26ca7fffcfd01b3fa:

`sprout/appliances/migrations/0032_hwprofile.py`:
- :bangbang: Line 19:101: **E501** *line too long (114 > 100 characters)*
- :bangbang: Line 21:101: **E501** *line too long (181 > 100 characters)*
- :bangbang: Line 24:101: **E501** *line too long (107 > 100 characters)*
- :bangbang: Line 25:101: **E501** *line too long (153 > 100 characters)*

`sprout/appliances/models.py`:
- :bangbang: Line 393:25: **E126** *continuation line over-indented for hanging indent*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a84302d8e8df8e921b780519d29331efbf88380f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d1881e376f01485b8f5a2c0c571f7777a6127c53:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
Solved in a different way ...

**Pull request closed without merging**
