### PR TITLE
[1LP][RFR] Modified Middleware timelines page to support new widgetastic.

### PR DESCRIPTION
**Pull request by hhovsepy**
Enabled test methods.

{{pytest: cfme/tests/middleware/test_provider_timelines.py -v --use-provider hawkular}}

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
looks good, please add a meta-data comment, so PRT can test on the files where you changed/re-enabled the tests

**Comment by hhovsepy** [comment]
Need to finish work on https://github.com/ManageIQ/wrapanapi/pull/124 to be able to run tests.

**Comment by hhovsepy** [comment]
random errors in PRT

**Comment by hhovsepy** [comment]
@RonnyPfannschmidt can this PR be reviewed?
only failure is random timeout which pass on upstream.

**Comment by hhovsepy** [comment]
Failed test caused by cot constantly reproducible BZ https://bugzilla.redhat.com/show_bug.cgi?id=1420431

**Pull request merged**
