### PR TITLE
[1LP][RFR] fix for test_manage_nsg_group test and some refactoring

### PR DESCRIPTION
**Pull request by izapolsk**
Purpose or Intent
=================
1. fixed test_manage_nsg_group test which started failing lately
2. got rid of terrible regexps 

{{pytest: --use-provider=azure cfme/tests/cloud/test_cloud_events.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit da3caa7ed0c09be2bb715a33ea06d204d4463166:

`cfme/tests/cloud/test_cloud_events.py`:
- :heavy_exclamation_mark: Line 45:1: **W293** *blank line contains whitespace*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
Can you explain the test_vm_capture[azure] failure in CFME 56z on PRT?

**Comment by izapolsk** [comment]
let me check. I haven't paid attention on it since sprout didn't give any 5.6 appliances to PRT tests.

**Comment by izapolsk** [comment]
tests finished successfully locally against 5.6. I'm  restarting PR tests.

**Comment by izapolsk** [comment]
tests can't get 5.6 appliance in PRT

**Pull request merged**
