### PR TITLE
[WIP] Fix test_appliance_console_restore_db_.* tests

### PR DESCRIPTION
**Pull request by jaryn**
Purpose or Intent
=================

__Fixing__  test_appliance_console_restore_db_.* tests which failed because of
1) timeout was too short when issuing the ap command
2) the VM providing the NFS share didn't exist.

Fixed by starting using paramiko_expect and creating the required VM on demand.

{{ pytest: -v cfme/tests/cli/test_appliance_console_db_restore.py::test_appliance_console_restore_db_samba cfme/tests/cli/test_appliance_console_db_restore.py::test_appliance_console_restore_db_nfs }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 8282a972a095178a73aa2c4867c9bbbbdeab75d5:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 18:1: **F401** *'cfme.utils.providers.get_mgmt' imported but unused*
- :bangbang: Line 269:5: **E303** *too many blank lines (2)*
- :bangbang: Line 522:9: **E123** *closing bracket does not match indentation of opening bracket's line*
- :bangbang: Line 535:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 540:11: **E222** *multiple spaces after operator*
- :heavy_exclamation_mark: Line 568:1: **W293** *blank line contains whitespace*
- :bangbang: Line 571:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 575:101: **E501** *line too long (104 > 100 characters)*
- :bangbang: Line 601:101: **E501** *line too long (102 > 100 characters)*
- :heavy_exclamation_mark: Line 626:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 413ee2e910bf4c190586cf773638279efab06449:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 20:1: **F811** *redefinition of unused 'SSHClient' from line 15*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by digitronik** [comment]
@jaryn please have a look on CI and PRT. For now, moving to WIPTEST

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e2d98ba8730aee33b86161e4dda8be69d9ab63c8:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f4a521385d7b155029639591b78dbe6a81be89fd:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 04da491abc7ba088d263c872498cae4fdabe4e78:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit aa0c44c28f7cd8382c6d4877d6a942a319456b24:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3f168994e72123387eb49a7f16283aad97f50592:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 3f168994e72123387eb49a7f16283aad97f50592

The *local* fixture **`get_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *test_appliance_console_restore_db_local*
    - *test_appliance_console_restore_db_nfs*
    - *test_appliance_console_restore_db_samba*

The *local* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *nfs_samba_share_vm*

The *local* fixture **`nfs_samba_share_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *setup_nfs_samba_backup*
    - *test_appliance_console_restore_db_nfs*

The *local* fixture **`proxy_machine`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *proxy_ssh*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*

The *local* fixture **`proxy_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 3f168994e72123387eb49a7f16283aad97f50592

The *local* fixture **`get_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *test_appliance_console_restore_db_local*
    - *test_appliance_console_restore_db_nfs*
    - *test_appliance_console_restore_db_samba*

The *local* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *nfs_samba_share_vm*

The *local* fixture **`nfs_samba_share_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *setup_nfs_samba_backup*
    - *test_appliance_console_restore_db_nfs*

The *local* fixture **`proxy_machine`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *proxy_ssh*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*

The *local* fixture **`proxy_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit 1ba1bc9b44a2f1f4ba7e3a0816d6aba334f52f43:

`cfme/tests/cli/test_appliance_console_db_restore.py`:
- :red_circle: Line 500:25: **F821** *undefined name 'random_vm_name'*
- :red_circle: Line 504:10: **F821** *undefined name 'deploy_template'*
- :bangbang: Line 510:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 510:1: **F811** *redefinition of unused 'utility_vm' from line 496*
- :bangbang: Line 512:12: **E201** *whitespace after '{'*
- :bangbang: Line 513:29: **E201** *whitespace after '{'*
- :bangbang: Line 514:52: **E202** *whitespace before '}'*
- :red_circle: Line 519:5: **F841** *local variable 'connect_kwargs' is assigned to but never used*
- :bangbang: Line 530:1: **E265** *block comment should start with '# '*
- :bangbang: Line 534:101: **E501** *line too long (102 > 100 characters)*
- :bangbang: Line 545:16: **E702** *multiple statements on one line (semicolon)*
- :red_circle: Line 557:19: **F821** *undefined name 'SSHClientInteraction'*
- :bangbang: Line 565:16: **E702** *multiple statements on one line (semicolon)*
- :heavy_exclamation_mark: Line 568:76: **W605** *invalid escape sequence '\?'*
- :heavy_exclamation_mark: Line 568:79: **W605** *invalid escape sequence '\('*
- :heavy_exclamation_mark: Line 568:84: **W605** *invalid escape sequence '\)'*
- :heavy_exclamation_mark: Line 570:47: **W605** *invalid escape sequence '\.'*
- :heavy_exclamation_mark: Line 570:49: **W605** *invalid escape sequence '\.'*
- :heavy_exclamation_mark: Line 570:51: **W605** *invalid escape sequence '\.'*
- :bangbang: Line 579:1: **E265** *block comment should start with '# '*
- :red_circle: Line 606:19: **F821** *undefined name 'SSHClientInteraction'*
- :heavy_exclamation_mark: Line 621:76: **W605** *invalid escape sequence '\?'*
- :heavy_exclamation_mark: Line 621:79: **W605** *invalid escape sequence '\('*
- :heavy_exclamation_mark: Line 621:84: **W605** *invalid escape sequence '\)'*
- :bangbang: Line 623:16: **E702** *multiple statements on one line (semicolon)*
- :heavy_exclamation_mark: Line 624:47: **W605** *invalid escape sequence '\.'*
- :heavy_exclamation_mark: Line 624:49: **W605** *invalid escape sequence '\.'*
- :heavy_exclamation_mark: Line 624:51: **W605** *invalid escape sequence '\.'*

`cfme/tests/configure/test_proxy.py`:
- :red_circle: Line 49:9: **F841** *local variable 'repofile' is assigned to but never used*

`scripts/prepare_utility_vm.py`:
- :red_circle: Line 2:1: **F401** *'cfme.utils.conf.credentials' imported but unused*
- :bangbang: Line 52:9: **E265** *block comment should start with '# '*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 1ba1bc9b44a2f1f4ba7e3a0816d6aba334f52f43

The *local* fixture **`get_appliances_with_providers`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *test_appliance_console_restore_db_local*
    - *test_appliance_console_restore_db_nfs*
    - *test_appliance_console_restore_db_samba*

The *local* fixture **`utility_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *nfs_samba_share_vm*

The *local* fixture **`nfs_samba_share_vm`** is used in the following files:
- **cfme/tests/cli/test_appliance_console_db_restore.py**
    - *setup_nfs_samba_backup*
    - *test_appliance_console_restore_db_nfs*

The *local* fixture **`proxy_machine`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *proxy_ssh*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*

The *local* fixture **`proxy_ssh`** is used in the following files:
- **cfme/tests/configure/test_proxy.py**
    - *validate_proxy_logs*
    - *prepare_proxy_specific*
    - *prepare_proxy_default*
    - *test_proxy_valid*
    - *test_proxy_override*

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Pull request closed without merging**
