### PR TITLE
added navigatable property to Host

### PR DESCRIPTION
**Pull request by izapolsk**
Since psav implemented Navigatable base class which helped to get rid of get_appliance call in every class, all get_appliance calls should be replaced by it.
So,  here I made such a replacement for Host class.

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ad4e27b92f91c4ef977699a1b905c09fe76f6f01:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0f9776ab9b088cbd636575904b886a1c7eb8ba56:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by izapolsk** [comment]
Unfortunately, psav already made such a change :(

**Pull request closed without merging**
