### PR TITLE
[1LP][RFR] Automate test for Ansible template job with survey

### PR DESCRIPTION
**Pull request by nachandr**
Added a test for Ansible template jobs with surveys

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c048ad4ee95b6806d573b31ded93b34f2a63216d:

`cfme/tests/services/test_config_provider_servicecatalogs.py`:
- :bangbang: Line 82:101: **E501** *line too long (123 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
@nachandr the retire tests are failing to expand the node in the accordion tree, and the tree isn't expanded.  Either the test needs updated in retirement, or the widget needs updated.

**Comment by nachandr** [comment]
Thanks @mshriver , The retirement tests are failing  because of this 

https://github.com/ManageIQ/manageiq-ui-classic/pull/5335  Hide services from the Services tree as its redundant and slow

**Comment by nachandr** [comment]
I have reported this GH issue to update navigation/methods and added a GH blocker for  the retirement tests https://github.com/ManageIQ/integration_tests/issues/8610

**Pull request merged**
