### PR TITLE
Fixed upstream configuration patch for autofocus

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit e6b736e448fa5b46e2dc423d16ac7d64eb077e79:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0ecdeb2a89a75b1bd2dd6e09b5f382bc16696418:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Tested this manually and it seemed to work now @amavinag Can you trigger a retest on jenkins?

**Comment by amavinag** [comment]
@psav js patch looks good on jenkins run.

**Comment by jkrocil** [comment]
LGTM

**Pull request merged**
