### PR TITLE
[1LP][RFR] REST API tests for parent service

### PR DESCRIPTION
**Pull request by mkoura**
Adding new test for testing parent service functionality using REST API.

**PRT:**
http://10.16.4.32/trackerbot/pr/run/10317 is good looking, also tested locally.

{{pytest: cfme/tests/services/test_rest_services.py -v --long-running -k TestServiceRESTAPI}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
The successful test runs you link to were tests run against `rhevm36`. The current failures are tests run against `vsphere55`. Have you tried running it locally with `--use-provider vspere55` if you can reproduce the failures?

**Comment by mkoura** [comment]
@jkrocil tests on `vsphere55` PASSED with expected skips:

```
$ cfme_pytest --use-provider vsphere55 -k TestServiceRESTAPI cfme/tests/services/test_rest_services.py
Loading templates from trackerbot...                                                                                                                                         
  Loaded 968 templates successfully!                                                                                                                                         
no test annotation found in None
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.13, pytest-2.9.2, py-1.4.32, pluggy-0.3.1 -- /home/martink/.local/python_venvs/cfme_tests/bin/python2
cachedir: .cache
rootdir: /home/martink/tmp/overlays/cfme_tests, inifile: 
plugins: wait-for-1.0.8, polarion-cfme-0.0.4
collected 34 items 

Appliance's streams: [downstream, 5.7]

cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_edit_service 
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_edit_service PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_edit_multiple_services PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_delete_service PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_delete_services PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_retire_service_now PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_retire_service_future PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_set_service_owner PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_set_services_owner PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_power_service[from_detail] PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_power_service[from_collection] PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_create_service_from_parent SKIPPED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_delete_parent_service PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_add_service_parent PASSED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_power_parent_service SKIPPED
cfme/tests/services/test_rest_services.py::TestServiceRESTAPI::test_retire_parent_service_now PASSED

======================================================== 19 tests deselected by "-kTestServiceRESTAPI -m 'not perf'" ========================================================
========================================================== 13 passed, 2 skipped, 19 deselected in 10538.92 seconds ==========================================================
collecting artifacts
```

**Comment by mkoura** [comment]
@izapolsk @mshriver please review

**Comment by izapolsk** [comment]
everything looks fine, :+1:

**Pull request merged**
