### PR TITLE
Yaml cleanup

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 05da2f4dab890ea954150518c3f9aad07b3dd94a:

`cfme/tests/configure/test_visual_cloud.py`:
- :red_circle: Line 10:1: **F401** *'cfme_data' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9450082ce6087d699428dfe9f4ade45fd2f84f7d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav just curious, any of these data in the sample yaml?

**Comment by psav** [comment]
I didn't look to be honest yet

**Comment by psav** [comment]
Yes there are - it would make it much smaller

**Comment by dajoRH** [comment]
Lint report for commit 89e498a9808656b62e77449d0d945551c2a055c8:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by akarol** [comment]
@psav looks ok to me! Many of the test cases are failing as there are many bugs around this area.I will mark the testcases with blockers.

**Comment by psav** [comment]
@mfalesni @jkrocil can I get an ack on this?

**Comment by jkrocil** [comment]
LGTM. Just seems curious that none of this was ever version-picked.

**Comment by psav** [comment]
It should be - future work

**Pull request merged**
