### PR TITLE
Navmazing fix for the containers_default_project_replicators test

### PR DESCRIPTION
**Pull request by pavelzag**
{{pytest: cfme/tests/containers/test_containers_default_project_replicators.py -v --use-provider container }}
Fixing test_containers_default_project_replicators to work with Navmazing

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2e654ec74b829ed8959b904493322aec920a5dcc:

`cfme/tests/containers/test_containers_default_project_replicators.py`:
- :red_circle: Line 2:1: **F401** *'sel' imported but unused*
- :red_circle: Line 4:1: **F401** *'Container' imported but unused*
- :bangbang: Line 8:47: **E271** *multiple spaces after keyword*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 64c3c1870f57b95e57e748ed487b2ca6596b62e1:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3765c87839deed7042d2cded88af88fb2b5bb934:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ae09ba99da425e9f739af61f3aa19ba63ce8042c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by pavelzag** [comment]
The tests that fail here are failing because the appliances don't have any Replicators to work with.
The 5.6 appliance did have and the test will probably pass

**Pull request merged**
