### PR TITLE
[WIP][NOTEST] move utils to cfme.utils

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
requires prt rebuild

result of running the refactoring script using

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 02816580ce33f16ac28e86adea442069964195b4:

`cfme/fixtures/base.py`:
- :red_circle: Line 4:1: **F401** *'cfme.utils.appliance.ApplianceException' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by jkrocil** [comment]
Try running `miq shell`.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c76add636771c255020da37968f942e8312f7b0:

`cfme/automate/buttons.py`:
- :red_circle: Line 15:1: **F401** *'cfme.utils.version' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 574c4bae7531a29db46ece169569b618ae5a9607:

`cfme/automate/buttons.py`:
- :red_circle: Line 15:1: **F401** *'cfme.utils.version' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
Both `miq shell` and test collection now locally work. :+1:

**Pull request closed without merging**
