### PR TITLE
Snapshot tree fix

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/infrastructure/test_snapshot.py -v --use-provider nested-rhevm35 --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e130e93e64a0d48c43107ddb8ac1926e9a6b0cda:

`cfme/infrastructure/virtual_machines.py`:
- :red_circle: Line 201:48: **F821** *undefined name 'snapshot_tree'*

`cfme/tests/infrastructure/test_snapshot.py`:
- :bangbang: Line 64:43: **E127** *continuation line over-indented for visual indent*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by mfalesni** [comment]
Looks terrible but I will fix it up

**Comment by dajoRH** [comment]
Lint report for commit d1eed1a12842ecda44a1058c37a8047095e828e0:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 895ef3f3a2f31a3e0c34f6d1bdcb34f3a3c0eb10:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Pull request merged**
