### PR TITLE
extract and simplify the logic for provider endpoints

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 52d96932e52793b343c16abe68836e4fdde10d19:

`utils/appliance.py`:
- :red_circle: Line 9:1: **F401** *'datetime' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ed92d04988ae278bdbb14180147ea90b3198f468:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
I think this is fine, can we squash it?

**Comment by RonnyPfannschmidt** [comment]
should i squash or does a gh squahs merge suffice?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0ce68f30f8829f1fb790b089c8ec6ee886385433:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
