### PR TITLE
[1LP][RFR]Bundle view is_displayed fix

### PR DESCRIPTION
**Pull request by sshveta**
1) Removed BZ
2) Fixed Editbundle view

### CODE REVIEW

**Comment by jawatts** [comment]
@sshveta the failures in the tests are fixed in #8091 correct?

**Comment by sshveta** [comment]
> @sshveta the failures in the tests are fixed in #8091 correct?

Yes @jawatts , to be merged after PR #8091

**Comment by izapolsk** [comment]
@sshveta, changes look good but some PRT tests still fail. Are you going to fix them in this PR ?

**Comment by mshriver** [comment]
PRT failures unrelated to bundle edit view

**Pull request merged**
