### PR TITLE
[WIPTEST] Implement Collections for RBAC User

### PR DESCRIPTION
**Pull request by LandoCalrizzian**
{{pytest: -v -k 'test_validate_chargeback_report or test_user_ownership_crud or test_edit_user_password or test_login or test_tagvis_user or test_user_change_password or test_permissions or test_permission_edit or test_assign_user_to_new_group or test_delete_group_with_assigned_user or test_current_user_login_delete or test_delete_default_user or test_user_remove_tag or test_user_edit_tag or test_user_email_error_validation or test_user_group_error_validation or test_user_password_required_error_validation or test_userid_required_error_validation or test_username_required_error_validation or test_user_duplicate_name or test_user_login'}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e14970b927c6b5abaeb4cd69ee7e6c34dbd36479:

`cfme/base/ui.py`:
- :red_circle: Line 73:31: **F821** *undefined name 'appliance'*

`cfme/tests/configure/test_access_control.py`:
- :red_circle: Line 375:5: **F841** *local variable 'user' is assigned to but never used*
- :red_circle: Line 509:5: **F841** *local variable 'user' is assigned to but never used*

`cfme/utils/appliance/__init__.py`:
- :bangbang: Line 310:101: **E501** *line too long (106 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1c601837751134572071b810850dddf7032c4f21:

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 40:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eef1905ece8af7254261ec699170da3258867742:

`cfme/tests/intelligence/reports/test_validate_chargeback_report.py`:
- :bangbang: Line 3:43: **E999** *SyntaxError: invalid syntax*
- :bangbang: Line 3:60: **E401** *multiple imports on one line*
- :bangbang: Line 84:101: **E501** *line too long (114 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by LandoCalrizzian** [comment]
Closing this PR and combining with #5667

**Pull request closed without merging**
