### PR TITLE
[WIPTEST] Added random choice for provider_type selection.

### PR DESCRIPTION
**Pull request by sbulage**
PRT run:
{{ pytest: cfme/tests/cli/test_appliance_cli.py -vvvv }}

### CODE REVIEW

**Comment by digitronik** [comment]
@sbulage can you please add `description` and your `intention` for this PR. It's affecting all `cli` tests so why `NOTEST` tag?

**Comment by sbulage** [comment]
@digitronik In this PR, I have added 2 provider types, in order to expand availability of appliance from any of the provider.

**Comment by sbulage** [comment]
@digitronik I have added respective test.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1b36cca726a39f2f5183c37fbf30439f06fb7f12:

`cfme/fixtures/cli.py`:
- :heavy_exclamation_mark: Line 118:6: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by sbulage** [comment]
Working as expected. Hence closing it.

**Pull request closed without merging**
