### PR TITLE
[1LP][RFR]Rename WidgetasticTaggable to Taggable

### PR DESCRIPTION
**Pull request by rlbabyuk**
Purpose or Intent
=================
Rename class WidgetasticTaggable to Taggable

### CODE REVIEW

**Comment by mshriver** [comment]
I feel like we've now gone full circle :D

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 572ae961b0dd1dfcb0f44dc832adb035936fa74a:

`cfme/services/catalogs/catalog.py`:
- :bangbang: Line 87:2: **E999** *SyntaxError: invalid syntax*
- :bangbang: Line 87:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 87:7: **E225** *missing whitespace around operator*
- :bangbang: Line 90:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 90:1: **E112** *expected an indented block*
- :bangbang: Line 90:3: **E225** *missing whitespace around operator*
- :bangbang: Line 90:5: **E225** *missing whitespace around operator*
- :bangbang: Line 90:7: **E225** *missing whitespace around operator*
- :bangbang: Line 91:1: **E302** *expected 2 blank lines, found 0*
- :bangbang: Line 92:1: **E305** *expected 2 blank lines after class or function definition, found 0*
- :bangbang: Line 92:1: **E112** *expected an indented block*
- :bangbang: Line 92:7: **E225** *missing whitespace around operator*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by izapolsk** [comment]
@rlbabyuk, PRT tests failed. you haven't renamed all occurancies.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
Rebase please

**Comment by rlbabyuk** [comment]
@psav just done

**Comment by mshriver** [comment]
Unrelated PRT failures in 22364

**Pull request merged**
