### PR TITLE
[WIP] adding create_ui/create_rest to VM Classes

### PR DESCRIPTION
**Pull request by lkhomenk**
Purpose or Intent
=================

This should unify VM provision
Adds 3 ways of getting VM via  UI/REST API/Mgmt_system

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6289b6ed020c3c2743482220c6fa48ddec827816:

`cfme/cloud/provider/gce.py`:
- :bangbang: Line 107:17: **E265** *block comment should start with '# '*
- :bangbang: Line 109:17: **E265** *block comment should start with '# '*
- :bangbang: Line 110:17: **E265** *block comment should start with '# '*
- :bangbang: Line 111:10: **E122** *continuation line missing indentation or outdented*
- :heavy_exclamation_mark: Line 113:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by izapolsk** [comment]
@lkhomenk, please don't append this to CloudInfraProvider. I'm going to remove it soon.

**Comment by lkhomenk** [comment]
Before adding into tests - I'm thinking if we need `varmeth` here. each method returns Vm in various representations.

**Comment by lkhomenk** [comment]
moving everything into VM classes

**Comment by dajoRH** [comment]
Lint report for commit fd19336b3247e2a63ea6524a3bd1273241feeebb:

`cfme/common/vm.py`:
- :red_circle: Line 23:1: **F811** *redefinition of unused 'exceptions' from line 11*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit de0cdfe52d59257b247d252d6d12ee3301e8948a:

`cfme/common/vm.py`:
- :red_circle: Line 23:1: **F811** *redefinition of unused 'exceptions' from line 11*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request closed without merging**
