### PR TITLE
Add settings in requirement mapping

### PR DESCRIPTION
**Pull request by akarol**
Purpose or Intent
=================
Add settings in requirement mapping

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fafa6e741ba5d84bfad531fa61d3923a3e03ff97:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
@akarol there is a discrepancy between what can be found on the product features MOJO page and what you are introducing in this PR - it says on the mojo page that "Feature: Settings" uses the "configuration" shortname, not "setting".

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by akarol** [comment]
@jkrocil As discussed with @psav, we were planning to have a separate requirement for the setting to include all the settings related test cases but i see that doing so will again raise some conflicts. It was name configuration since in earlier version setting was under configure tab.I think we better go with the existing "configuration". what do you think?

**Comment by dajoRH** [comment]
Lint report for commit 33bbe9139e14ee4311cfe2388223759adcf445f0:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
@akarol  Wouldn't it make more sense for it to be "settings" (plural)? Or this is to align with other thigns?

**Comment by akarol** [comment]
@mfalesni make sense.I will quickly update it.since we define everything as singular so i thought..

**Comment by psav** [comment]
@mfalesni we already agreed on the change to ```settings```

**Pull request merged**
