### PR TITLE
[WIP] Projects Dashboard Tests

### PR DESCRIPTION
**Pull request by pavelzag**
# Purpose or Intent

{{pytest: cfme/tests/containers/test_projects_dashboard.py -v --use-provider cm-env2 }}

This test is checking the data integrity of the Objects counter box and the Pods Table in the Containers Projects' Dashboard view.
It's depending on https://github.com/ManageIQ/wrapanapi/pull/193 PR that allows fetching Pods and Services object per selected project. It also allows getting Images per specific project
https://bugzilla.redhat.com/show_bug.cgi?id=1461618

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4760022988cbb84178764277e8c89c0764f98c83:

`cfme/tests/containers/test_projects_dashboard.py`:
- :red_circle: Line 2:1: **F401** *'collections.namedtuple' imported but unused*
- :red_circle: Line 9:1: **F401** *'cfme.containers.overview.ContainersOverview' imported but unused*
- :red_circle: Line 55:5: **F841** *local variable 'api_values' is assigned to but never used*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 538158e39fc6d35b4fc25ef54745578b466f9b55:

`cfme/containers/provider/__init__.py`:
- :red_circle: Line 7:1: **F401** *'widgetastic_manageiq.NestedSummaryTable' imported but unused*

`cfme/tests/containers/test_projects_dashboard.py`:
- :bangbang: Line 44:101: **E501** *line too long (117 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1acbdfcac28ffe281b7cb0878a134203b64f4105:

`cfme/tests/containers/test_projects_dashboard.py`:
- :bangbang: Line 19:25: **E261** *at least two spaces before inline comment*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by pavelzag** [comment]
@gshefer Please have a look and let me know if and what should I change
Thanks!

**Comment by psav** [comment]
From a code PoV it looks OK I think, just did a quick skim, but it fails on PRT

**Comment by pavelzag** [comment]
@psav 
It's depending on ManageIQ/wrapanapi#193 PR that allows fetching Pods and Services object per selected project. It also allows getting Images per specific project
https://bugzilla.redhat.com/show_bug.cgi?id=1461618

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c1d14070bc6bdf791c18b00562e34edc92ee59d:

`cfme/containers/provider/__init__.py`:
- :red_circle: Line 501:13: **F821** *undefined name 'FlashMessages'*

Please, rectify these issues :smirk: .

* ec89228480ab51875b6279620f64a67fc1f87b3e
  * Merge commit detected!!! :bangbang:
* 5c1d14070bc6bdf791c18b00562e34edc92ee59d
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b65bbaa0b6982fc6eb417c43ee3e2b8ba207a338:

`cfme/tests/containers/test_projects_dashboard.py`:
- :heavy_exclamation_mark: Line 94:10: **W292** *no newline at end of file*

`widgetastic_manageiq/__init__.py`:
- :bangbang: Line 604:6: **E111** *indentation is not a multiple of four*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2bc37645227336cc97688f7483ca639a7921a401:

`cfme/tests/containers/test_projects_dashboard.py`:
- :red_circle: Line 5:1: **F401** *'cfme.containers.image.Image' imported but unused*
- :bangbang: Line 22:9: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 27:5: **E121** *continuation line under-indented for hanging indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ddb6f8d5d400f405a99dbe698d360ce23535c3f3:

`cfme/tests/containers/test_projects_dashboard.py`:
- :bangbang: Line 22:9: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 27:5: **E121** *continuation line under-indented for hanging indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 64777bc6ac569a03cf168c645223304876b0e112:

`cfme/tests/containers/test_projects_dashboard.py`:
- :bangbang: Line 23:13: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 26:9: **E121** *continuation line under-indented for hanging indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by pavelzag** [comment]
@gshefer Please review the changes added after the collections fixes you merged
Lemme know if I can do this better

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Closing as #6810 introduces the same framework enhancements and tests.

**Pull request closed without merging**
