### PR TITLE
[WIPTEST]fixing finding Quadicon by short name in upstream

### PR DESCRIPTION
**Pull request by lkhomenk**
Purpose or Intent
=================

fixing search Quadicon by short name if name is greater than 12 symbols

A lot of test were failing as title in upstream was changed to title=test_...xlkjT(5 last symbols)

{{pytest: cfme/tests/cloud/test_instance_power_control.py::test_stop --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 466bf6d12f1c8026789b311881036893b7b67d31:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by lkhomenk** [comment]
This PR is needed for #3326 for Upstream

**Comment by psav** [comment]
We have a GH Issue open for this, unfortunately this fix could result in the wrong name being chosen. It is likely that we will have to wait for this to be fixed upstream.

**Comment by mfalesni** [comment]
I saw that it should be possible to retrieve the quadicon by name but that would required an overhaul of the locator structure.

**Comment by jkrocil** [comment]
It is a bug in upstream ManageIQ. This affects all quadicon types so letsl wait for a fix.

**Pull request closed without merging**
