### PR TITLE
[1LP][RFR] Testing generate widget content using auotmate method

### PR DESCRIPTION
**Pull request by ganeshhubale**
This tests case checks  whether content of dashboard widget is generated using via automate method.

{{ pytest: cfme/tests/intelligence/reports/test_widgets.py -k 'test_generate_widget_content_by_automate' -v }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 06ae48854b83f99f24a179d132a5ff6bf871cf08:

`cfme/tests/intelligence/reports/test_widgets.py`:
- :bangbang: Line 240:101: **E501** *line too long (102 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 55d414459729c09d228730faa785fb2eb73abdfd:

`cfme/tests/intelligence/reports/test_widgets.py`:
- :bangbang: Line 148:1: **E305** *expected 2 blank lines after class or function definition, found 1*
- :bangbang: Line 148:1: **E402** *module level import not at top of file*
- :red_circle: Line 148:1: **F401** *'cfme.utils.wait.wait_for' imported but unused*
- :bangbang: Line 149:1: **E302** *expected 2 blank lines, found 0*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by ganeshhubale** [comment]
@digitronik 
I have added PR for global fixtures: #8490

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request merged**
