### PR TITLE
[1LP][RFR] dockerbot: use readable task ids

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
**not yet tested**

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by izapolsk** [comment]
@RonnyPfannschmidt, we can change field size if it is necessary.

**Comment by RonnyPfannschmidt** [comment]
will shedule that one for later

**Comment by mshriver** [comment]
@RonnyPfannschmidt @izapolsk  Where are we with this PR? I would like to either pursue the changes in trackerbot and push this PR to merge, or close it if its no longer needed. 

Thanks!

**Comment by izapolsk** [comment]
@mshriver, @RonnyPfannschmidt,  I can prepare migration for trackerbot as I stated before. Is it everything what's necessary to tackle this ?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4fa175c7a5d7e48b053c0603eb1530237c6a8463:

`cfme/networks/provider/nuage.py`:
- :red_circle: Line 40:11: **N801** *class names should use CapWords convention*

`cfme/tests/ansible/test_embedded_ansible_basic.py`:
- :red_circle: Line 217:5: **N806** *variable in function should be lowercase*

`cfme/tests/v2v/test_v2v_ansible.py`:
- :red_circle: Line 121:5: **N806** *variable in function should be lowercase*

`cfme/utils/smem_memory_monitor.py`:
- :red_circle: Line 0:0: **EPY3** *Usage of .iteritems*

`cfme/utils/template/base.py`:
- :red_circle: Line 282:9: **N806** *variable in function should be lowercase*

`cfme/v2v/migrations.py`:
- :red_circle: Line 47:7: **N801** *class names should use CapWords convention*
- :red_circle: Line 71:7: **N801** *class names should use CapWords convention*
- :red_circle: Line 76:7: **N801** *class names should use CapWords convention*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
