### PR TITLE
 modify cleanup scripts to moduralise and reuse the existing code.

### PR DESCRIPTION
**Pull request by amavinag**
* created cleanup class in cleanup_edomain_templates script
    and reusing its methods in other scripts.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f6513cb4c3e52816c622eb78ebf30355e517e6d8:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Having a class for ```RhevmCleanup``` seems a little weird,  can some or all of this functionality go into mgmtsystem?

**Comment by RonnyPfannschmidt** [comment]
can the ssh client usage in the be warped into a `with contextlib.closing(...)`
else cleanup does not match the intentions in error cases

**Comment by dajoRH** [comment]
Lint report for commit c47c2e9eba92a608062027f79056317ed32a978f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1898737063c78c265776cd21762bb51b42a45510:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
I still think having a class for this is odd, am I alone?

**Comment by amavinag** [comment]
@psav, lets close this?
I can check rhevm mgmt script for cleanup if we can move it there. We can discuss that separately there.

**Comment by psav** [comment]
Closing by request

**Pull request closed without merging**
