### PR TITLE
Added pytest.mark.requirement

### PR DESCRIPTION
**Pull request by mkoura**
Purpose or Intent
=================
I've added new pytest.requirements to REST API related tests.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dfeb1cc5125e6fc0c3e548a8362eace4909ce4f2:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 414f7c5183742f926d31da1048c68aa4925cdc70:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mkoura** [comment]
@psav I changed it so that now there is just one requirement for each test. I made changes only in files where are no other tests but tests using REST API. Where I was not able to find more fitting label I marked it as "rest".
In files where is a mixture of rest api and "normal" tests I left it to respective FA owners to mark these tests.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 241484ff272c93bf9692c3c43627e61e75c68258:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
