### PR TITLE
[RFR] V2V: Add support for multiple versions of VDDK

### PR DESCRIPTION
**Pull request by nachandr**
### PRT Run

{{ pytest: cfme/tests/v2v/test_v2v_smoke.py --use-template-cache --provider-limit 2 --use-provider rhv44 --use-provider vsphere67-ims}}

The SSH test failure is not related to the changes made through this PR . The remaining three tests related to VDDK passed.
[rhevm-4.3-virtualcenter-6.7-nfs-nfs-rhel7_minimal-SSH]

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 0b168439f1a95fb95ae04f84ef27055b013e5ce1

The *global* fixture **`v2v_provider_setup`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 04b94508cf3d5bc863b93dd9fcd3791813c1a465

The *global* fixture **`v2v_provider_setup`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 1831b581ad183ccc0ed7d18febaa14d2f517c34c

The *global* fixture **`v2v_provider_setup`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit fdf5e17bab677ac5d2bbb79d375a849da025aacb

The *global* fixture **`v2v_provider_setup`** is used in the following files:
- **cfme/tests/cloud_infra_common/test_quota_with_multiple_providers.py**
    - *test_show_quota_used_on_tenant_screen*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Review by jawatts — APPROVED** [review]

**Review by mshriver — APPROVED** [review]

**Pull request merged**
