### PR TITLE
[WIP][NOTEST][NOMERGE] experiment with python3

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this takes a look at needs of python3 - the basic plan is to backport parts of this into the mainline until its no longer needed

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit abff9b5cdb8de687134555c3d25c4af92b08c389:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 1855:101: **E501** *line too long (102 > 100 characters)*

`cfme/web_ui/expression_editor.py`:
- :bangbang: Line 351:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ff9c74a35f97d5610bb37f1f8419a2c3c8f926c6:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 1708:101: **E501** *line too long (102 > 100 characters)*

`cfme/web_ui/expression_editor.py`:
- :bangbang: Line 351:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21e4a39e8da1c61132fab62e4dde55f22eb0352f:

`cfme/web_ui/__init__.py`:
- :bangbang: Line 1708:101: **E501** *line too long (102 > 100 characters)*

`cfme/web_ui/expression_editor.py`:
- :bangbang: Line 351:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34715452464d83da0917b6024291ac4f8143999d:

`cfme/infrastructure/virtual_machines.py`:
- :red_circle: Line 1021:29: **F821** *undefined name 'six'*

`cfme/utils/appliance/__init__.py`:
- :red_circle: Line 45:1: **F811** *redefinition of unused 'six' from line 20*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing due to repeat conflicts

**Pull request closed without merging**
