### PR TITLE
Fixing log collection for upstream 

### PR DESCRIPTION
**Pull request by otsuman**
{{pytest:  cfme/tests/configure/test_log_depot_operation.py  -k test_collect_log_depot}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 1d87427d0c4e97d4c1a48ceb2bce32d1880a3679:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
@otsuman The PR is not signed :/

**Comment by dajoRH** [comment]
Lint report for commit 4d77ca8e18da198da8911cd5edd6240a35f79148:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 998b0d87465a46a2dc7d24c00d56e9b088527ebd:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 29971d4c08c984452b1d6f0c917f0ff2f002bd88:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 19c58fea280eded61865440d617d542a7c2aecf4:

`cfme/tests/configure/test_log_depot_operation.py`:
- :bangbang: Line 234:52: **E231** *missing whitespace after ','*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 294f257a1f6d9daade250f80b2a7c5cf527dcce9:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
LGTM

**Pull request merged**
