### PR TITLE
Erradicate browser_session

### PR DESCRIPTION
**Pull request by psav**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 19c6c1ca10d5f56acb2b1e4365149c3615dbc0c9:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav You can actually remove the `utils.browser.browser_session` too as it seems not used anywhere.

**Comment by dajoRH** [comment]
Lint report for commit 002400be0578278b8ae6293db222c6edf94adbb2:

`utils/browser.py`:
- :red_circle: Line 7:1: **F401** *'contextmanager' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 838480d109654219f73a17173107cc72b5919444:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
