### PR TITLE
[DRAFT][WIP] Add sprout provider audit/cleanup script

### PR DESCRIPTION
**Pull request by mshriver**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 5f9a56e25d4280ec26b7e114073d59f0f30cf4a3:

`scripts/cleanup_sprout_providers.py`:
- :red_circle: Line 6:1: **F401** *'re' imported but unused*
- :red_circle: Line 17:1: **F401** *'cfme.utils.providers.get_mgmt' imported but unused*
- :bangbang: Line 25:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 69:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 78:5: **E303** *too many blank lines (2)*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 76be257625e1530231857fb08cf533a3e3a55f1d:

`scripts/cleanup_sprout_providers.py`:
- :bangbang: Line 29:1: **E302** *expected 2 blank lines, found 1*
- :heavy_exclamation_mark: Line 58:26: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 59:57: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 69:1: **W293** *blank line contains whitespace*
- :bangbang: Line 70:5: **E303** *too many blank lines (2)*
- :bangbang: Line 78:101: **E501** *line too long (101 > 100 characters)*
- :heavy_exclamation_mark: Line 86:1: **W293** *blank line contains whitespace*
- :bangbang: Line 87:5: **E303** *too many blank lines (2)*
- :heavy_exclamation_mark: Line 89:21: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 90:42: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 93:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 40393a1163c5d5f8c47dbde1c4a03b5b391a01ff:

`scripts/cleanup_sprout_providers.py`:
- :bangbang: Line 32:1: **E302** *expected 2 blank lines, found 1*
- :heavy_exclamation_mark: Line 61:26: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 62:57: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 71:1: **W293** *blank line contains whitespace*
- :bangbang: Line 80:101: **E501** *line too long (101 > 100 characters)*
- :heavy_exclamation_mark: Line 126:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 63067a0e4ed67335c3561a06b8e631ce824c4d97:

`cfme/utils/thread_tools.py`:
- :heavy_exclamation_mark: Line 45:52: **W292** *no newline at end of file*

`scripts/cleanup_sprout_providers.py`:
- :heavy_exclamation_mark: Line 77:1: **W293** *blank line contains whitespace*
- :bangbang: Line 86:101: **E501** *line too long (101 > 100 characters)*
- :red_circle: Line 125:22: **F821** *undefined name 'vm_to_delete'*
- :heavy_exclamation_mark: Line 132:1: **W293** *blank line contains whitespace*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1c75af3b73a6ab0710280a3c2015993a5d3a7054:

`cfme/utils/thread_tools.py`:
- :bangbang: Line 8:28: **E241** *multiple spaces after ','*
- :heavy_exclamation_mark: Line 52:52: **W292** *no newline at end of file*

`scripts/cleanup_sprout_providers.py`:
- :heavy_exclamation_mark: Line 31:6: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 32:33: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 80:1: **W293** *blank line contains whitespace*
- :bangbang: Line 89:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 137:1: **E305** *expected 2 blank lines after class or function definition, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a3420eff81c75728103c1324815deeda0aeb9fe8:

`cfme/utils/thread_tools.py`:
- :bangbang: Line 8:28: **E241** *multiple spaces after ','*
- :heavy_exclamation_mark: Line 52:52: **W292** *no newline at end of file*

`scripts/cleanup_sprout_providers.py`:
- :heavy_exclamation_mark: Line 31:6: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 32:33: **W291** *trailing whitespace*
- :heavy_exclamation_mark: Line 80:1: **W293** *blank line contains whitespace*
- :bangbang: Line 89:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 137:1: **E305** *expected 2 blank lines after class or function definition, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7d717826b93d197b83c753b015a90d55dd02c809:

`cfme/utils/thread_tools.py`:
- :bangbang: Line 8:28: **E241** *multiple spaces after ','*
- :heavy_exclamation_mark: Line 52:52: **W292** *no newline at end of file*

`scripts/cleanup_sprout_providers.py`:
- :red_circle: Line 23:1: **F401** *'cfme.utils.thread_tools.pool_manager' imported but unused*
- :bangbang: Line 89:101: **E501** *line too long (101 > 100 characters)*
- :bangbang: Line 128:9: **E265** *block comment should start with '# '*
- :bangbang: Line 138:1: **E303** *too many blank lines (3)*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
This has been implemented as a celery task

**Pull request closed without merging**
