### PR TITLE
[1LP][WIPTEST] Fixing test_operations_vm_on for archived/orphaned VMs

### PR DESCRIPTION
**Pull request by jan-zmeskal**
__Fixing__ test_operations_vm_on. The previous version did not take into account a situation where there might be:

- Orphaned VMs that don't have a host anymore
- Archived VMs that don't have a datastore anymore

{{pytest: cfme/tests/intelligence/reports/test_canned_corresponds.py::test_operations_vm_on -vv}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 47a35a796d942b60fc30a4141e46aa6666e4c311:

`cfme/tests/intelligence/reports/test_canned_corresponds.py`:
- :bangbang: Line 123:13: **E123** *closing bracket does not match indentation of opening bracket's line*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by jkrocil** [comment]
@jan-zmeskal Does this replace #6244?

**Comment by jan-zmeskal** [comment]
@jkrocil No, I don't think so. From the looks of it, these two PRs solve different issue. #6244 probably encountered some problem when there were too many rows in a report - at least I guess.

**Comment by psav** [comment]
No tests ran on PRT - was this intentional?

**Comment by jan-zmeskal** [comment]
@psav It was not. There was some issue with PRT when I was creating the PR. I'll try to re-run it

**Comment by jan-zmeskal** [comment]
@psav There is no possibility to re-test in PRT: http://10.16.4.32/trackerbot/pr/pr/6321

Do I need to move the PR back to the [WIPTEST] state?

**Pull request merged**
