### PR TITLE
Randomly choose the replicator, and then check all the Properties/Relationships in one navigation

### PR DESCRIPTION
**Pull request by jaryn**
Purpose or Intent
=================

__Optimizing__ the tests

{{pytest: cfme/tests/containers/test_containers_default_project_replicators.py -v --use-provider container }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f84c868f58a3f298c7ffcc4e79554fb423974b0c:

`cfme/tests/containers/test_containers_default_project_replicators.py`:
- :bangbang: Line 27:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by psav** [comment]
All tests are failing on PRT, do you still want this merged?

**Comment by psav** [comment]
Oh and it needs linting

**Comment by dajoRH** [comment]
Lint report for commit 00a7989e6d0d0395679cfe189bb315e913839b8e:

`cfme/tests/containers/test_containers_default_project_replicators.py`:
- :bangbang: Line 27:1: **E302** *expected 2 blank lines, found 1*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit daca745404d36954a6bd4dc04e5827dbae30b46e:

`cfme/tests/containers/test_containers_default_project_replicators.py`:
- :bangbang: Line 26:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 34:34: **E901** *SyntaxError: invalid syntax*
- :bangbang: Line 35:1: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 35:39: **E701** *multiple statements on one line (colon)*
- :bangbang: Line 45:1: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 46:1: **E122** *continuation line missing indentation or outdented*
- :bangbang: Line 46:39: **E701** *multiple statements on one line (colon)*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2d7e336efb9714203b4e079c3fedf536ebb71716:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1009465d91cbb727a2ac101205e34febb47fd8e3:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jaryn** [comment]
@pavelzag  Fixed in 1009465d91cbb727a2ac101205e34febb47fd8e3

**Comment by dajoRH** [comment]
Lint report for commit 0be213b4e3fd1e914a15a14e39773313d3984631:

Lint OK! :cake: :punch: :cookie: .

* 0be213b4e3fd1e914a15a14e39773313d3984631
  * Merge commit detected!!! :bangbang:

**The PR might not be acceptable in this state** :rage4:.
There is a merge commit in the branch which we do not like in PRs so please, get rid of it.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21dc2a561abdf78035b7099e94c22117e07a1c58:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
