### PR TITLE
[WIP] Adding Physical Servers Inventory Tests

### PR DESCRIPTION
**Pull request by douglasgabriel**
__Adding tests__ for get physical servers inventory data by API Rest:
- test_get_hardware
- test_get_hardware_firmware
- test_get_hardware_nics
- test_get_hardware_ports
- test_get_asset_details

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 512c552172e8aeb1e3c906f51623e070b1dee2b2:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_inventory.py`:
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 16:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 20:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 22:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 24:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 25:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 25:42: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 27:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 28:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 29:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 30:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 31:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 31:55: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 33:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 34:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 35:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 36:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 37:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 37:50: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 39:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 40:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 41:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 42:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 43:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 43:51: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 45:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 46:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 47:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 48:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 49:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 49:47: **E711** *comparison to None should be 'if cond is not None:'*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6c15c3c4d582df6777f52585ab4c2274f720631e:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/physical_infrastructure/test_physical_servers_inventory_api.py`:
- :bangbang: Line 28:44: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 35:57: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 42:52: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 49:53: **E711** *comparison to None should be 'if cond is not None:'*
- :bangbang: Line 56:49: **E711** *comparison to None should be 'if cond is not None:'*
- :heavy_exclamation_mark: Line 57:1: **W391** *blank line at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cc235f62859fc950059eb283dc94f1c89d8cbb31:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c8340fa42d93ec0f1249b7d23d76b7cd98446d1b:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/physical_infrastructure/test_physical_servers_inventory_api.py`:
- :bangbang: Line 11:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 15:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 40c37b6407943b63eb98ee346856339372a7c08d:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/physical_infrastructure/test_physical_servers_inventory_api.py`:
- :bangbang: Line 11:1: **E302** *expected 2 blank lines, found 1*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by douglasgabriel** [comment]
This PR was replace by https://github.com/ManageIQ/integration_tests/pull/6689

**Pull request closed without merging**
