### PR TITLE
Use unicode_literals everywhere.

### PR DESCRIPTION
**Pull request by jaryn**
Using unicode strings everywhere to avoid problems with encoding/decoding them on various places.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 667bc7e845ed9d8ee979fd159f662680e593865f:

`cfme/tests/containers/test_naming_conventions.py`:
- :bangbang: Line 8:4: **E121** *continuation line under-indented for hanging indent*

`cfme/web_ui/__init__.py`:
- :bangbang: Line 2346:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7389b4ca2d81170fea0c80fd97fa9dcc0bb361f7:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4396d385e668ce4d0cb66e10b626ae7dc478519a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c05533ddfc4eef31f6a3852ab5fe4c472415ac0b:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 854935ea5dfba1b738488b156903be9e62356a6c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 18cb46cfb1cd3f8fda341ec03acaa32d2eb281ef:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 252c882f75a155eba43130821697cd15080617f2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 737338e54514efff94c5369cf95a82606064ed72:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
I don't see a point with a significant weight that would justify this PR. This can potentially break things, not necessarily some on the first glance, down in the core. There is too much of risk in merging of this.

We *will* convert to Python 3 once all our dependencies can run with Python 3. I guess it will be done by those that wrote the core to catch the potential errors that can creep out.

**Comment by jaryn** [comment]
You are right @mfalesni . I just wanted to see how much of damage this will make. Looking at the outputs on the Trackerbot I have seen lots of Time-outs  do you think they were caused by this patch or are the cfme-tests so broken?

**Comment by jaryn** [comment]
For the record -- I used:

    find . -name '*.py' | grep -v '.venv' | xargs -tn1 sed -i '0,/import/s/\(.*import.*\)/from __future__ import unicode_literals\n\1/'

This `sed` has an issue with occurences of `import` in docstrings and comments though. So the patch still had to be processed by human eye.

**Comment by RonnyPfannschmidt** [comment]
note that using unicode literals are highly problematic on python2 - its something you never want in a codebase that uses other unowned codebases

**Pull request closed without merging**
