### PR TITLE
[1LP][WIP] update to pytest 3.0

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b13be4351cecd5056547a112d9ea0b46bbf68641:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 927d8e8a13385992c9bc4d63976d0604a1a68e88:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Still fails to run anything on Jenkins

**Comment by dajoRH** [comment]
Lint report for commit 9fce5b5979b05d7275d0b54480bc90757d6ff046:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2aa08721910bd4358fd3d3a82228f1b94f570c7f:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
@psav i updated it and did a force push with now 3.0.4, can we rerun and check?

**Comment by dajoRH** [comment]
Lint report for commit 91d1d21534ce52485a0a2a1eb6381719d808d7c7:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1874b6612c094566fb3774121df85dd4582cb48e:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 573229cae06354eb9edeaa00cfe8700597ead546:

`conftest.py`:
- :bangbang: Line 24:1: **E402** *module level import not at top of file*
- :bangbang: Line 24:47: **E261** *at least two spaces before inline comment*
- :bangbang: Line 24:48: **E262** *inline comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 63f91e79cacf59066c19ce6f4715d30b13b9d9e0:

`cfme/test_framework/pytest_plugin.py`:
- :grey_exclamation: Line 155:19: **S001** *found %s formatter*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
still trouble with pytest-warnings wrt assertion rewriting inhibition

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing in favor of the much more lightweight #4527

**Pull request closed without merging**
