### PR TITLE
[wip] widgetastic browser object integration: try to elevate reopen

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
by using a werkzeug local

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6c71c8734030dd6cd8686932c17738e123915b88:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 34d053e186abf28bd5ee695bc9378643dfc43ca5:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d7be35edacb05a6f45980fedbfcc5212707d8306:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 571d567101168403619870e9a1ff4af998ad9849:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing as a rebase was merged

**Pull request closed without merging**
