### PR TITLE
[WIP]Compliance mixin; Use it in the VM and Host

### PR DESCRIPTION
**Pull request by mfalesni**
{{pytest: cfme/tests/control/test_compliance.py -v }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 96056e406508a4b62450f93de29ce4f34a9f012f:

`cfme/common/vm.py`:
- :red_circle: Line 3:1: **F401** *'contextmanager' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7b485719160f4d16902d07ce212fee1ecf5b0fec:

`cfme/common/vm.py`:
- :red_circle: Line 3:1: **F401** *'contextmanager' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a9c6f994c6fd0a94792a0b66cf05ff5c6194e5b3:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
This is nice, can we get some tests around it from PRT?

**Comment by mfalesni** [comment]
@psav Sure, I can put some metadata here.

**Comment by mfalesni** [comment]
@psav Doesn't look too bad ;)

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 847901d2b71f44111ffbf8ed6aa8191a0906de73:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c1db405dee30debe9e9e13c7abf2872e217a948a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
Rebase needed again...

**Comment by dajoRH** [comment]
Lint report for commit 39419c6589ca22a7c757a26b71da0f3e14eb268c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
This is obsoleted by widgetastic

**Pull request closed without merging**
