### PR TITLE
[1LP][RFR] Fix for azure enviroment vars partial match

### PR DESCRIPTION
**Pull request by vatsalparekh**
Purpose or Intent
=================
added `partial_match` to solve `NoSuchElementException` ([Traceback](https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-59z/job/downstream-59z-tests-master/223/Artifactor_Report/cfme/tests/cloud/test_provisioning.py/test_provision_from_template[azure-Manual]/filedump-traceback.log), [Screenshot](https://cfmeqe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Downstream-59z/job/downstream-59z-tests-master/223/Artifactor_Report/cfme/tests/cloud/test_provisioning.py/test_provision_from_template[azure-Manual]/filedump-exception_screenshot.png))

{{ pytest: -vvvv cfme/tests/cloud/test_provisioning.py -k test_provision_from_template --use-provider azure }}

### CODE REVIEW

**Comment by vatsalparekh** [comment]
5.9 might get stuck due to [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1533808)

**Comment by izapolsk** [comment]
@vatsalparekh, your changes look good but partial_match doesn't work there for some reason

**Comment by vatsalparekh** [comment]
@izapolsk yes the partial_match is not working on 5.9z with this bootstrapselect, one thing I found was that xpath of the options inside the select was different from the ones in 5.8, and it works on 5.8

**Comment by izapolsk** [comment]
@vatsalparekh, the issue you run into should be sorted out by #widgetastic.patternfly/40

**Pull request merged**
