### PR TITLE
fix test_catalog.py

### PR DESCRIPTION
**Pull request by otsuman**
{{pytest: cfme/tests/services/test_catalog.py }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 22b499ed07522877c4e5fc4f5e2ab5a0b9ffe1bb:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5f25366cfcb7bc97b0d4f3835fe3e1a49f8f44a4:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 818a50781f7d9b7081c9a57bf973efaf24ae36bb:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by otsuman** [comment]
@psav previous run was 3/3. After it I only changed version.LOWEST and remove version pick for 5.5

**Pull request merged**
