### PR TITLE
[WIP] UI report script

### PR DESCRIPTION
**Pull request by jkrocil**
# Purpose or Intent

Adding a script to merge coverage reports from multiple jenkins test runs using an appliance from sprout.

**Example usage:**
`python scripts/ui_coverage_report.py --appliance-ip 10.11.22.33 --build-ids 711,720,724,742 --verbose --job-name downstream-56z-tests`

**Spits out:**

```
Coverage percentage for downstream-56z-tests, builds [711, 720, 724, 742], is 55.84%
To see the report, open /tmp/merged-report/index.html using your browser
```

but also a crazy amount of unnecessary spam...

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit dbcc69ac4a82b9fba09936f3693ff13f2df516de:

`scripts/ui_coverage_report.py`:
- :grey_exclamation: Line 85:9: **T001** *print statement found.*
- :grey_exclamation: Line 109:9: **T001** *print statement found.*
- :grey_exclamation: Line 131:9: **T001** *print statement found.*
- :grey_exclamation: Line 156:9: **T001** *print statement found.*
- :grey_exclamation: Line 178:9: **T001** *print statement found.*
- :grey_exclamation: Line 243:9: **T001** *print statement found.*
- :grey_exclamation: Line 258:9: **T001** *print statement found.*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by jkrocil** [comment]
@mfalesni print statements in scripts with --verbose are bad because?

**Comment by mfalesni** [comment]
@jkrocil 

This is a print *statement*:
```python
print "foo bar"
```

This is a print *function*:
```python
print("foo bar")
```
(actually in python 2 that still is a statement unless you use print_function future but this is one of hte forward-looking enforcements we do)

**Comment by jkrocil** [comment]
Ah, right, hahaa, will fix ;) thanks

**Comment by dajoRH** [comment]
Lint report for commit 6a62f47a2c41b37797b31dca9edc8ecb0a6f0ec2:

`scripts/ui_coverage_report.py`:
- :red_circle: Line 166:21: **N806** *variable in function should be lowercase*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request closed without merging**
