### PR TITLE
[WIPTEST]Widgetastic provider add and edit views + initial support of endpoints

### PR DESCRIPTION
**Pull request by izapolsk**
Purpose or Intent
=================
1. Add/Edit views + appropriate methods for Infra Providers (initial unification for Cloud Providers)
2. initial support of endpoints (in progress)

based on #4387 
includes fully or partially code from #4453 , #4445 , #4461

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Its a small chunk and its still _huge_ :)

**Comment by izapolsk** [comment]
@mshriver, it will become much more smaller when forthcoming PRs get merged :)

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 78d6411adb4c9f0ba20fb4a6acdd18f3ae12866e:

`cfme/common/provider.py`:
- :bangbang: Line 286:101: **E501** *line too long (101 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request closed without merging**
