### PR TITLE
[RFR] Fix test failure

### PR DESCRIPTION
**Pull request by valaparthvi**
## Purpose or Intent

- __Fixing__ 
    1. test_create_picture_with_role[individual
    2. webui/test_rest.py

### PRT Run
{{ pytest: cfme/tests -k "test_create_picture_with_role or test_delete_advanced_search_filter_from_detail or test_delete_advanced_search_filter_from_collection" -vvv }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 0237ac587a6210b31044c3e0348831022e74bc69

The *local* fixture **`config_manager_rest`** is used in the following files:
- **cfme/tests/infrastructure/test_config_management_rest.py**
    - *test_config_manager_create_rest*
    - *test_config_manager_edit_rest*
    - *test_config_manager_delete_rest*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 0c41f5a3db4e283407d3420cd64ba6c9ef015b35

The *local* fixture **`config_manager_rest`** is used in the following files:
- **cfme/tests/infrastructure/test_config_management_rest.py**
    - *test_config_manager_create_rest*
    - *test_config_manager_edit_rest*
    - *test_config_manager_delete_rest*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit ca51994b6adab6f99038b95c1420c1b97629d481

The *local* fixture **`config_manager_rest`** is used in the following files:
- **cfme/tests/infrastructure/test_config_management_rest.py**
    - *test_config_manager_create_rest*
    - *test_config_manager_edit_rest*
    - *test_config_manager_delete_rest*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit ff65232711009f468f8a54b61569112d913ea702

The *local* fixture **`config_manager_rest`** is used in the following files:
- **cfme/tests/infrastructure/test_config_management_rest.py**
    - *test_config_manager_create_rest*
    - *test_config_manager_edit_rest*
    - *test_config_manager_delete_rest*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 18893f5e3ae8c21a05a2e12099065a5186ac02be

The *local* fixture **`config_manager_rest`** is used in the following files:
- **cfme/tests/infrastructure/test_config_management_rest.py**
    - *test_config_manager_create_rest*
    - *test_config_manager_edit_rest*
    - *test_config_manager_delete_rest*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by john-dupuy** [comment]
@valaparthvi changes LGTM but these will also be fixed by #9317

**Comment by valaparthvi** [comment]
Hey @john-dupuy I see this PR will bring some major changes. But, since the PR is big, I'm assuming it would take some time to get merged, so can we carry on with these fixes for now?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by valaparthvi** [comment]
Hey @john-dupuy I removed the changes related to config_manager, can we take this PR further now?

**Pull request merged**
