### PR TITLE
[WIPTEST] move utils down into cfme

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
moving most of our utility code into a package below cfme

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 0f4a94b6dc4c14f280d6862e2db604e90964f270:

`cfme/tests/configure/test_version.py`:
- :heavy_exclamation_mark: Line 23:1: **W391** *blank line at end of file*

`cfme/tests/intelligence/reports/test_validate_chargeback_report.py`:
- :red_circle: Line 17:1: **F811** *redefinition of unused 'testgen' from line 15*
- :red_circle: Line 17:1: **F401** *'cfme.utils.version' imported but unused*

`cfme/tests/services/test_myservice.py`:
- :red_circle: Line 14:1: **F401** *'cfme.utils.version.current_version' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6e950674a816c979c82735b8c76cd20e1bfad1ba:

`cfme/tests/configure/test_version.py`:
- :heavy_exclamation_mark: Line 23:1: **W391** *blank line at end of file*

`cfme/tests/intelligence/reports/test_validate_chargeback_report.py`:
- :red_circle: Line 17:1: **F811** *redefinition of unused 'testgen' from line 15*
- :red_circle: Line 17:1: **F401** *'cfme.utils.version' imported but unused*

`cfme/tests/services/test_myservice.py`:
- :red_circle: Line 14:1: **F401** *'cfme.utils.version.current_version' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing in favor of #4104

**Pull request closed without merging**
