### PR TITLE
[WIP] Initial Azure Power Control implementation

### PR DESCRIPTION
**Pull request by jteehan**
Not too much magic here.  Already quick reviewed with Pete.

{{pytest: cfme/tests/cloud/test_instance_power_control.py -k "test_stop or test_start or test_suspend" --long-running --use-provider azure }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit a9c0a0fd7d435520024f0b642b3f6b3c65647fd2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jteehan** [comment]
Not a problem.  Actually, I already did but haven't committed anything new.  :)

**Comment by jteehan** [comment]
Right, so I changed all the region stuff locally after the azure mgmt was completed.  The problem with region is two fold.  First, it was in two locations in the yaml, so now I just extract it only from the provisioning section.  Second, the gui region has to be something like "US East",  but it's API counter part has to be "eastus".  To compensate for this, the new yaml will have region_gui and region_api.  I'm not happy about it either, but they're not interchangeable.

**Comment by dajoRH** [comment]
Lint report for commit 24998a75950809d833ec766d481e1b81e987ed02:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 63e823153245b207a3b05bbcebce9d3b4eefd06a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jteehan** [comment]
So, upstream passed.  It looks like the downstream PRT failures are for deploy_template not implemented, which means downstream didn't get the latest version of mgmt system.  We can retry tomorrow.  This is working locally.  The tests aren't necessarily passing, but some are, and I can see Azure VMs coming and going.

**Comment by dajoRH** [comment]
Lint report for commit 39286d4e9ba53707ab5baee36c366bcd97728c12:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jteehan** [comment]
I don't think 5.5 is ever going to pass because there are no events.  It's always going to timeout.

**Comment by jteehan** [comment]
I'm going to put this back into WIP.  The mgmt system needs a respin for some logic errors.  I think this PR is fine, but really need to see both working together.  I'll check that in tomorrow.

**Comment by dajoRH** [comment]
Lint report for commit 7309a8c39cbeab599754c5bc1a427f86f2fecba5:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 167cb07bfd28076bdbb5f18c414748f612afc397:

`cfme/cloud/provider/__init__.py`:
- :bangbang: Line 167:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 167:3: **E901** *SyntaxError: invalid syntax*
- :bangbang: Line 167:7: **E225** *missing whitespace around operator*
- :bangbang: Line 167:49: **E231** *missing whitespace after ':'*
- :bangbang: Line 167:49: **E701** *multiple statements on one line (colon)*
- :bangbang: Line 167:54: **E226** *missing whitespace around arithmetic operator*
- :bangbang: Line 167:60: **E226** *missing whitespace around arithmetic operator*
- :bangbang: Line 167:69: **E226** *missing whitespace around arithmetic operator*
- :bangbang: Line 168:3: **E225** *missing whitespace around operator*
- :bangbang: Line 168:5: **E225** *missing whitespace around operator*
- :bangbang: Line 168:7: **E225** *missing whitespace around operator*
- :bangbang: Line 169:1: **E302** *expected 2 blank lines, found 0*
- :bangbang: Line 258:7: **E225** *missing whitespace around operator*
- :bangbang: Line 258:51: **E231** *missing whitespace after ':'*
- :bangbang: Line 258:51: **E701** *multiple statements on one line (colon)*
- :bangbang: Line 258:56: **E226** *missing whitespace around arithmetic operator*
- :bangbang: Line 258:62: **E226** *missing whitespace around arithmetic operator*

`utils/providers.py`:
- :bangbang: Line 439:3: **E227** *missing whitespace around bitwise or shift operator*
- :bangbang: Line 439:3: **E901** *SyntaxError: invalid syntax*
- :bangbang: Line 439:7: **E225** *missing whitespace around operator*
- :bangbang: Line 441:3: **E225** *missing whitespace around operator*
- :bangbang: Line 441:5: **E225** *missing whitespace around operator*
- :bangbang: Line 441:7: **E225** *missing whitespace around operator*
- :bangbang: Line 442:5: **E113** *unexpected indentation*
- :bangbang: Line 569:7: **E225** *missing whitespace around operator*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eab0eafab9e518473ea36caa5efa4a8f66e9fb43:

`cfme/cloud/provider/__init__.py`:
- :red_circle: Line 230:13: **F821** *undefined name 'setup_provider_by_name'*

`utils/providers.py`:
- :red_circle: Line 10:1: **F401** *'partial' imported but unused*
- :red_circle: Line 451:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 456:25: **F821** *undefined name 'get_credentials_from_config'*
- :red_circle: Line 470:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 474:40: **F821** *undefined name 'credentials'*
- :red_circle: Line 476:40: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 488:16: **F821** *undefined name 'VMwareProvider'*
- :red_circle: Line 491:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 497:16: **F821** *undefined name 'SCVMMProvider'*
- :red_circle: Line 501:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 508:39: **F821** *undefined name 'credentials'*
- :red_circle: Line 510:40: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 512:16: **F821** *undefined name 'RHEVMProvider'*
- :red_circle: Line 522:39: **F821** *undefined name 'credentials'*
- :red_circle: Line 524:38: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 527:39: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 529:16: **F821** *undefined name 'OpenstackInfraProvider'*
- :red_circle: Line 539:23: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 540:16: **F821** *undefined name 'KubernetesProvider'*
- :red_circle: Line 549:23: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 550:16: **F821** *undefined name 'OpenshiftProvider'*
- :red_circle: Line 559:16: **F821** *undefined name 'HawkularProvider'*
- :red_circle: Line 564:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 566:15: **F821** *undefined name 'UnknownProviderType'*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b9a7431e0edb0b870f522617f489c17a1d3477ac:

`cfme/cloud/provider/__init__.py`:
- :red_circle: Line 230:13: **F821** *undefined name 'setup_provider_by_name'*

`utils/providers.py`:
- :red_circle: Line 10:1: **F401** *'partial' imported but unused*
- :red_circle: Line 451:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 456:25: **F821** *undefined name 'get_credentials_from_config'*
- :red_circle: Line 470:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 474:40: **F821** *undefined name 'credentials'*
- :red_circle: Line 476:40: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 488:16: **F821** *undefined name 'VMwareProvider'*
- :red_circle: Line 491:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 497:16: **F821** *undefined name 'SCVMMProvider'*
- :red_circle: Line 501:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 508:39: **F821** *undefined name 'credentials'*
- :red_circle: Line 510:40: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 512:16: **F821** *undefined name 'RHEVMProvider'*
- :red_circle: Line 522:39: **F821** *undefined name 'credentials'*
- :red_circle: Line 524:38: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 527:39: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 529:16: **F821** *undefined name 'OpenstackInfraProvider'*
- :red_circle: Line 539:23: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 540:16: **F821** *undefined name 'KubernetesProvider'*
- :red_circle: Line 549:23: **F821** *undefined name 'process_credential_yaml_key'*
- :red_circle: Line 550:16: **F821** *undefined name 'OpenshiftProvider'*
- :red_circle: Line 559:16: **F821** *undefined name 'HawkularProvider'*
- :red_circle: Line 564:37: **F821** *undefined name 'credentials'*
- :red_circle: Line 566:15: **F821** *undefined name 'UnknownProviderType'*

Whoa
Whoa :rage4: ! That is a lot of errors. Please go fix them :point_up: 
*CFME QE Bot*

**Pull request closed without merging**
