### PR TITLE
[RFR]Update classes to use BaseEntitiesView

### PR DESCRIPTION
**Pull request by rlbabyuk**
Purpose or Intent
=================
Update classes to use BaseEntitiesView + navigation steps update
{{pytest: -k 'test_delete_resource_pool_appear_after_refresh or test_tagvis_cloud_object' --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ab7fcc53c42da3cf0bf676a92a47516bf1c5e811:

`cfme/cloud/availability_zone.py`:
- :bangbang: Line 79:5: **E265** *block comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by quarckster** [comment]
Looks good, what about the failed test for 5.9?

**Comment by rlbabyuk** [comment]
Added workaround to a widget, as there were changes in the tags dropdown, with this changes tag assignment is successful for 5.9. 
https://github.com/RedHatQE/widgetastic.patternfly/pull/32

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request merged**
