### PR TITLE
[1LP][RFR] small fix for service tests

### PR DESCRIPTION
**Pull request by izapolsk**
{{pytest: --use-provider=vsphere55 --long-running cfme/tests/services/test_myservice.py cfme/tests/services/test_service_catalogs.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d0f1e41c9715fbc74bf23a542dd5178d065d18a0:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6c5422e6ae2389efda261b275bae889173c62f59:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 04708cdacbc7198da0da3eb978ce44ebde205f5b:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by izapolsk** [comment]
ssveta and mshriver already work  on fixing service tests. So, I just want to add slight fix which they didn't notice.

**Pull request merged**
