### PR TITLE
[RFR]Small fix in alert message for MapTags

### PR DESCRIPTION
**Pull request by pavelzag**
A small fix for the alert message in the MapTags menu

### CODE REVIEW

**Comment by mkoura** [comment]
Please see https://github.com/ManageIQ/integration_tests/pull/5037

**Comment by pavelzag** [comment]
Yes, I saw. This PR is dated 4 days ago though..

**Comment by izapolsk** [comment]
sorry Pavel, I noticed and picked up #5037 first :(. it has already been merged.

**Comment by pavelzag** [comment]
No worries :D

**Pull request closed without merging**
