### PR TITLE
Service Catalog 5.7 fix

### PR DESCRIPTION
**Pull request by sshveta**
UI message change in 5.7 for service requests and added provisioning entry point for bundle .
Also marked tests with some new bugs

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 47d5ced685e625617e5484744b2aa3a0cac0bf00:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0c203cc6c76def41b36af8851a686ab43e00c0f7:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by sshveta** [comment]
Recent widgetastic changes are not working with upstream build and navigation is failing

**Comment by dajoRH** [comment]
Lint report for commit 97da451c0fcf20336ca8896a8ddfcb1cd06917ce:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a64b7a2350e631ae95620bfcb51283acd9b0f2d1:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit df60105989db643c8323754fb5859e6881c5d7e2:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
