### PR TITLE
[RFR][1LP] Remove external implementations method from sentaku

### PR DESCRIPTION
**Pull request by psav**
Removing a warning generator :)

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4638d8efd3567d32b70fa25c92adc2497dbfc0a0:

`cfme/services/service_catalogs/__init__.py`:
- :heavy_exclamation_mark: Line 34:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
those should be more like ?importscan.scan(__name__)`

**Comment by RonnyPfannschmidt** [comment]
so we shoudl have soemwhere more upwards a call like `importscan.scan(__name__, ignore=lambda modname: 'test' in modname)`

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9f89f975b7f12428adaf8437c308ef2386f9fa6e:

`cfme/services/service_catalogs/__init__.py`:
- :heavy_exclamation_mark: Line 34:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
