### PR TITLE
[WIP] Widgeting system

### PR DESCRIPTION
**Pull request by mfalesni**
This is heavily WIP.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 7a9e38ec85eb422d7c2bac7b5f7c8ec609a0f2ef:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0d61757dddf14d3e80f0381527c93cd3ec23d42a:

`pomoc/browser.py`:
- :red_circle: Line 2:1: **F401** *'ErrorInResponseException' imported but unused*
- :red_circle: Line 2:1: **F401** *'InvalidElementStateException' imported but unused*
- :red_circle: Line 2:1: **F401** *'InvalidSwitchToTargetException' imported but unused*
- :red_circle: Line 2:1: **F401** *'NoAlertPresentException' imported but unused*
- :red_circle: Line 2:1: **F401** *'NoSuchAttributeException' imported but unused*
- :red_circle: Line 2:1: **F401** *'UnexpectedAlertPresentException' imported but unused*
- :red_circle: Line 2:1: **F401** *'WebDriverException' imported but unused*

`pomoc/objects.py`:
- :red_circle: Line 89:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
Basing against FW30 branch

**Comment by dajoRH** [comment]
Lint report for commit fa1bc5f98790effb68681c8ebc3be3a78ad82d93:

`pomoc/browser.py`:
- :red_circle: Line 4:1: **F401** *'ErrorInResponseException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidElementStateException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidSwitchToTargetException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoSuchAttributeException' imported but unused*
- :red_circle: Line 4:1: **F401** *'UnexpectedAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'WebDriverException' imported but unused*

`pomoc/objects.py`:
- :red_circle: Line 86:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Pull request closed without merging**
