### PR TITLE
SSA scan and Properties table - added comments, modifications

### PR DESCRIPTION
**Pull request by jdemon519**
Purpose or Intent
=================

Fixed assert issue in  cfme/tests/containers/test_containers_properties.py
Implemented flash function in cfme/tests/containers/test_one_image_analysis.py

{{pytest: cfme/tests/containers/test_containers_properties.py -v --use-provider container }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2c4364c8a7ea1ff74a54437b4b049813b6a47d95:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 29e614ee04237c84073f770f7f19f7bc612677f2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by jdemon519** [comment]
Jenkins test run

https://cm-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/All/job/ashlifst-test/61/console

**Comment by psav** [comment]
This seems to include other PRs inside it, I'm rather confused, can we isolate changes inside PRs, or at least give me a chain of PRs so I can follow from the beginning.

**Comment by jdemon519** [comment]
I'll redo the PRs today, splitting them up into 4 or 5 different ones.

**Pull request closed without merging**
