### PR TITLE
[NOTEST] kill most hookwrapper usage

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
this one needs a big test-run, and maybe a cherrypick to master

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9cf7b57068c4d6f23c34381bf003b107af5a0733:

`fixtures/parallelizer/__init__.py`:
- :red_circle: Line 47:1: **F401** *'pytest' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 3942bf4ebf3d699e3df59a6f9af68b423b07c07f:

`fixtures/parallelizer/__init__.py`:
- :red_circle: Line 47:1: **F401** *'pytest' imported but unused*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 84364fde6291782dc953b7092935728682afbe07:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c0f24d9ecd5c30ac7709b6aa9896adde43decb5:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing due to initial misstake in source branch

**Pull request closed without merging**
