### PR TITLE
[WIP] Widgeting system

### PR DESCRIPTION
**Pull request by mfalesni**
Heavy wip

```python
from cfme.configure.access_control import User, Credential
from cfme.classic_ui.intelligence import Reports, Dashboard
u = User()
u.credential = Credential(principal='admin', secret='smartvm', verify_secret='smartvm')
from fixtures.pytest_store import store
n = store.current_appliance.browser.navigator
# Now the fun
n.navigate_to(Reports, user=u)
n.navigate_to(Dashboard, user=u)
n.navigate_to(Reports, user=u)
```

Dashboard -> Reports should not need user=. Going anywhere from Reports requires user because it does not have on_view, it reloads the browser. I guess on_view will become mandatory.

You can also try from cfme.classic_ui.compute.infrastructure.providers import InfrastructureProviders and navigate to it too.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6ac3d5089cf52d10790a2d5a52feccf225b30ef0:

`pomoc/browser.py`:
- :red_circle: Line 4:1: **F401** *'ErrorInResponseException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidElementStateException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidSwitchToTargetException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoSuchAttributeException' imported but unused*
- :red_circle: Line 4:1: **F401** *'UnexpectedAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'WebDriverException' imported but unused*

`pomoc/objects.py`:
- :red_circle: Line 86:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d29b1c72302b1a1f561c104b402c28b4d490eaa9:

`pomoc/browser.py`:
- :red_circle: Line 4:1: **F401** *'ErrorInResponseException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidElementStateException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidSwitchToTargetException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoSuchAttributeException' imported but unused*
- :red_circle: Line 4:1: **F401** *'UnexpectedAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'WebDriverException' imported but unused*

`pomoc/objects.py`:
- :red_circle: Line 86:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 024e8d1197b9ebd58c7eb38a8735d4294f037457:

`cfme/classic_ui/base.py`:
- :red_circle: Line 8:11: **N801** *class names should use CapWords convention*

`pomoc/browser.py`:
- :red_circle: Line 4:1: **F401** *'ErrorInResponseException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidElementStateException' imported but unused*
- :red_circle: Line 4:1: **F401** *'InvalidSwitchToTargetException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'NoSuchAttributeException' imported but unused*
- :red_circle: Line 4:1: **F401** *'UnexpectedAlertPresentException' imported but unused*
- :red_circle: Line 4:1: **F401** *'WebDriverException' imported but unused*

`pomoc/objects.py`:
- :red_circle: Line 97:9: **N802** *function name should be lowercase*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
This can be closed now I assume?

**Comment by mfalesni** [comment]
Indeed

**Pull request closed without merging**
