### PR TITLE
[1LP][RFR] Updated test help menu

### PR DESCRIPTION
**Pull request by rlbabyuk**
Purpose or Intent
=================
1) Updated help manu test due to https://polarion.engineering.redhat.com/polarion/#/project/RHCF3/workitem?id=RHCF3-22486 request.
2) Added cleanup, extend option checks
3) Added new ui cases
4) Fixed expression editor locators for 5.10

{{pytest: cfme/tests/webui/test_general_ui.py cfme/tests/infrastructure/test_advanced_search_vms.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 3874dd7d431a510ea163e0ea6f00e68f4460a4b3:

`cfme/tests/webui/test_general_ui.py`:
- :heavy_exclamation_mark: Line 122:79: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit cd8a8f231de06d8cac2af04f0f814c5656dd2405:

`cfme/tests/webui/test_general_ui.py`:
- :bangbang: Line 129:101: **E501** *line too long (113 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by quarckster** [comment]
Expression Editor requires a little bit more fixes look #7516 I propose to wait until #7516 will be merged.

**Comment by psav** [comment]
#7516 is now merged, please relook at this

**Pull request merged**
