### PR TITLE
[1LP][RFR] move markers to cfme.markers

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
tested locally with collect-only, should be merge-able when the tests pass, but take with a grain of salt

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@psav at first glance the errors seem unrelated

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Looks great, but @psav suggested, and I agree, probably better to wait until after test stabilization to move these. Will merge right after a release (17.20.0 maybe?)

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f5b52380fb51fef371de9faa1d24779bb6e8b541:

`cfme/tests/infrastructure/test_host.py`:
- :red_circle: Line 16:1: **F401** *'cfme.markers.env_markers.provider.providers' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
needs a crosscheck on prt before merge

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
```
==================================== ERRORS ====================================
_________ ERROR at setup of cfme/tests/infrastructure/test_ssa_vddk.py _________
ImportError while importing test module '/cfme_tests_te/cfme/tests/infrastructure/test_ssa_vddk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
cfme/tests/infrastructure/test_ssa_vddk.py:13: in <module>
    from markers.env_markers.provider import ONE_PER_VERSION
E   ImportError: No module named markers.env_markers.provider
___________ ERROR at setup of cfme/tests/networks/test_tag_tagvis.py ___________
ImportError while importing test module '/cfme_tests_te/cfme/tests/networks/test_tag_tagvis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
cfme/tests/networks/test_tag_tagvis.py:6: in <module>
    from markers.env_markers.provider import ONE_PER_CATEGORY
E   ImportError: No module named markers.env_markers.provider
_______ ERROR at setup of cfme/tests/ssui/test_ssui_service_catalogs.py ________
ImportError while importing test module '/cfme_tests_te/cfme/tests/ssui/test_ssui_service_catalogs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
cfme/tests/ssui/test_ssui_service_catalogs.py:10: in <module>
    from markers.env_markers.provider import providers
E   ImportError: No module named markers.env_markers.provider
```

**Comment by RonnyPfannschmidt** [comment]
should be fixed now, waiting for prt

**Pull request merged**
