### PR TITLE
[1LP][RFR][NOTEST] Fix for all method avoiding Ansible Embedded Manager

### PR DESCRIPTION
**Pull request by digitronik**
Purpose or Intent
=================
```
>       raise NameError("Could not find provider {}".format(provider_name))
E       NameError: Could not find provider Embedded Ansible Automation Manager

cfme/utils/providers.py:340: NameError
NameError
Could not find provider Embedded Ansible Automation Manager
```
```
In [5]: for prov in providers:
   ...:     print prov.name, getattr(prov, "parent_ems_id", False)
   ...:
   ...:
RHOS11 False
RHOS11 Network Manager 3
RHOS11 Cinder Manager 3
RHOS11 Swift Manager 3
Embedded Ansible Automation Manager False
```

I found the check for `parent_ems_id` is not proper in case of `Ansible Embedded Manager`. To deal with Manger better to check in provider name only `"Manager"` is available or not.

### CODE REVIEW

**Comment by digitronik** [comment]
@mshriver @izapolsk what you think about this?

**Comment by digitronik** [comment]
Extended this PR to fix

```
>   datastore_db = {ds.name: ds.hosts[0]["ems_id"] for ds in datastores}
E   IndexError: list index out of range

cfme/infrastructure/datastore.py:333: IndexError
IndexError
list index out of range
```

**Comment by sshveta** [comment]
@digitronik : Any tests that we can run and check ?

**Comment by digitronik** [comment]
@sshveta we can not reproduce this by running test. It can reproduce while run means old appliance which run for embedded Anabel same use for custom button test.

**Pull request merged**
