### PR TITLE
[WIP] - change group on SSUI

### PR DESCRIPTION
**Pull request by dgaikwad**

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 86cb4c3dfbd53733ecfc782b9936dae40a7b0891

The *local* fixture **`custom_user`** is used in the following files:
- **cfme/tests/configure/test_access_control.py**
    - *test_ssui_group_switch*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 5e50d55ff6ad44a4fa655b40fbfaed7c2a27f61a

The *local* fixture **`custom_user`** is used in the following files:
- **cfme/tests/configure/test_access_control.py**
    - *test_ssui_group_switch*

The *local* fixture **`policy_profiles`** is used in the following files:
- **cfme/tests/control/test_rest_control.py**
    - *test_query_policy_attributes*
    - *test_create_policy_profiles*
    - *test_edit_policy_profiles*
    - *test_delete_policy_profiles_from_detail*
    - *test_delete_policy_profiles_from_collection*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 4948327b05705603e62cf4af797fa981b45426e4

The *local* fixture **`custom_user`** is used in the following files:
- **cfme/tests/configure/test_access_control.py**
    - *test_ssui_group_switch*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dgaikwad** [comment]
this large effort testcase so decided to not automate

**Pull request closed without merging**
