### PR TITLE
[1LP][RFR] service tests fix

### PR DESCRIPTION
**Pull request by izapolsk**
The issue is caused by Tab click. That click was added in order to resolve the issue when cfme didn't see some changes made in provisioning dialog. 
So, one of ways to fix that issue could be to fix that root issue.

{{pytest: --long-running cfme/tests/services/test_service_catalogs.py cfme/tests/infrastructure/test_provisioning_dialog.py}}

### CODE REVIEW

**Comment by izapolsk** [comment]
@lkhomenk, your thoughts ?

**Comment by izapolsk** [comment]
I've restarted PRT in order to check issues with filling/clearing input fields really disappeared.

**Comment by mshriver** [comment]
some PRT results in for 58z and 59z in run 17257.

**Comment by jkrocil** [comment]
Merging, providing we find a proper solution in then next 4 weeks. If not, we need to revisit this. @izapolsk

**Comment by lkhomenk** [comment]
proper solution would be - provision forms migration to Angular as per developer's comment on this =)

**Comment by izapolsk** [comment]
@lkhomenk, have you heard about ETA ?

**Pull request merged**
