### PR TITLE
[1LP][RFR] Collect Logs conversion

### PR DESCRIPTION
**Pull request by rlbabyuk**
Purpose or Intent
=================
Collect Logs conversion for Server and Zone

{{pytest: cfme/tests/configure/test_log_depot_operation.py}}

PRT(17982): only 1 failure for 5.9( test_collect_log_depot[anon_ftp] ) and doesn't caused by conversion

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f3663cb9348683923fb15801a6d8c53e0e4ad80a:

`cfme/configure/configuration/__init__.py`:
- :bangbang: Line 11:33: **E271** *multiple spaces after keyword*

`cfme/configure/configuration/diagnostics_settings.py`:
- :bangbang: Line 246:15: **E271** *multiple spaces after keyword*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9348541445baa5773a8c1171a418ee876e4baf46:

`cfme/tests/configure/test_log_depot_operation.py`:
- :heavy_exclamation_mark: Line 328:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
Marking WIPTEST due to PRT results in 17797

**Comment by rlbabyuk** [comment]
Restarted PRT as it looked like there were some network issues. Now PRT run looks good, one case is failing for 5.9, it doesn't cause by PR changes and I would like to add fix with separate PR

**Pull request merged**
