### PR TITLE
Fix menu levels checks

### PR DESCRIPTION
**Pull request by mkoura**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 260ede7a95ff2b68361b494821560430723fe091:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ae3cfecc726a79a58da07eb9001533841b8dad3d:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c23b4eca83081071cac3b5b31eed4feeb916049f:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 155d48ec6f37e9cea4249692f58005abe2988a78:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 86c1f3693b67d6f9e9e169e8bb9cc6914b45336c:

`cfme/tests/configure/test_visual_cloud.py`:
- :red_circle: Line 11:1: **F401** *'current_version' imported but unused*

`cfme/tests/configure/test_visual_infra.py`:
- :red_circle: Line 11:1: **F401** *'virtual_machines' imported but unused*
- :bangbang: Line 207:7: **E127** *continuation line over-indented for visual indent*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4b06c3cc31f5d6b0d09a7649ff34619981360c49:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
LGTM, the only single failing test is unrelated to the main focus of this fix and has been assigned to someone else already :+1:

**Pull request merged**
