### PR TITLE
[1LP][RFR] fix open url changes

### PR DESCRIPTION
**Pull request by digitronik**
Signed-off-by: Nikhil Dhandre <ndhandre@redhat.com>

Purpose or Intent
=================

Needs `Checkbox` `is_enabled` property

{{pytest: cfme/tests/automate/custom_button/test_buttons.py::test_open_url_availability}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by digitronik** [comment]
@izapolsk @mshriver please review `is_enabed` property for `Checkbox`
https://github.com/RedHatQE/widgetastic.core/pull/155

This PR depends on that property.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mshriver** [comment]
@digitronik WT.core update merged and released with 0.39. Please update requirements files here with the new version, and use the widget property instead of the direct calls to `__element__` made here.

**Pull request merged**
