### PR TITLE
[1LP][RFR] switch to modern setuptools and create a initial wheel package

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
its makes the entry-points a more easily editable text file and it makes the package a more easy edit

i didn't yet experiment with the wheels suitability but this is probably something others can experiment with

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by psav** [comment]
```
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    use_scm_version=True,
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools/__init__.py", line 131, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools/dist.py", line 370, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools/dist.py", line 529, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/integration.py", line 22, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 119, in get_version
    parsed_version = _do_parse(root, parse)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 83, in _do_parse
    version = version_from_scm(root) or _version_from_entrypoint(
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 31, in version_from_scm
    return _version_from_entrypoint(root, 'setuptools_scm.parse_scm')
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/__init__.py", line 36, in _version_from_entrypoint
    version = ep.load()(root)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/git.py", line 126, in parse
    return meta(tag, distance=number, node=node, dirty=dirty, branch=branch)
  File "/home/user/work/cfme_venv_pycharm/lib/python2.7/site-packages/setuptools_scm/version.py", line 135, in meta
    assert tag is not None, 'cant parse version %s' % tag
AssertionError: cant parse version None
```

**Comment by RonnyPfannschmidt** [comment]
@psav will be fixed by `setuptools_scm==3.0.0` in 5-10

**Comment by psav** [comment]
Code wise looks good, but it seems there is breakage here

**Comment by psav** [comment]
Great looking forward to it

**Comment by RonnyPfannschmidt** [comment]
cycled to retrigger travis after stale-ness

**Pull request merged**
