### PR TITLE
[1LP][RFR] unblock added for cla != ContainersProvider

### PR DESCRIPTION
**Pull request by gshefer**
{{pytest: cfme/tests/containers/test_containers_main_pages_sort.py -v }}

### CODE REVIEW

**Comment by gshefer** [comment]
There is a bug in the framework that raise exception once we are trying to sort a table column with empty fields:
http://10.16.45.124/xgIo2PGx/artifacts/report.html

**Comment by mshriver** [comment]
Can you revise your pytest command to run against non-container providers so we can confirm this uncollects appropriately? Thanks.

**Comment by gshefer** [comment]
Do you mean '{{pytest: cfme/tests/containers/test_containers_main_pages_sort.py -v }}' right?

**Comment by mshriver** [comment]
Yep, or specify a non-container type, just so we see both sides.

Looks like the failing PRT results in the last run (with container provider) are unrelated to scoping this test.

Please open a GH issue against the framework bug you mentioned in an earlier comment.

**Comment by gshefer** [comment]
Done - https://github.com/ManageIQ/integration_tests/issues/4052

**Pull request merged**
