### PR TITLE
[WIP] Let PXESystemImageEditView inherit is_displayed from parent class

### PR DESCRIPTION
**Pull request by jan-zmeskal**
Ignore for now

### CODE REVIEW

**Comment by mshriver** [comment]
I think I know what you're trying to fix, but I don't think this is the right way to go about it in this case - the `PXEMainView.is_displayed` only looks at the vertical navigation selection.

This is a result of wait_for_view being the default behavior of navigate_to. Since this is an edit page, and its a fine practice to default to never matching the view - you'll want to update any calls to navigate to this view to pass `wait_for_view=0`.

We may be implementing a pattern to have such `is_displayed` methods raise `NotImplemented`, so if you'd like to wait a bit that may be a better fix than updating the nav calls.

**Comment by jan-zmeskal** [comment]
Hi @mshriver, you're right. Already yesterday I realized that `wait_for_view=0` is much better solution. I didn't have time to change this PR so I at least let it hang there as a reminder for me. I don't understand the last part of your message though. Are you preparing a change that will fix this more globally. Or should I still create a PR for `wait_for_view=0`?

**Comment by mshriver** [comment]
@jan-zmeskal the last comment I made was about an idea I had for how to handle these views where we explicitly do not want to implement is_displayed, but don't want to force callers to account for the fact that it returns False.

@izapolsk ran with the idea and opened up #7958

**Comment by jan-zmeskal** [comment]
@mshriver I see. If I understand it correctly, after izapolsk's PR is merged, we'll have to `raise NotImplementedError` in the views that now return `False` in `is_displayed`, right?

**Comment by mshriver** [comment]
That's correct, but we're still debating the merits of that pattern. Please raise any concerns or ideas you have about it in #7958.

In the meantime, passing `wait_for_view=0` or implementing the is_displayed method are both viable fixes for nav.

**Comment by jan-zmeskal** [comment]
@mshriver I am in no rush as far as fixing ISO provision test case goes, since the feature itself does not work right now. I just want to ask: Could we create some GH issue where we could track progress on this?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request closed without merging**
