### PR TITLE
Update _on_details_page() for providers

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ae848b0d48d692397662227afd2748cfbf430864:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
@psav I have removed the change to _on_details_page but kept the change to the reload locator. I hope this is good to merge.

**Comment by dajoRH** [comment]
Lint report for commit a8fe2359d75ff982bb5c0e825a13a47f362105a0:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
