### PR TITLE
[1LP][RFR] Add manual cases and cleanup Generic Object tests

### PR DESCRIPTION
**Pull request by john-dupuy**
Adding some manual test cases for generic objects. These will be automated in the near future. 

Also moving generic object and generic object button tests to their own folder under `cfme.tests.automate`

{{ pytest: --long-running cfme/tests/automate/generic_objects/ }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 159ca8261b9a14bc92eebaeb54025b9d85d598cc

The *local* fixture **`gen_obj_def_import_export`** is used in the following files:
- **cfme/tests/automate/generic_objects/test_definitions.py**
    - *test_import_export_generic_object_definition*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit c481c4846135e28c1a3ddfa35309702667133adb

The *local* fixture **`button_group`** is used in the following files:
- **cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py**
    - *_generic_object_button*
    - *test_custom_button_on_generic_class_crud*

The *local* fixture **`gen_obj_def_import_export`** is used in the following files:
- **cfme/tests/automate/generic_objects/test_definitions.py**
    - *test_import_export_generic_object_definition*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by jawatts** [comment]
@john-dupuy can you check the PRT failure in 5.10

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 243305c0229d896621c32bd80cbf4226da9b4952

The *local* fixture **`button_group`** is used in the following files:
- **cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py**
    - *_generic_object_button*
    - *test_custom_button_on_generic_class_crud*

The *local* fixture **`gen_obj_def_import_export`** is used in the following files:
- **cfme/tests/automate/generic_objects/test_definitions.py**
    - *test_import_export_generic_object_definition*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Pull request merged**
