### PR TITLE
[RFR] Automate: test_dynamic_dialogs_on_service_request

### PR DESCRIPTION
**Pull request by valaparthvi**
## Purpose or Intent

- __Adding tests__ 
    1. test_dynamic_dialogs_on_service_request

### PRT Run
{{ pytest: cfme/tests/services/test_dialog_element_in_catalog.py -k test_dynamic_dialogs_on_service_request -svvv }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit dfbf6dcfa7d54bb69d62706fc8e76f4047f14f36

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 0643c76213ff26f9b3e3ef8ae6ec8a2ab3605461

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 4f55f081e79b3d7a7da4913bcf13343642f1b88d

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit f8b8bf77fa65502fcf24e03465ccd74726a473af

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit b3b1c6a0315c0096e3e964335db10b724aa97e50

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 49a2c3fb54aeafd2f05620f2e77b5a05e74f546f

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit d953f24c5ea94642aa8ee14286c480ec03bf7dfa

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit d953f24c5ea94642aa8ee14286c480ec03bf7dfa:

`cfme/tests/services/test_dialog_element_in_catalog.py`:
- :bangbang: Line 663:16: **E702** *multiple statements on one line (semicolon)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit df85f96b9fb206d9f2d0475fb11a6998687107df:

`cfme/tests/services/test_dialog_element_in_catalog.py`:
- :bangbang: Line 659:16: **E702** *multiple statements on one line (semicolon)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit df85f96b9fb206d9f2d0475fb11a6998687107df

The *local* fixture **`service`** is used in the following files:
- **cfme/tests/services/test_dialog_element_in_catalog.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dgaikwad** [comment]
LGTM

**Pull request merged**
