### PR TITLE
Added more verifications on  datasource creation as bugs are fixed.

### PR DESCRIPTION
**Pull request by hhovsepy**
Did some refactorings in datasource and JDBC driver methods.

{{pytest: cfme/tests/middleware/test_middleware_datasource.py cfme/tests/middleware/test_middleware_drivers.py -v --use-provider hawkular --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4f349197b5e0be47cf244e65697c14ac2e008511:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by hhovsepy** [comment]
there is a problem in PRT, tests are not run

**Comment by mfalesni** [comment]
@hhovsepy Added targeted pytest options in the PR description and initiated a retest.

**Comment by hhovsepy** [comment]
downstream tests passes
can this PR me merged?

**Pull request merged**
