### PR TITLE
[WIP] Add SSUI progress bar wait

### PR DESCRIPTION
**Pull request by jkrocil**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 9f13aaece73c7786f434851d1bc0f7910ac7c622:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8b53f24d740f9e59dc3699dda757f851fef3fb09:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@jkrocil The in_flight script is becoming quite big, I think it is time to engage jsmin there.

**Comment by psav** [comment]
I forget, did we solve this?

**Comment by psav** [comment]
I'm thinking this can probably go now? We will be splitting out ssui soon anyways

**Pull request closed without merging**
