### PR TITLE
[WIP] Fixed few failing tests related to Ansible Service.

### PR DESCRIPTION
**Pull request by sbulage**
## Purpose or Intent

Removed dependency for Ansible Catalog item as Module fixture with Function scoped fixture where it has been modified in tests.

- Fixed below tests.
- [x] test_embed_tower_exec_play_against
- [x] test_service_ansible_playbook_provision_in_requests
- [x] test_ansible_service_cloud_credentials

### PRT Run

{{ pytest: cfme/tests/ansible/test_embedded_ansible_services.py -k " test_embed_tower_exec_play_against or test_service_ansible_playbook_provision_in_requests" --long-running --use-provider=complete -svvv }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 21b15608ade71156b17930968313ce03edaf6e94

The *local* fixture **`ansible_catalog_item_funcscope`** is used in the following files:
- **cfme/tests/ansible/test_embedded_ansible_services.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by sbulage** [comment]
Depends upon #9475

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 2e3149ec64a2955b4682c2bf1247abd69ef8d87e

The *local* fixture **`ansible_catalog_item_funcscope`** is used in the following files:
- **cfme/tests/ansible/test_embedded_ansible_services.py**

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 19409e42c6f783882510274281cb41964584216a

The *local* fixture **`ansible_catalog_item_funcscope`** is used in the following files:
- **cfme/tests/ansible/test_embedded_ansible_services.py**
    - *test_ansible_service_cloud_credentials*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit d998e931b0930e99874958a149f3e0c4382aaf13

The *local* fixture **`ansible_catalog_item_funcscope`** is used in the following files:
- **cfme/tests/ansible/test_embedded_ansible_services.py**
    - *test_ansible_service_cloud_credentials*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by sbulage** [comment]
Changes are already in by this PR #9599 hence closing it.

**Pull request closed without merging**
