### PR TITLE
Tests to verify the collection of performance metrics 

### PR DESCRIPTION
**Pull request by nachandr**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 6619a022ba01d29a2f37e25cd9668ed4645fc1e4:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7e6cea9f5966695170a55b33b6c49ad1b1bad8cf:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8f60005c5b15124aed3872251162bb2da6ec9e9c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef988b165892b3efaf8f6e83b2a7902499565b79:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b21d57cafad17116bd1138ccddc1dc3cc9e2798e:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 944eb107acb321292e7e418944f936316d2c8a97:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 0de995e51067514cfc1658e2eb4a614759cc65a7:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5df5fc74ab00c7395606de3e59457a5a76d125ed:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 24e01f74bb6995f37a66d579541e1a0e94117944:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajohnso** [comment]
@nachandr , that sacrifices the existing cloud utilization tests since you use the generator to focus only on rhev and vmware for now.  Could you rename this file to something like test_utliization_metrics and then update the test_utilization to uncollect rhev and vmware so we don;t create redundancy.  That should bridge the gap until we add the cloud support in and generally the rest of the supported provider.

**Pull request closed without merging**
