### PR TITLE
[1LP][RFR] fixing provisioning form in service catalogs

### PR DESCRIPTION
**Pull request by izapolsk**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 73c274c5c3dd981ccf4f16a2c21f186865a17e44:

`cfme/fixtures/service_fixtures.py`:
- :bangbang: Line 42:5: **E265** *block comment should start with '# '*

`cfme/rest/gen_data.py`:
- :bangbang: Line 309:13: **E265** *block comment should start with '# '*

`cfme/tests/infrastructure/test_vm_clone.py`:
- :bangbang: Line 33:5: **E265** *block comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b31a13382f19f2270715a76978019de85dbf37ff:

`cfme/fixtures/service_fixtures.py`:
- :bangbang: Line 42:5: **E265** *block comment should start with '# '*

`cfme/rest/gen_data.py`:
- :bangbang: Line 309:13: **E265** *block comment should start with '# '*

`cfme/tests/infrastructure/test_vm_clone.py`:
- :bangbang: Line 33:5: **E265** *block comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by izapolsk** [comment]
PRT looks good. Failures in tests aren't related to my changes.

**Comment by lkhomenk** [comment]
PRT failures are related to ENV issues on rhv41
and I'll take care about PXE provision - that test is not 100% stable at the moment

**Comment by izapolsk** [comment]
@lkhomenk, awesome, ty

**Pull request merged**
