### PR TITLE
5.7 entry point locator change

### PR DESCRIPTION
**Pull request by sshveta**
Entry point locator changed in 5.7

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c24c8d7a2db50e3bbec3ea69f9941727695252ef:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit eb9b2f5a27d7cab45f375c2e660b995a5fa12668:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9162666f1ed8f82171de3e6ba9b5c45c25f67796:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by sshveta** [comment]
@mfalesni : The Service Catalog accordion also need to implement the Bootstrapview Internally.
Navigation [
                    lambda ctx: accordion_tree(
                        'All Services', ctx['catalog'], ctx['catalog_item'].name),
                    

fails because of the change.

**Comment by dajoRH** [comment]
Lint report for commit b23f78e84da65e303f0dd3551e4897df3d442d1c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by sshveta** [comment]
Fixed that error .

**Comment by dajoRH** [comment]
Lint report for commit 5576593512813793aeecc77fe5307434b510f448:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
@sshveta With regards to the accordion.tree - it should work for all trees. There were some issues with the initial tree detection code but then I fixed it and it should work reliably or fail predictibly.

**Comment by dajoRH** [comment]
Lint report for commit afa5605d1469c2f3300dd33392744e6d60ecea38:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 22fd989f7d7ed38904ee9c53fb4335fc9163198c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ce0efa3d624fa9e1078dbc92878095855f30f7ba:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8d6930a45257864addc609d9e2348dcd89e25aea:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d4dab9a3b96f7bb2a97b66f0c9d4306fdb7c26a0:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
