### PR TITLE
[WIP] Sprout - Allow usage by multipel teams by introducing a basic tenancy handling

### PR DESCRIPTION
**Pull request by mfalesni**
This is an update that should affect visibility of providers based on the groups assigned to the user logged in. The only thing that needs to be solved though is the fact that shepherd does not have split counts yet, as the counts are stored directly in the Group table.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 671b9a58af20f96d771ce18d7d78f0ea844977e1:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fcaa756c7f15d7319e2bd59c26f3a278685ccb1c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b8991779902471ae26b2afb79a68644e9c6dba01:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit aac157f29f47b7d827b1f7a086c4ecdcabdafa67:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c942fe037b7890d3c53815692519031531f75cf2:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f174aeed8d04ba2d475552c6f8278fbb21ea0f8d:

`sprout/appliances/api.py`:
- :bangbang: Line 285:17: **E131** *continuation line unaligned for hanging indent*

`sprout/appliances/migrations/0031_auto_20160506_0848.py`:
- :bangbang: Line 20:101: **E501** *line too long (114 > 100 characters)*
- :bangbang: Line 22:101: **E501** *line too long (139 > 100 characters)*
- :bangbang: Line 23:101: **E501** *line too long (172 > 100 characters)*
- :bangbang: Line 40:101: **E501** *line too long (104 > 100 characters)*

`sprout/appliances/models.py`:
- :bangbang: Line 445:101: **E501** *line too long (103 > 100 characters)*
- :bangbang: Line 450:1: **E303** *too many blank lines (3)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1fd183bde07b395a19f112ee0c24afcb5cd5510d:

`sprout/appliances/api.py`:
- :bangbang: Line 285:17: **E131** *continuation line unaligned for hanging indent*

`sprout/appliances/migrations/0031_auto_20160506_0848.py`:
- :bangbang: Line 20:101: **E501** *line too long (114 > 100 characters)*
- :bangbang: Line 22:101: **E501** *line too long (139 > 100 characters)*
- :bangbang: Line 23:101: **E501** *line too long (172 > 100 characters)*
- :bangbang: Line 40:101: **E501** *line too long (104 > 100 characters)*

`sprout/appliances/models.py`:
- :bangbang: Line 445:101: **E501** *line too long (103 > 100 characters)*
- :bangbang: Line 450:1: **E303** *too many blank lines (3)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b7e807f2f08d019fc9453add17c4a71e3b81405c:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ef7744b6af4847b67b84d411a13d45f0a0c06277:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by psav** [comment]
Big PR :) Is this THE ONE?

**Comment by mfalesni** [comment]
@psav yes, yes. I will rebase it again in order to make sure the migration schema is correct and then I can possibly plant the bomb :)

**Comment by dajoRH** [comment]
Lint report for commit d7cc6a4bed1136f7ef53cf75822203e1af319055:

`sprout/appliances/migrations/0034_provider_allow_renaming.py`:
- :bangbang: Line 18:101: **E501** *line too long (112 > 100 characters)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
BTW this can **only** be merged when I say so because of the migrations merging of the other pull requests

**Comment by dajoRH** [comment]
Lint report for commit d0fd850601ab8ae0baca517ba9249d15a0566322:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c79138d65b4c807bed47eca73092611bcee9a029:

`sprout/appliances/templatetags/appliances_extras.py`:
- :heavy_exclamation_mark: Line 47:29: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b2dedfee379a757aed6b9b3ec1bb7f86d35caf9a:

`sprout/appliances/tasks.py`:
- :red_circle: Line 96:33: **F841** *local variable 'e' is assigned to but never used*
- :red_circle: Line 125:37: **F841** *local variable 'e' is assigned to but never used*

`sprout/appliances/templatetags/appliances_extras.py`:
- :heavy_exclamation_mark: Line 47:29: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5142d65be58dce70a9edf425d47dd2a9d55e28bb:

Everything seems all right from lint perspective :smile: .

Commit inspection report:
**No commit flaws detected**.

*CFME QE Bot*

**Pull request merged**
