### PR TITLE
[WIPTEST] clean out cfme/__init__.py by moving the related classes to new places

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@psav i just realized that as is this may be a externally breaking change

**Comment by dajoRH** [comment]
Lint report for commit 6000f38e474c5abb083ce32e297255d6a1d80c13:

`cfme/automate/__init__.py`:
- :red_circle: Line 9:1: **F811** *redefinition of unused 'BaseLoggedInPage' from line 7*

`cfme/base/ui.py`:
- :bangbang: Line 6:101: **E501** *line too long (105 > 100 characters)*

`cfme/control/import_export.py`:
- :red_circle: Line 9:1: **F811** *redefinition of unused 'BaseLoggedInPage' from line 8*

`cfme/tests/configure/test_access_control.py`:
- :red_circle: Line 12:1: **F811** *redefinition of unused 'Credential' from line 10*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e13ee6b5865f471a3e7eaef439d3af2478270242:

`cfme/base/workaround.py`:
- :heavy_exclamation_mark: Line 55:41: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by psav** [comment]
This is still breaking it seems

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
closing as super-seeded by more granular changes after the rebase broke it

**Pull request closed without merging**
