### PR TITLE
[WIP] Automate delete multiple gob

### PR DESCRIPTION
**Pull request by john-dupuy**
{{ pytest: cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py::test_generic_object_button_delete_multiple }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 2e0d2b4623e9754f454b9c514e3ee10719d30848

The *local* fixture **`two_buttons`** is used in the following files:
- **cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py**
    - *test_generic_object_button_delete_multiple*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 04c7854d1e825614bebecf7b19c16d33bb98599f

The *local* fixture **`two_buttons`** is used in the following files:
- **cfme/tests/automate/generic_objects/buttons/test_generic_class_custom_button.py**
    - *test_generic_object_button_delete_multiple*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by mshriver** [comment]
image

**Comment by john-dupuy** [comment]
@valaparthvi I am not certain of exact steps, and I have had mixed results in reproducing locally. My thought is that this test will be blocked until the BZ is fixed, and then once the BZ is fixed the test should in theory pass. 

I agree that it is a flaky test for a flaky feature. It may be better to leave as manual until the BZ is fixed and we have more info on what causes this behavior. What do you think?

**Comment by valaparthvi** [comment]
Yeah, I guess so, better to keep it manual. Although, I'm sorry the work that you did wouldn't be merged rn :/
Also, I think it would be helpful to devs if you drop a comment on the BZ about this weird behaviour.

**Comment by john-dupuy** [comment]
Agreed on all points! Marking this WIP for now.

**Pull request closed without merging**
