### PR TITLE
support of navmazing's context parameters

### PR DESCRIPTION
**Pull request by izapolsk**
Purpose or Intent
=================
It is possible to use context params in navmazing due to some tricky navigation cases.
However, some object based on navmazing doesn't support such params.
So, I added appropriate args, kwargs in order to use them for some complex locations like VMs.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit b2fca1ab725d436905cf05fda0dc769d4213ae95:

`utils/appliance/endpoints/ui.py`:
- :bangbang: Line 221:23: **E201** *whitespace after '('*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a6aa5488a5d490f204de0aaa773ee6f4bb3b1d7f:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
Are you SURE we need this? It's a slippery slope. #imscared

**Comment by izapolsk** [comment]
:broken_heart: 
no, I'm not confident about this. But I didn't find any better way. 
I can also move context params to class methods but it doesn't look good as well.
You have mentioned that this can be resolved by moving to collections. I could do this if you give me a proper merged example.

**Comment by psav** [comment]
Going to close this for now as I think we can do it without once we get collections etc

**Pull request closed without merging**
