### PR TITLE
Fixed menu multi use

### PR DESCRIPTION
**Pull request by psav**
This allows new Menu objects to be created and use the "global"
stack. Ultimately there are some drawbacks but these are more
limitations on future enhancement than regressions

* You can't have a 5.5 and a 5.6 appliance in the same stack
* Menu needs total overhaul :) - but we knew that anyway

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 73180026b681ffa7b55a8023a687d6127158493a:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
let's see what PR tester says ... once it wakes up :)

**Comment by dajoRH** [comment]
Lint report for commit 1fc495e4511838d5b8daf528aed01eb340fbcffc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6756a68ce5f3e1414829955794d130e253cd3e63:

Everything seems all right :smile: .
*CFME QE Bot*

**Pull request merged**
