### PR TITLE
[1LP][RFR] Deployment Roles workaround

### PR DESCRIPTION
**Pull request by okolisny**
Added an option to use DeploymentRoles class on applications with different Infra providers connected (Openstack, VMWare etc.)
{{ pytest: cfme/tests/openstack/infrastructure/test_roles.py --use-provider=rhos_uc }}

### CODE REVIEW

**Comment by okolisny** [comment]
Tests were not collected in PRT run. Tested locally both cases

**Comment by rrasouli** [comment]
@okolisny please add in comment the BZ number

**Comment by RonnyPfannschmidt** [comment]
it took me a bit to realize that the code didn't pick on versions, but based on provider features,
can we take a look at encoding that more clearly?

**Comment by okolisny** [comment]
@rrasouli actually it is not about BZ in general..

**Comment by okolisny** [comment]
@RonnyPfannschmidt the reason I had created this PR is that Clusters menu item can be different, and it depends on providers that CFME has.
For example, if you have any provider (except Openstack) it called simply 'Clusters'. If you have some provider and the Openstack infra provider connected, it is - 'Clusters / Deployment Roles'.
If you have only Openstack infra provider it is - 'Deployment Roles'. And, I think the best way here to do is to **try** use the first title, and if it doesn't work, search the second

**Comment by okolisny** [comment]
@izapolsk By design, they have to fix these Openstack tests in your Jenkins also, but I'm very very OK with ignoring PRT results :-)

**Pull request merged**
