### PR TITLE
[1LP][RFR] Fix service order

### PR DESCRIPTION
**Pull request by quarckster**
Purpose
=================

In the latest CFME build `DialogFieldDropDownList` was reverted to `BootstrapSelect` in service order screen.

{{pytest: -v -k "test_service_ansible_playbook_order_credentials or test_provision_stack" --long-running}}

### CODE REVIEW

**Comment by lkhomenk** [comment]
LGTM. but i'd like to see PRT for few more order forms. I've restarted PRT

**Comment by quarckster** [comment]
PRT failed due to not related PR changes.

**Comment by quarckster** [comment]
@izapolsk orchestration templates update is required, some fields cannot be found on the order screen because they have wrong ids.

**Comment by jkrocil** [comment]
@quarckster Is it possible they bring `DialogFieldDropDownList` back?

**Comment by quarckster** [comment]
@jkrocil I don't know, it seems to me it's some kind of a mistake because it was introduced only in one place.

**Pull request merged**
