### PR TITLE
[WIP] Wrong provider object was passed, passed string, needs an object

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 4201f4e29f441c43061e67d1fab0a811f148f31a:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by jkrocil** [comment]
Now it's failing with:
```
>       service_catalogs.order(catalog_item.catalog, catalog_item)
E       TypeError: order() takes exactly 1 argument (3 given)

cfme/tests/services/test_pxe_service_catalogs.py:145: TypeError
```

Will you be taking care of that issue as well, @mfalesni?

**Comment by mfalesni** [comment]
@jkrocil I will take a look and will see what can I do about that.

**Comment by mfalesni** [comment]
It was fixed in meanwhile by #3929

**Pull request closed without merging**
