### PR TITLE
[1LP][RFR] Adding RHV tier as property to XML report

### PR DESCRIPTION
**Pull request by jan-zmeskal**
We're parsing jUnit XML output in Report Portal and it would be very nice to filter test cases there based on tiers. This change will expose RHV tiers as properties. Example here:

```
<testcase classname="cfme.tests.intelligence.reports.test_canned_corresponds" file="cfme/tests/intelligence/reports/test_canned_corresponds.py" line="115" name="test_operations_vm_on[rhv_cfme_integration]" time="10.0113461018">
  <properties>
    <property name="rhv_tier" value="rhv2"/>
  </properties>
</testcase>
```

If the tier is exposed as a property, we can propagate it into Report Portal as a tag.

Verification run [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CFME-DEV/job/cfme-5.9-rhv-4.2-integration-test-dev/). XML report from it [here](https://rhv-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CFME-DEV/job/cfme-5.9-rhv-4.2-integration-test-dev/lastSuccessfulBuild/artifact/xunit_output.xml).

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d0316ec53421921fb009e450116bb6aac601bb57:

`cfme/markers/rhv.py`:
- :red_circle: Line 23:1: **F401** *'attr' imported but unused*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
looks good, did you consider using just the tier numbers as values to ease parsing/processing?

**Comment by jan-zmeskal** [comment]
@RonnyPfannschmidt You're right that such approach would be easier for programmatic parsing. However I decided to go with the full name as this will be more expressive in Report Portal UI.

**Comment by RonnyPfannschmidt** [comment]
@jan-zmeskal thanks for providing context

**Pull request merged**
