### PR TITLE
[1LP][RFR] handling modals in 5.11

### PR DESCRIPTION
**Pull request by izapolsk**
trying to kill two rabbits by one shot

{{ pytest: --use-template-cache --long-running cfme/tests/services/test_config_provider_servicecatalogs.py }}

fixing issue: https://github.com/ManageIQ/integration_tests/issues/8836

this implementation isn't final yet.
I lean towards to creating parametraized decorator like

```
@handle_modal(action=cancel, wait='10s')
view.configuration.item_select('Remove Catalog Item'), handle_alert=True)

```

### CODE REVIEW

**Comment by izapolsk** [comment]
based on https://github.com/RedHatQE/widgetastic.patternfly/pull/92

**Comment by izapolsk** [comment]
please ignore PRT failures. there are too many issues in 5.11 atm. I can't handle them in one PR.

**Comment by digitronik** [comment]
@izapolsk @mshriver causing some failures; not only 511 but 510

```
RecursionError: maximum recursion depth exceeded
``` 
for some widgets like `TextInput` or other. Need solid debug.

**Comment by izapolsk** [comment]
@digitronik, could you please provide more details ? above one gives me not much info.

**Comment by digitronik** [comment]
I tried to fill `textinput` on `MethodAddView` and faceing error as its mixing with `MiqBrowser`
http://pastebin.test.redhat.com/766127

As per my observation `Model` `is_displayed` not proper... I avoid debug as it's working properly with revert commit. Please have a look on this mixing implementation.

**Pull request merged**
