### PR TITLE
New navigation for chargeback

### PR DESCRIPTION
**Pull request by otsuman**
{{ pytest: cfme/tests/intelligence/test_chargeback.py cfme/tests/intelligence/test_chargeback_assignments.py -k "test_assign_storage_enterprise or test_assign_compute_enterprise or test_edit_compute_chargeback or test_edit_storage_chargeback or test_delete_compute_chargeback or test_delete_storage_chargeback" }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d313a7c15e4508a42fbc6e469c5f41b5f21d4713:

`cfme/intelligence/chargeback.py`:
- :red_circle: Line 286:1: **F811** *redefinition of unused 'All' from line 209*
- :red_circle: Line 296:1: **F811** *redefinition of unused 'New' from line 219*
- :red_circle: Line 304:1: **F811** *redefinition of unused 'Details' from line 227*
- :red_circle: Line 312:1: **F811** *redefinition of unused 'Edit' from line 235*
- :red_circle: Line 370:1: **F811** *redefinition of unused 'All' from line 286*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fe3140d9d3a27b33a95d2ac11e9b42b14aa77f75:

`cfme/intelligence/chargeback.py`:
- :red_circle: Line 286:1: **F811** *redefinition of unused 'All' from line 209*
- :red_circle: Line 296:1: **F811** *redefinition of unused 'New' from line 219*
- :red_circle: Line 304:1: **F811** *redefinition of unused 'Details' from line 227*
- :red_circle: Line 312:1: **F811** *redefinition of unused 'Edit' from line 235*
- :red_circle: Line 370:1: **F811** *redefinition of unused 'All' from line 286*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 7775b697431097e3eb6baef078dc81b7bb1801fa:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
This is looking good, are there any ```am_i_here``` functions we could add here to assist in reducing navigation?

**Comment by dajoRH** [comment]
Lint report for commit 36072648e3f75e8c427439455a79959d08ff433c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by otsuman** [comment]
@psav added. But let's wait for PRT results

**Comment by dajoRH** [comment]
Lint report for commit 39e8c519273a3bda278e9e845a1a721ed1e3bce9:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
