### PR TITLE
[WIP] Adding Physical Providers API Tests

### PR DESCRIPTION
**Pull request by douglasgabriel**
__Adding tests__ for actions of physical providers api:
- test_create_provider
  
- test_edit_provider
  
- test_refresh_provider
  
- test_delete_provider

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 2d83b9afa76864948b2a41be25cf02619df0d27d:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/physical_infrastructure/test_provider_api.py`:
- :red_circle: Line 7:1: **F401** *'json' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.utils.log.logger' imported but unused*
- :bangbang: Line 17:13: **E261** *at least two spaces before inline comment*
- :bangbang: Line 21:11: **E261** *at least two spaces before inline comment*
- :bangbang: Line 25:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 28:7: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 28:13: **E203** *whitespace before ':'*
- :bangbang: Line 29:13: **E203** *whitespace before ':'*
- :bangbang: Line 30:17: **E203** *whitespace before ':'*
- :bangbang: Line 31:13: **E203** *whitespace before ':'*
- :bangbang: Line 33:9: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 38:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 40:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 42:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 43:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 46:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 49:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 50:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 53:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 56:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 57:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 61:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 62:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 66:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 68:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 70:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 71:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 73:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 74:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 75:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 76:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 77:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 78:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 79:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 81:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 82:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 83:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 84:5: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 84:13: **E231** *missing whitespace after ':'*
- :bangbang: Line 88:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 89:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 90:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 92:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 93:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 94:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 95:5: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 97:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 99:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 101:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 103:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 104:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 106:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 107:5: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 110:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 112:3: **E111** *indentation is not a multiple of four*
- :bangbang: Line 114:3: **E111** *indentation is not a multiple of four*

`cfme/utils/generators.py`:
- :bangbang: Line 27:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 27:29: **E231** *missing whitespace after ','*
- :heavy_exclamation_mark: Line 32:99: **W292** *no newline at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f004ef84ff402a7b53c29ad3a4911f1128fb7092:

`cfme/common/provider_views.py`:
- :bangbang: Line 185:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 578:90: **E231** *missing whitespace after ','*
- :bangbang: Line 578:101: **E501** *line too long (106 > 100 characters)*

`cfme/physical/physical_server.py`:
- :bangbang: Line 196:1: **E302** *expected 2 blank lines, found 1*

`cfme/physical/provider/__init__.py`:
- :bangbang: Line 111:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/physical_infrastructure/test_physical_server.py`:
- :red_circle: Line 6:1: **F401** *'cfme.physical.physical_server.PhysicalServerCollection' imported but unused*
- :red_circle: Line 8:1: **F401** *'cfme.test_requirements' imported but unused*
- :bangbang: Line 14:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 18:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 23:1: **E302** *expected 2 blank lines, found 1*

`cfme/tests/physical_infrastructure/test_provider_api.py`:
- :bangbang: Line 12:13: **E261** *at least two spaces before inline comment*
- :bangbang: Line 13:11: **E261** *at least two spaces before inline comment*
- :bangbang: Line 21:7: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 21:13: **E203** *whitespace before ':'*
- :bangbang: Line 22:13: **E203** *whitespace before ':'*
- :bangbang: Line 23:17: **E203** *whitespace before ':'*
- :bangbang: Line 24:13: **E203** *whitespace before ':'*
- :bangbang: Line 26:9: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 39:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 40:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 42:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 47:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 48:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 50:7: **E111** *indentation is not a multiple of four*
- :bangbang: Line 86:7: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 86:15: **E231** *missing whitespace after ':'*
- :bangbang: Line 98:7: **E121** *continuation line under-indented for hanging indent*
- :bangbang: Line 111:7: **E121** *continuation line under-indented for hanging indent*

`cfme/utils/generators.py`:
- :bangbang: Line 27:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 27:29: **E231** *missing whitespace after ','*
- :heavy_exclamation_mark: Line 32:99: **W292** *no newline at end of file*

Hmmm
:scream: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by douglasgabriel** [comment]
Closing this PR because the `/providers` endpoint is already being tested in other places indirectly, so it turns unnecessary

**Pull request closed without merging**
