### PR TITLE
[1LP][RFR]correct logger creation and artifactor logger creation

### PR DESCRIPTION
**Pull request by RonnyPfannschmidt**
there is probably need to get rid of create_logger in artifactor, its not clear how to do that off-hand

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit fd1663b69630432e9b16ae9370b6e3a97e6e982f:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by psav** [comment]
Artifactor logging no longer works after this new change

**Comment by dajoRH** [comment]
Lint report for commit 7ffe69b9473db82f0e6ec205f67724a3017024f1:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f8f47379dfe283cf882d32ce4316535754b64b58:

`artifactor/plugins/logger.py`:
- :red_circle: Line 15:1: **F401** *'os' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d1097fa76da2fa1d8e23c6f4424ec8704d8cfa78:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by psav** [comment]
Getting better, but we now have no timestamps in the artifactor log files.

**Comment by dajoRH** [comment]
Lint report for commit 06ea59728d9c1658ba60e60eeceea0a9e24725d5:

`utils/log.py`:
- :red_circle: Line 133:1: **F401** *'fauxfactory' imported but unused*
- :red_circle: Line 138:1: **F401** *'dt' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f4437d39f5df1b163728d0636b80b05a0303c0e0:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 57d8a1756c30579f5ac618708d74ff4a086d4038:

`utils/log.py`:
- :red_circle: Line 137:1: **F401** *'RotatingFileHandler' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 236c18720a7f49d9001566bef81d07ab79c2b177:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by psav** [comment]
Broken again in artifactor, I get Warning messages in the main cfme.log (and nothing else) and in all the contextual cfme.logs I get nothing at all

**Comment by dajoRH** [comment]
Lint report for commit 56655c3393841833c7af830b35855d1b3c63c6e6:

`utils/log.py`:
- :red_circle: Line 141:1: **F401** *'safe_string' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 08dfaf263b59c591ba174a4253fe9250c3e6707c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f45855a7b2784cd6041300432de0175d5a4cad12:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by psav** [comment]
Sorry ronny, I don't see any messages in the logger now :(

**Comment by dajoRH** [comment]
Lint report for commit 7213e82c61b426377388dfe229bdbb65ad7fe1d9:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 5c648f3d339fe2f0f189c72bd66b7aafd56455ae:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 94cfb472e54ea86daf872645cc087456ca88bf64:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f386d19396e92694d17bbc4523908a8f2d02f831:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8f170054cc565b796e223817488c9bf0562382b5:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
ID like to take another look at the occasionally failing message formatting

**Comment by dajoRH** [comment]
Lint report for commit 5963e9bbc8ec77223fc4c389a2f8fdde8f9badee:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8e4c637f4202a22309c6330b96b2a315dcee0036:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
