### PR TITLE
[RFR]ManageIQ Ansible Module Tests - Tags

### PR DESCRIPTION
**Pull request by pavelzag**
**Purpose or Intent**

{{pytest: cfme/tests/containers/test_manageiq_ansible_tags.py -v --use-provider cm-env2 }}

This test is testing the Tags function of MIQ Ansible Module which adds adds to objects inside ManageIQ.
For this test to run successfully it needs the git library added to requirements

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d64dd1197e0aa0d03c4f6ab495b7d96961cffab3:

`cfme/tests/containers/test_manageiq_ansible_tags.py`:
- :bangbang: Line 17:2: **E231** *missing whitespace after ','*
- :bangbang: Line 25:1: **E303** *too many blank lines (4)*
- :red_circle: Line 55:9: **F841** *local variable 'thevalue' is assigned to but never used*
- :red_circle: Line 55:41: **F821** *undefined name 'instance'*
- :red_circle: Line 57:63: **F821** *undefined name 'custom_attribute'*

`utils/ansible.py`:
- :bangbang: Line 247:101: **E501** *line too long (126 > 100 characters)*
- :bangbang: Line 248:101: **E501** *line too long (118 > 100 characters)*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 9cd2fb70bf3ba7c22a6a853b9c7a8df0597784e5:

`cfme/tests/containers/test_manageiq_ansible_tags.py`:
- :red_circle: Line 2:1: **F401** *'cfme.fixtures.pytest_selenium as sel' imported but unused*
- :red_circle: Line 4:1: **F401** *'cfme.containers.pod.Pod' imported but unused*
- :bangbang: Line 18:2: **E231** *missing whitespace after ','*
- :bangbang: Line 26:2: **E231** *missing whitespace after ','*
- :bangbang: Line 31:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 44:17: **E225** *missing whitespace around operator*

`utils/ansible.py`:
- :bangbang: Line 247:101: **E501** *line too long (126 > 100 characters)*
- :bangbang: Line 248:101: **E501** *line too long (118 > 100 characters)*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d23b9454c949e73a9fd9a2247ddf8202155ff124:

`cfme/tests/containers/test_manageiq_ansible_tags.py`:
- :red_circle: Line 2:1: **F401** *'cfme.fixtures.pytest_selenium as sel' imported but unused*
- :red_circle: Line 4:1: **F401** *'cfme.containers.pod.Pod' imported but unused*
- :bangbang: Line 18:2: **E231** *missing whitespace after ','*
- :bangbang: Line 26:2: **E231** *missing whitespace after ','*
- :bangbang: Line 31:1: **E302** *expected 2 blank lines, found 1*
- :bangbang: Line 44:17: **E225** *missing whitespace around operator*
- :heavy_exclamation_mark: Line 61:1: **W391** *blank line at end of file*

`utils/ansible.py`:
- :bangbang: Line 247:101: **E501** *line too long (126 > 100 characters)*
- :bangbang: Line 248:101: **E501** *line too long (118 > 100 characters)*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 98169dcc63f970ce3be0afce2db2de104233a078:

`cfme/tests/containers/test_manageiq_ansible_tags.py`:
- :heavy_exclamation_mark: Line 86:43: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by pavelzag** [comment]
@quarckster @RonnyPfannschmidt @otsuman @mkoura Hi guys, please have a look and let me know what can be done to push this through

**Comment by psav** [comment]
@jkrocil I remember in the past I think you were looking at these ansible modules, can you take this one please?

**Comment by jkrocil** [comment]
@pavelzag Please rebase so we can merge it.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request merged**
