### PR TITLE
[WIPTEST][NOMERGE] Parametrized chargebacks - cmqe

### PR DESCRIPTION
**Pull request by jkrocil**
@gshefer ^ This is what I meant when I said it should be parametrized instead of copypaste. Please see if this makes sense.

Potentially supersedes #4769.

**Changes before:**
+1,410 −218

**Changes after:**
+362 −347

**Collection before:**
```
Appliance's streams: [5.8, downstream]
<Module 'cfme/tests/containers/test_chargeback_for_images.py'>
  <Function 'test_image_chargeback_fixed_rate_1_hourly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_2_hourly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_hourly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_hourly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_io_hourly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_1_daily_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_2_daily_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_daily_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_daily_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_io_daily_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_1_weekly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_2_weekly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_weekly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_weekly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_io_weekly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_1_monthly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_fixed_rate_2_monthly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_monthly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_monthly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_io_monthly_fixed_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_daily_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_used_daily_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_used_daily_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_memory_used_monthly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_network_used_monthly_variable_rate[cm-env1]'>
  <Function 'test_image_chargeback_cpu_cores_used_monthly_variable_rate[cm-env1]'>
<Module 'cfme/tests/containers/test_chargeback_for_projects.py'>
  <Function 'test_project_chargeback_new_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_assign_compute_custom_rate[cm-env1]'>
  <Function 'test_project_chargeback_report_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_1_hourly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_2_hourly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_hourly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_hourly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_io_hourly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_1_daily_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_2_daily_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_daily_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_daily_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_io_daily_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_1_weekly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_2_weekly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_weekly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_weekly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_io_weekly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_1_monthly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_fixed_rate_2_monthly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_monthly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_monthly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_io_monthly_fixed_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_used_hourly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_daily_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_used_daily_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_used_daily_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_used_weekly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_memory_used_monthly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_network_used_monthly_variable_rate[cm-env1]'>
  <Function 'test_project_chargeback_cpu_cores_used_monthly_variable_rate[cm-env1]'>
```

**Collection after:**
```
<Module 'cfme/tests/containers/test_chargeback.py'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Image-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Image-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Image-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Image-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Image-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Image-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Image-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Image-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Image-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Image-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Image-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Project-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Project-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Hourly-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Project-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Project-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Daily-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Project-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Project-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Weekly-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Project-Fixed1]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Project-Fixed2]'>
  <Function 'test_chargeback_rate[cm-env2-fixed-Monthly-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Hourly-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Daily-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Weekly-Project-Memory]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Project-Network]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Project-CpuCores]'>
  <Function 'test_chargeback_rate[cm-env2-variable-Monthly-Project-Memory]'>
```

Not tested yet due to issues with accordion in widgetastic...

{{pytest: cfme/tests/containers/test_chargeback.py --use-provider cm-env2 --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
Ok, spent some more time on this this evening; current collection:
```
<Module 'cfme/tests/containers/test_chargeback.py'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Image-fixed-Hourly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Image-fixed-Hourly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-fixed-Hourly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-fixed-Hourly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-fixed-Hourly]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Image-fixed-Daily]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Image-fixed-Daily]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-fixed-Daily]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-fixed-Daily]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-fixed-Daily]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Image-fixed-Weekly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Image-fixed-Weekly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-fixed-Weekly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-fixed-Weekly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-fixed-Weekly]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Image-fixed-Monthly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Image-fixed-Monthly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-fixed-Monthly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-fixed-Monthly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-fixed-Monthly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-variable-Hourly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-variable-Hourly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-variable-Hourly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-variable-Daily]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-variable-Daily]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-variable-Daily]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-variable-Weekly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-variable-Weekly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-variable-Weekly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Image-variable-Monthly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Image-variable-Monthly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Image-variable-Monthly]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Project-fixed-Hourly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Project-fixed-Hourly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-fixed-Hourly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-fixed-Hourly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-fixed-Hourly]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Project-fixed-Daily]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Project-fixed-Daily]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-fixed-Daily]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-fixed-Daily]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-fixed-Daily]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Project-fixed-Weekly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Project-fixed-Weekly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-fixed-Weekly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-fixed-Weekly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-fixed-Weekly]'>
  <Function 'test_chargeback_rate_fixed_1[cm-env2-Project-fixed-Monthly]'>
  <Function 'test_chargeback_rate_fixed_2[cm-env2-Project-fixed-Monthly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-fixed-Monthly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-fixed-Monthly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-fixed-Monthly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-variable-Hourly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-variable-Hourly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-variable-Hourly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-variable-Daily]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-variable-Daily]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-variable-Daily]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-variable-Weekly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-variable-Weekly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-variable-Weekly]'>
  <Function 'test_chargeback_rate_cpu_cores[cm-env2-Project-variable-Monthly]'>
  <Function 'test_chargeback_rate_network_io[cm-env2-Project-variable-Monthly]'>
  <Function 'test_chargeback_rate_memory_used[cm-env2-Project-variable-Monthly]'>
```

There is indeed an issue in py.test that I had to work around, but it's not that big a deal. The code is still much shorter and cleaner but the collection took a small hit because of that. @gshefer Please run this in your env to confirm the performance is the same as with your original solution. Thanks.

**Comment by jkrocil** [comment]
@gshefer any news on this?

**Comment by jkrocil** [comment]
#4769 which includes these changes got merged today. Closing.

**Pull request closed without merging**
