### PR TITLE
[WIP] Middleware Server Widgetastic Conversion

### PR DESCRIPTION
**Pull request by rsnyman**
Convert Servers in Middleware to Widgetastic.

{{pytest: cfme/tests/middleware -v --use-provider hawkular}}

### CODE REVIEW

**Comment by rsnyman** [comment]
I'm waiting for the rest of the middleware conversions to be completed before I'll move this to RFR, as there will no doubt be some impact on this.

**Comment by hhovsepy** [comment]
PR with the rest of middleware conversation https://github.com/ManageIQ/integration_tests/pull/5083

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by hhovsepy** [comment]
@rsnyman I will suggest to merge this PR first, them I will rebase mine.

**Comment by rsnyman** [comment]
@hhovsepy and I chatted and he's pull my changes into his branch and will be continuing development there.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Pull request closed without merging**
