### PR TITLE
[1LP][RFR] Adding more Tower workflow tests

### PR DESCRIPTION
**Pull request by nachandr**
{{ py.test: cfme/tests/services/test_ansible_workflow_servicecatalogs.py }}

Added tests for automating ordering of Ansible workflow service based on project sync up and inventory sync up.

PRT results:
510 - PASS
511 - PASS

Note
The latest PRT run[0] passed on both 510 and 511.But, GH still shows the failure from run#34025
[0]http://infra-trackerbot2.cfme2.lab.eng.rdu2.redhat.com/pr/run/34040

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 5d8954b670fa14843e0b7885ae0418cb68c1fd5e

The *local* fixture **`ansible_workflow_catitem`** is used in the following files:
- **cfme/tests/services/test_ansible_workflow_servicecatalogs.py**
    - *test_tower_workflow_item*
    - *test_retire_ansible_workflow*

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Lint report for commit 5d8954b670fa14843e0b7885ae0418cb68c1fd5e:

`cfme/tests/services/test_ansible_workflow_servicecatalogs.py`:
- :red_circle: Line 53:70: **F821** *undefined name 'workflow_type'*
- :red_circle: Line 55:83: **F821** *undefined name 'workflow_type'*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 02cd07a7e4eb77614ce918106980c844b8898aeb

The *local* fixture **`ansible_workflow_catitem`** is used in the following files:
- **cfme/tests/services/test_ansible_workflow_servicecatalogs.py**
    - *test_tower_workflow_item*
    - *test_retire_ansible_workflow*

Please, consider creating a PRT run against these tests make sure your fixture changes do not break existing usage :smiley:

**Comment by lina-nikiforova** [comment]
@nachandr can you please take a look at PRT failures?

**Comment by john-dupuy** [comment]
If you look at PRT run # 34040 for 5.10z, this is actually passing. This is a small bug with PRT that @izapolsk should have a fix for soon.

**Pull request merged**
