### PR TITLE
[1LP][RFR] workaround for catalogs view which causes some tests fail

### PR DESCRIPTION
**Pull request by izapolsk**
Fix for test errors like:
```
    def step(self):
>       self.prerequisite_view.toolbar.policy.item_select('Edit Tags')
E       AttributeError: 'DetailsTemplateView' object has no attribute 'toolbar'
```
{{pytest: --long-running cfme/tests/services/test_orchestration_template.py}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 26752ce7a16d56dce5653b54b53fd2c9972a1627:

`cfme/services/catalogs/__init__.py`:
- :red_circle: Line 47:11: **N801** *class names should use CapWords convention*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit b690e0366fc6f1bdaf43fb8a075a988d09330751:

`cfme/services/catalogs/orchestration_template.py`:
- :bangbang: Line 179:101: **E501** *line too long (108 > 100 characters)*
- :bangbang: Line 247:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by izapolsk** [comment]
I'm going to merge this PR since I got two green checkmarks.

**Pull request merged**
