### PR TITLE
[1LP][RFR] Fixed strings in Control

### PR DESCRIPTION
**Pull request by quarckster**
Requires #7002 
{{pytest: -v -k "test_condition_crud or test_policy_crud" --long-running }}

### CODE REVIEW

**Comment by izapolsk** [comment]
@quarckster, please check PRT

**Comment by quarckster** [comment]
@izapolsk it failed because it requires #7002, that's why I marked it as NOMERGE

**Comment by mshriver** [comment]
Dependent PR merged, restarting PRT

**Comment by quarckster** [comment]
PRT failures not related to the changes.

**Pull request merged**
