### PR TITLE
[WIPTEST] Expression editor - Fixed int value and changed remove button xpath for newer versions

### PR DESCRIPTION
**Pull request by mmojzis**
{{pytest: cfme/tests/infrastructure/test_advanced_search_vms.py cfme/tests/infrastructure/test_advanced_search_host.py cfme/tests/infrastructure/test_advanced_search_providers.py -v --long-running}}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 875c314e3683026f3bab81c38f33e9ec5b43a8a2:

`cfme/web_ui/expression_editor.py`:
- :bangbang: Line 44:32: **E127** *continuation line over-indented for visual indent*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
What's the plan here, please? Are we still chasing this or should we close it?

**Comment by mmojzis** [comment]
@jkrocil I can see that somebody else already fixed it. So that's probably the reason why I didn't want to merge it anymore. So closing it.

**Pull request closed without merging**
