### PR TITLE
Add test_zone_add_maxlength and test_zone_add_dupe test

### PR DESCRIPTION
**Pull request by anewmanRH**
Adding tests for zones to cover cases max length(50) of name and description and Z. As well as creating a zone duplicate name and description.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit ffdeb936f4c5090e847e406b12bf3ebddf9117a0:

`cfme/tests/configure/test_zones.py`:
- :bangbang: Line 83:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 96:7: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1c58904483e878787143f15ba132fe47a7c7c74c:

`cfme/tests/configure/test_zones.py`:
- :bangbang: Line 83:1: **E303** *too many blank lines (3)*
- :heavy_exclamation_mark: Line 94:1: **W293** *blank line contains whitespace*
- :heavy_exclamation_mark: Line 94:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit bc9f656b85bb8af171f6b6f6545fd45de8289e2c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
Please sign this commit

**Comment by dajoRH** [comment]
Lint report for commit 5d86c095f04be080afd839bfe5725e4dd86f840c:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Pull request merged**
