### PR TITLE
[WIP]Use the externalized MIQ REST API Client

### PR DESCRIPTION
**Pull request by mfalesni**

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 70c09a1e711e6abed57248578546dd713ae8b1bd:

`utils/appliance.py`:
- :red_circle: Line 9:1: **N811** *constant imported as non constant*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a626f639a94719c97ee0a4f909aae0a0bae88719:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6ecfbd60f0d3fa28dca4c169b746af0f3bda2afc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e7030b8dfc25349c79dffc9efa1a5197db649144:

`cfme/cloud/instance.py`:
- :bangbang: Line 170:1: **E303** *too many blank lines (3)*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c96d95be89221c9e5ae5e1b68cbd3112e54f2554:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6161c6c7353b3b100ba0a0ddab88ae315f3254ed:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
This doesn't seem to make much damage.

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit ae0bd6ed3bd8e1b5958554418972845df688f8c4:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 521816d570a4ef1bbe6b40188e3ef8b2e7aa3037:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by mfalesni** [comment]
And I will just keep rebasing this thing over and over ...

**Comment by dajoRH** [comment]
Lint report for commit 6a2cc744528363d9181f5fe9285a482c79698371:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by mfalesni** [comment]
@mkoura Can you pick the changes in this one and adapt them for the updated client in https://github.com/ManageIQ/manageiq-api-client-python ?

**Pull request closed without merging**
