### PR TITLE
[1LP][RFR] Add host networks and subnets tests

### PR DESCRIPTION
**Pull request by jadhaj**
Purpose or Intent
=================
Added 2 tests:
1. test_host_networks
2. test_host_subnets

{{ pytest: cfme/tests/openstack/infrastructure/test_hosts.py::test_host_networks cfme/tests/openstack/infrastructure/test_hosts.py::test_host_subnets --use-provider rhos11}}

### CODE REVIEW

**Comment by jadhaj** [comment]
Local results:

2018-10-15 11:40:55,563 [I] [cfme] -------------- test_host_network[openstack_infra] result: passed --------------- (cfme/fixtures/log.py:70)
2018-10-15 15:02:31,178 [I] [cfme] -------------- test_host_subnets[openstack_infra] result: passed --------------- (cfme/fixtures/log.py:70)

**Comment by lina-nikiforova** [comment]
@jadhaj  The tests were uncollected in PRT and didn't run, can you make them run there?

**Comment by jadhaj** [comment]
@lina-nikiforova Rerun it via tracker bot and tests still uncollected:
http://infra-trackerbot2.cfme2.lab.eng.rdu2.redhat.com/pr/run/27873

Could it be an issue with PRT system ?

**Comment by digitronik** [comment]
@jadhaj @lina-nikiforova Its due to not provided `provider` with test run.

**Pull request merged**
