### PR TITLE
Messaging: Added support for MiddlewareMessaging. Fixed Menu Items for Middleware.

### PR DESCRIPTION
**Pull request by hhovsepy**
Added menu item, test cases.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit d9fdafe73b4c7f788cbdf7570b6803b15ac153fb:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by hhovsepy** [comment]
Need https://github.com/ManageIQ/wrapanapi/pull/71 to be merged and released for this PR.

**Comment by dajoRH** [comment]
Lint report for commit 6f6d00fc58e808310f48d93acd4f0456d912aeea:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 905824790d7e3029aa2cc3b791de23790f875c97:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by psav** [comment]
Re-running PRT seems something was up with the provider

**Comment by hhovsepy** [comment]
@psav seems like tests passed

**Pull request merged**
