### PR TITLE
[WIP] Configuration Management WT conversion + Collection + tests

### PR DESCRIPTION
**Pull request by vatsalparekh**
Purpose or Intent
=================
WT Conversion + Collection implementation + tests changes

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 494374d7bf38a30066d6e2fc6fc9d3fcc1298ea9:

`cfme/infrastructure/config_management.py`:
- :red_circle: Line 9:1: **F811** *redefinition of unused 'Dropdown' from line 9*
- :red_circle: Line 9:1: **F811** *redefinition of unused 'FlashMessages' from line 9*
- :red_circle: Line 9:1: **F401** *'widgetastic_patternfly.BootstrapNav' imported but unused*
- :red_circle: Line 33:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 33:32: **E261** *at least two spaces before inline comment*
- :bangbang: Line 33:33: **E262** *inline comment should start with '# '*
- :red_circle: Line 38:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 38:34: **E261** *at least two spaces before inline comment*
- :bangbang: Line 38:35: **E262** *inline comment should start with '# '*
- :bangbang: Line 110:14: **E222** *multiple spaces after operator*
- :red_circle: Line 128:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 128:22: **E261** *at least two spaces before inline comment*
- :bangbang: Line 128:23: **E262** *inline comment should start with '# '*
- :red_circle: Line 135:15: **N801** *class names should use CapWords convention*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 21e513e1755d21524d4d8df75c9b05fdf4e16d04:

`cfme/infrastructure/config_management.py`:
- :red_circle: Line 9:1: **F811** *redefinition of unused 'Dropdown' from line 9*
- :red_circle: Line 9:1: **F811** *redefinition of unused 'FlashMessages' from line 9*
- :red_circle: Line 9:1: **F401** *'widgetastic_patternfly.BootstrapNav' imported but unused*
- :red_circle: Line 33:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 33:32: **E261** *at least two spaces before inline comment*
- :bangbang: Line 33:33: **E262** *inline comment should start with '# '*
- :red_circle: Line 38:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 38:34: **E261** *at least two spaces before inline comment*
- :bangbang: Line 38:35: **E262** *inline comment should start with '# '*
- :bangbang: Line 110:14: **E222** *multiple spaces after operator*
- :red_circle: Line 128:11: **N801** *class names should use CapWords convention*
- :bangbang: Line 128:22: **E261** *at least two spaces before inline comment*
- :bangbang: Line 128:23: **E262** *inline comment should start with '# '*
- :red_circle: Line 135:15: **N801** *class names should use CapWords convention*
- :red_circle: Line 292:16: **F821** *undefined name 'Satellite'*
- :red_circle: Line 294:16: **F821** *undefined name 'AnsibleTower'*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e33a6348ded8fe5f3a8df0a7b9fb042c5e19b9c1:

`cfme/infrastructure/config_management.py`:
- :bangbang: Line 32:34: **E262** *inline comment should start with '# '*
- :bangbang: Line 37:36: **E262** *inline comment should start with '# '*
- :bangbang: Line 127:24: **E262** *inline comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit dc6b2bf8ba470a59c43e280de42c2a857e7067c6:

`cfme/infrastructure/config_management.py`:
- :bangbang: Line 33:9: **E265** *block comment should start with '# '*
- :bangbang: Line 39:9: **E265** *block comment should start with '# '*
- :bangbang: Line 130:9: **E265** *block comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by vatsalparekh** [comment]
Closing this because WT part got merged in PR #5536 
Will do a separate one for Collection

**Pull request closed without merging**
