### PR TITLE
Navmazing config

### PR DESCRIPTION
**Pull request by psav**
Purpose or Intent
=================

Moving to UIServer

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 11b2638ffb99b08b61bc9560c182f71e8470e5f9:

`utils/appliance/endpoints/ui.py`:
- :heavy_exclamation_mark: Line 261:1: **W391** *blank line at end of file*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 4611cd7f46875efc051b2e775a38b8e3bd06bc21:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
You have multiple commits in the PR. When you want your PR to be merged, please squash them. Do not squash them when working on the pull request as this allows to see the progress!

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 6533229794103465549fddf54e12341f50811782:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 60212b087d38dfc0c4acc46cac1cfa78a0d8c73d:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by izapolsk** [comment]
everything looks fine . 
I'm wondering what the implementation you're about to put into ssui.

**Pull request merged**
