### PR TITLE
[WIP]include saucelabs executor in browsermanager.

### PR DESCRIPTION
**Pull request by amavinag**
Purpose or Intent
=================
  * included saucelabs executor in BrowserManager.
  * the necessary yaml data needs to be included to cfme-data.

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit c7c3f14e8c23702cae4c9efe4ed3a8bb3584a5d2:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 8366e86d5d28083723ca978e62bea9c26d4b4f06:

Everything seems all right from lint perspective :smile: .

Commit inspection report:

**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit c2869897fe277d6bf0b443665881a48df2920a1f:

`markers/sauce.py`:
- :red_circle: Line 7:1: **F401** *'credentials' imported but unused*

Please, rectify these issues :smirk: .

Commit inspection report:

**No commit flaws detected**.

*CFME QE Bot*

**Comment by mshriver** [comment]
@amavinag is this PR still needed?

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 47ea846cb01e47714e566fb2babcfbe37a84c672:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit d32fa3d4fe6a02ec22ab5efc950d46d69fae2778:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 1fd4fcfc428d4ddc6280f5639a8508137d34530a:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 97065ed3ffadc326ebda23c955b7de5251446435:

Lint OK! :cake: :punch: :cookie: .


**No commit flaws detected**.
<mergeable/>

*CFME QE Bot*

**Comment by RonnyPfannschmidt** [comment]
after discussion on bluejeans wrt structuring we came up with an idea to handle the saucelabs metadata in fixtures/browser.py

in case of a saucelabs setup the setup/teardown hooks can handle browser stopping and starting as well as monkeypatching the browser configuration

after this starting point we can eventually discuss if/how part of those responsibilities can be moved into the browser manager

**Comment by mshriver** [comment]
@RonnyPfannschmidt Since Amogh has left the team, would you like to take over this branch?

**Comment by RonnyPfannschmidt** [comment]
@mshriver its already "mine" @psav asked me before, unfortunately i didn't self-assign

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by jkrocil** [comment]
@RonnyPfannschmidt I'm closing this PR since it seems to be going nowhere. Please open a new PR from your own branch once you have something.

**Pull request closed without merging**
