### PR TITLE
[WIP] Replace testgen with pytest.mark.provider in cfme/tests/intelligence & cfme/tests/middleware

### PR DESCRIPTION
**Pull request by ohiliazo**
__Updating tests__ Replacing testgen feature with pytest.mark.provider

### CODE REVIEW

**Comment by izapolsk** [comment]
@ohiliazo, congrats with  your first PR!

**Comment by dajoRH** [comment]
Lint report for commit 24cc5b6dd18d1d04f10307233a160fe8582b6248:

`cfme/tests/intelligence/reports/test_validate_chargeback_report.py`:
- :bangbang: Line 34:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 49285c5c61468595d22065c275a2a40ee15995bb:

`cfme/exceptions.py`:
- :bangbang: Line 133:101: **E501** *line too long (101 > 100 characters)*

`cfme/tests/intelligence/reports/test_validate_chargeback_report.py`:
- :bangbang: Line 34:101: **E501** *line too long (104 > 100 characters)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Pull request closed without merging**
