### PR TITLE
[1LP][RFR]Automate: test_edit_service_request_task

### PR DESCRIPTION
**Pull request by valaparthvi**
## Purpose or Intent
- __Adding tests__ `test_edit_service_request_task`

### PRT Run
{{ pytest: cfme/tests/services/test_rest_services.py -k "test_edit_service_request_task" --long-running -vvv }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 62dfb55bf1c9594d06cc93c141a1d6a2a2b98dc2

The *local* fixture **`request_task`** is used in the following files:
- **cfme/tests/services/test_rest_services.py**
    - *test_edit_service_request_task*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit a1a4070b78195a3ba792df3a477f0a9043b50197

The *local* fixture **`request_task`** is used in the following files:
- **cfme/tests/services/test_rest_services.py**
    - *test_edit_service_request_task*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by john-dupuy** [comment]
@valaparthvi Regarding these three PR's, #9320, #9321, and #9318, I see that the objects you're editing are different and therefore require different fixtures, but the tests are the same. Is there some way to parametrize them? Do you think it's worth it?

**Comment by valaparthvi** [comment]
Hey @john-dupuy, I had the same thought - parametrizing the test somehow since the test steps are same, but the setup will become messy. And I don't think to go through all the trouble to parametrize it is worth it, I think the current implementation is more readable and easy to understand.

**Comment by john-dupuy** [comment]
Makes sense @valaparthvi, just wanted to get your opinion on it!

**Pull request merged**
