### PR TITLE
Added new mixin for Timelines.

### PR DESCRIPTION
**Pull request by hhovsepy**
Used that TimelinesMixin in Hawkular provider. Added new test for hawkular timelines page. Moved general deployment functions into separate utility.

{{pytest: cfme/tests/middleware/test_provider_timelines.py cfme/tests/middleware/test_middleware_deployment.py -v --long-running --use-provider hawkular }}

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit f8ec33a02f2125380f3ade328e6501fc194c648b:

`cfme/common/__init__.py`:
- :heavy_exclamation_mark: Line 497:31: **W292** *no newline at end of file*

Please, rectify these issues :smirk: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 107b23d9216026ccdc6d2e2e06985bff35f92815:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit a37f6147a03aac4358d3cabb0a36ecde385857f9:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 68649dfaa6ee1726ad14ea6405e46927802fea40:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 78af76e99506685185c1620f07f7c3b8abd7d966:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
One failure is fixed in https://github.com/ManageIQ/integration_tests/pull/3162, second one started failing because of our test environment.

**Comment by dajoRH** [comment]
Lint report for commit 38ca9d318c9eeea14732304e919d2ea756e1b8fd:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by hhovsepy** [comment]
@psav @mfalesni this PR became blocker of us

**Comment by mfalesni** [comment]
Giving it a second go through the PR tester with correct metadata.

**Comment by dajoRH** [comment]
Lint report for commit ce94faf8134100eea84a0a5bef8226ee988c03bc:

Everything seems all right :smile: .
*CFME QE Bot*

**Comment by mfalesni** [comment]
@hhovsepy ~90%, asking for result analysis

**Comment by hhovsepy** [comment]
@mfalesni thanks,
rerun of tests fail because of our broken environment.

**Comment by mfalesni** [comment]
:+1:

**Pull request merged**
