### PR TITLE
[WIPTEST] Fix for test failures in access_control

### PR DESCRIPTION
**Pull request by LandoCalrizzian**
Updating test for deleting default groups due to the change vers > 5.7

Updating tests that are failing in cfme version >= 5.7. Also updating access_control module and test to move selenium automation out of the tests in into the access_control module.  Widgetastic and navmazing updates are still needed but will be implemented in separate PR's

### CODE REVIEW

**Comment by dajoRH** [comment]
Lint report for commit 2a45e6170dc10a88a64659a8a83d006d25529589:

`cfme/configure/access_control.py`:
- :bangbang: Line 10:9: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 297:9: **E122** *continuation line missing indentation or outdented*
- :red_circle: Line 302:41: **F841** *local variable 'fme' is assigned to but never used*
- :red_circle: Line 306:9: **F841** *local variable 'flash_success_msg' is assigned to but never used*
- :red_circle: Line 331:9: **F841** *local variable 'flash_success_msg' is assigned to but never used*
- :red_circle: Line 332:9: **F841** *local variable 'flash_fail_msg' is assigned to but never used*

`cfme/exceptions.py`:
- :bangbang: Line 374:1: **E302** *expected 2 blank lines, found 1*
- :heavy_exclamation_mark: Line 375:71: **W291** *trailing whitespace*

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 286:5: **E265** *block comment should start with '# '*
- :bangbang: Line 287:5: **E265** *block comment should start with '# '*
- :bangbang: Line 288:5: **E265** *block comment should start with '# '*
- :bangbang: Line 289:5: **E265** *block comment should start with '# '*
- :bangbang: Line 290:5: **E265** *block comment should start with '# '*
- :bangbang: Line 294:1: **E302** *expected 2 blank lines, found 1*
- :red_circle: Line 295:5: **F401** *'cfme.exceptions.FlashMessageException' imported but unused*
- :red_circle: Line 296:5: **F841** *local variable 'flash_msg' is assigned to but never used*
- :bangbang: Line 298:5: **E265** *block comment should start with '# '*
- :bangbang: Line 299:5: **E265** *block comment should start with '# '*
- :bangbang: Line 302:5: **E265** *block comment should start with '# '*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit fdadb35d2cd34ff10c17912519e1acfb4b46d373:

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 286:5: **E265** *block comment should start with '# '*
- :bangbang: Line 287:5: **E265** *block comment should start with '# '*
- :bangbang: Line 288:5: **E265** *block comment should start with '# '*
- :bangbang: Line 289:5: **E265** *block comment should start with '# '*
- :bangbang: Line 290:5: **E265** *block comment should start with '# '*

Hmmm
:frowning: You might like to check the lint of your code :point_up: 


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit 544620662313b8172df3e05922b33508b2d5d324:

`cfme/configure/access_control.py`:
- :bangbang: Line 245:13: **E123** *closing bracket does not match indentation of opening bracket's line*
- :bangbang: Line 300:17: **E126** *continuation line over-indented for hanging indent*
- :bangbang: Line 302:9: **E265** *block comment should start with '# '*

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 288:45: **E701** *multiple statements on one line (colon)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit f1e255ad1a8376d932f95f5643a446d2c6ef238a:

`cfme/configure/access_control.py`:
- :bangbang: Line 92:18: **E203** *whitespace before ':'*
- :bangbang: Line 114:18: **E203** *whitespace before ':'*

`cfme/tests/configure/test_access_control.py`:
- :bangbang: Line 289:45: **E701** *multiple statements on one line (colon)*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by LandoCalrizzian** [comment]
Closing pull request since can't be easily rebased after merge of #4725. Submitting a new PR to resolve test issues

**Pull request closed without merging**
