### PR TITLE
[WIP]Fixture min hosts

### PR DESCRIPTION
**Pull request by prichard77**

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit e813643a20e8199dc9261b469c2d94f6039114f7

The *local* fixture **`setup_provider_min_hosts`** is used in the following files:
- **cfme/tests/infrastructure/test_host.py**
    - *test_infrastructure_hosts_refresh_multi*
    - *test_compare_hosts_from_provider_allhosts*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by dajoRH** [comment]
Lint report for commit e813643a20e8199dc9261b469c2d94f6039114f7:

`cfme/tests/infrastructure/test_host.py`:
- :bangbang: Line 352:24: **E251** *unexpected spaces around keyword / parameter equals*
- :bangbang: Line 399:5: **E265** *block comment should start with '# '*

Please, rectify these issues :smirk: .


**No commit flaws detected**.

*CFME QE Bot*

**Comment by dajoRH** [comment]
Would you mind rebasing this Pull Request against latest master, please? :trollface:
*CFME QE Bot*

**Comment by prichard77** [comment]
The content of this PR is included in other PRs.

**Pull request closed without merging**
