### PR TITLE
[1LP][RFR] Fix OpenStack volume tests

### PR DESCRIPTION
**Pull request by jaryn**
## Purpose or Intent
__Fixing__ volume tests. It seems the `storage_manager` attribute was removed without changing the tests. Also the `size` attribute was changed to `volume_size`.

As can be currently seen on trackerbot, all tests executed in this PR were failing like this:
```
>                                         provider=provider)
E       TypeError: create() got an unexpected keyword argument 'storage_manager'

cfme/tests/openstack/cloud/test_volume_backup.py:31: TypeError
TypeError
b"create() got an unexpected keyword argument 'storage_manager'"
```

Many of them started working with these changes.

{{pytest: cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_detach_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_instances.py::test_instance_attach_volume[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_create_backup_of_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_create_volume_backup[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_create_volume_incremental_backup[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_incr_backup_of_attached_volume_crud[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_restore_incremental_backup[openstack-13] cfme/tests/openstack/cloud/test_volume_backup.py::test_restore_volume_backup[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_create_volume[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_create_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_delete_volume[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_delete_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_edit_volume[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_edit_volume_with_type[openstack-13] cfme/tests/openstack/cloud/test_volumes.py::test_volume_attach_detach_instance[openstack-13]
--long-running -v --use-provider complete }}

### CODE REVIEW

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 471324456d11822dda8516a0846336073e3e3e76

The *local* fixture **`volume`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume*
    - *test_edit_volume*
    - *test_delete_volume*
    - *test_volume_attach_detach_instance*

The *local* fixture **`volume_backup`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volume_backup.py**
    - *incremental_backup*
    - *attached_volume*
    - *test_create_volume_backup*
    - *test_restore_volume_backup*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit a57d72a9bcadccbac2878320508b92de7a6ee198

The *local* fixture **`volume`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume*
    - *test_edit_volume*
    - *test_delete_volume*
    - *test_volume_attach_detach_instance*

The *local* fixture **`volume_backup`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volume_backup.py**
    - *incremental_backup*
    - *attached_volume*
    - *test_create_volume_backup*
    - *test_restore_volume_backup*

The *local* fixture **`volume_with_type`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume_with_type*
    - *test_edit_volume_with_type*
    - *test_delete_volume_with_type*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit cdb84e8f814ff64464c697ebfb4541ded785699a

The *local* fixture **`volume`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume*
    - *test_edit_volume*
    - *test_delete_volume*
    - *test_volume_attach_detach_instance*

The *local* fixture **`volume_with_type`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume_with_type*
    - *test_edit_volume_with_type*
    - *test_delete_volume_with_type*

The *local* fixture **`volume_backup`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volume_backup.py**
    - *incremental_backup*
    - *attached_volume*
    - *test_create_volume_backup*
    - *test_restore_volume_backup*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by dajoRH** [comment]
I detected some fixture changes in commit 830ff0e3b994b47f719708c3f1790604904adad3

The *local* fixture **`volume`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume*
    - *test_edit_volume*
    - *test_delete_volume*
    - *test_volume_attach_detach_instance*

The *local* fixture **`volume_with_type`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volumes.py**
    - *test_create_volume_with_type*
    - *test_edit_volume_with_type*
    - *test_delete_volume_with_type*

The *local* fixture **`volume_backup`** is used in the following files:
- **cfme/tests/openstack/cloud/test_volume_backup.py**
    - *incremental_backup*
    - *attached_volume*
    - *test_create_volume_backup*
    - *test_restore_volume_backup*

Please, consider creating a PRT run to make sure your fixture changes do not break existing usage :smiley:

**Comment by john-dupuy** [comment]
@jaryn There are still several failures in PRT, do you want to fix them in this PR or with follow-up PRs?

**Comment by jaryn** [comment]
> @jaryn There are still several failures in PRT, though the initial `TypeError` is gone now. Do you want to fix them in this PR or with follow-up PRs?

I would like to merge this and fix the others some other day.

**Comment by john-dupuy** [comment]
Ack, that's fine by me, what do you think @mshriver?

**Pull request merged**
